### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: net.jpountz.xxhash.StreamingXXHash32.<init>(I)V

### ISSUE THREAD

**Issue by AlexNfr** [jankotek/mapdb#1005]
Hi!

I received the following error message:

_Exception in thread "main" java.lang.NoSuchMethodError: net.jpountz.xxhash.StreamingXXHash32.<init>(I)V
	at net.jpountz.xxhash.AbstractStreamingXXHash32Java.<init>(AbstractStreamingXXHash32Java.java:27)
	at net.jpountz.xxhash.StreamingXXHash32JavaSafe.<init>(StreamingXXHash32JavaSafe.java:27)
	at net.jpountz.xxhash.StreamingXXHash32JavaSafe$Factory.newStreamingHash(StreamingXXHash32JavaSafe.java:21)
	at net.jpountz.xxhash.XXHashFactory.newStreamingHash32(XXHashFactory.java:229)
	at net.jpountz.xxhash.XXHashFactory.<init>(XXHashFactory.java:189)
	at net.jpountz.xxhash.XXHashFactory.instance(XXHashFactory.java:47)
	at net.jpountz.xxhash.XXHashFactory.safeInstance(XXHashFactory.java:94)
	at net.jpountz.xxhash.XXHashFactory.fastestJavaInstance(XXHashFactory.java:128)
	at net.jpountz.xxhash.XXHashFactory.fastestInstance(XXHashFactory.java:153)
	at org.mapdb.CC.<clinit>(CC.java:47)
	at org.mapdb.serializer.SerializerByteArray.<clinit>(SerializerByteArray.java:15)
	at org.mapdb.Serializer.<clinit>(Serializer.java:315)
	at org.mapdb.DB.<clinit>(DB.kt:45)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:477)
	at exercise.mapdb.MapdbDemo1.main(MapdbDemo1.kt:12)_

when compiling a simple example:

```
package exercise.mapdb

import org.mapdb.DBMaker
import org.mapdb.Serializer
import kotlin.test.assertEquals

object MapdbDemo1
{
    @JvmStatic
    fun main(vararg args: String)
    {
        val db = DBMaker.tempFileDB().make()

        val dbMap = db.hashMap("Demo1Map", Serializer.STRING, Serializer.STRING)
                        .createOrOpen()

        val welcomeKey = "Welcome"
        val welcomeMessage = "Hi, Alex!"
        dbMap[welcomeKey] = welcomeMessage

        assertEquals(welcomeMessage, dbMap[welcomeKey])

        dbMap.close()
    }
}
```

**Comment by AlexNfr** [comment]
Used dependencies:

![изображение](https://user-images.githubusercontent.com/19978596/154952095-18327fe3-c567-497b-9770-b2830b937294.png)
