### ISSUE TITLE
NoClassDefFoundError regarding EnumEntries since MapDB 3.1.0

### ISSUE THREAD

**Issue by chkpnt** [jankotek/mapdb#1042]
I've just updated MapDB from 3.0.10 to 3.1.0.

Now I'm getting the following error:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.mapdb.DB]: Factory method 'sessionsDB' threw exception; nested exception is java.lang.NoClassDefFoundError: kotlin/enums/EnumEntriesKt
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.31.jar!/:5.3.31]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-5.3.31.jar!/:5.3.31]
        ... 54 common frames omitted
Caused by: java.lang.NoClassDefFoundError: kotlin/enums/EnumEntriesKt
        at org.mapdb.DBMaker$StoreType.<clinit>(DBMaker.kt:35) ~[mapdb-3.1.0.jar!/:na]
        at org.mapdb.DBMaker.fileDB(DBMaker.kt:50) ~[mapdb-3.1.0.jar!/:na]
        at org.mapdb.DBMaker.fileDB(DBMaker.kt:54) ~[mapdb-3.1.0.jar!/:na]
```

As there is no [changelog](https://mapdb.org/changelog/) that mentions required migration steps: What to do? I guess there is a runtime dependency missing. I'm using Java 11.

**Comment by carlosjepard** [comment]
I'm getting the same error

**Comment by a7l97nn** [comment]
Same problem for me with Java 21

**Comment by zeroonead** [comment]
Same problem for me with Java 1.8

**Comment by moyangzhan** [comment]
Upgrade kotlin-stdlib to 2.0 can fix this problem

**Comment by chkpnt** [comment]
I've migrated to the [Eclipse Serializer](https://github.com/eclipse-serializer/serializer/) from the [EclipseStore](https://eclipsestore.io/) project, so I'm no longer facing this issue.
