### ISSUE TITLE
BTreeMap broken with custom value serializer 

### ISSUE THREAD

**Issue by krr** [jankotek/mapdb#162]
Hi!

I am considering MapDB for a new project, but I think the **BTreeMap** implementation is broken when using a custom value serializer.

I have written up a small test which displays the behavior. Please see below.

The test first creates a HashMap with a custom serializer, puts in some values, commits and closes the database. It then reopens the database, and fetches the values. That works nicely.

The test then creates a BTreeMap with a custom serializer and attempts the same operations as for the HashMap. Unfortunately, it fails.

Running it, I get the following output:

```
--- Testing HashMap with custom serializer
Putting and committing data
Custom serializer called with 'MyValue{string='one'}'
Custom serializer called with 'MyValue{string='two'}'
Closing and reopening db
Reading back data
Entry id = 2, contents = MyValue{string='two'}
Entry id = 1, contents = MyValue{string='one'}
--- Testing BTreeMap with custom serializer
Custom serializer called with 'null'
Custom serializer called with 'null'
Putting and committing data
Custom serializer called with 'null'
Custom serializer called with 'null'
Custom serializer called with 'MyValue{string='one'}'
Custom serializer called with 'MyValue{string='two'}'
Closing and reopening db
Exception in thread "main" java.lang.InternalError: data were read beyond record size, check your serializer
    at org.mapdb.StoreDirect.get2(StoreDirect.java:335)
    at org.mapdb.StoreWAL.get2(StoreWAL.java:195)
    at org.mapdb.StoreWAL.get(StoreWAL.java:182)
    at org.mapdb.EngineWrapper.get(EngineWrapper.java:51)
    at org.mapdb.AsyncWriteEngine.get(AsyncWriteEngine.java:299)
    at org.mapdb.CacheHashTable.get(CacheHashTable.java:92)
    at org.mapdb.EngineWrapper.get(EngineWrapper.java:51)
    at org.mapdb.BTreeMap$BTreeIterator.pointToStart(BTreeMap.java:811)
    at org.mapdb.BTreeMap$BTreeIterator.<init>(BTreeMap.java:778)
    at org.mapdb.BTreeMap$BTreeEntryIterator.<init>(BTreeMap.java:1002)
    at org.mapdb.BTreeMap.entryIterator(BTreeMap.java:1497)
    at org.mapdb.BTreeMap$EntrySet.iterator(BTreeMap.java:1702)
    at refactored.experiment.Problem.printEntries(Problem.java:65)
    at refactored.experiment.Problem.testBTreeMap(Problem.java:116)
    at refactored.experiment.Problem.main(Problem.java:128)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Reading back data
```

As you can see, the custom serializer is invoked several times with a 'null' argument.  Tracking it back into the MapDB implementation, it appears that it attempts to serialize a (empty) BTree leaf node, with 4 null values, using the custom serializer.

If I disable the custom value serializer, it appears to work. However, not being able to use a custom serializer is a showstopper for me :(

Here's the test case:

```
package problem;

import org.mapdb.DB;
import org.mapdb.DBMaker;
import org.mapdb.Serializer;

import java.io.*;
import java.util.Map;


public class Problem {

   public static class MyValue implements Serializable {
      private String string;

      public MyValue(String string) {
         this.string = string;
      }

      @Override
      public String toString() {
         return "MyValue{" + "string='" + string + '\'' + '}';
      }


      @Override
      public boolean equals(Object o) {
         if (this == o) return true;
         if (!(o instanceof MyValue)) return false;

         MyValue myValue = (MyValue) o;
         if (!string.equals(myValue.string)) return false;
         return true;
      }


      @Override
      public int hashCode() {
         return string.hashCode();
      }
   }

   public static class MyValueSerializer implements Serializable, Serializer<MyValue> {

      @Override
      public void serialize(DataOutput out, MyValue value) throws IOException {
         if (value == null) {
            System.err.println("Custom serializer called with 'null'");
         } else {
            System.out.println("Custom serializer called with '" + value + "'");
            out.writeUTF(value.string);
         }
      }

      @Override
      public MyValue deserialize(DataInput in, int available) throws IOException {
         String s = in.readUTF();
         return new MyValue(s);
      }
   }

   private static void printEntries(Map<Long, MyValue> map) {
      System.out.println("Reading back data");
      for (Map.Entry<Long, MyValue> entry : map.entrySet()) {
         System.out.println("Entry id = " + entry.getKey() + ", contents = " + entry.getValue().toString());
      }
   }

   private static void testHashMap(File path) {
      System.out.println("--- Testing HashMap with custom serializer");

      DB db = DBMaker.newFileDB(path).make();
      Map<Long, MyValue> map = db.createHashMap("map")
                                 .valueSerializer(new MyValueSerializer())
                                 .make();
      db.commit();

      System.out.println("Putting and committing data");
      map.put(1L, new MyValue("one"));
      map.put(2L, new MyValue("two"));
      db.commit();

      System.out.println("Closing and reopening db");
      db.close();
      map = null;

      db = DBMaker.newFileDB(path).make();
      map = db.getHashMap("map");

      printEntries(map);
   }

   private static void testBTreeMap(File path) {
      System.out.println("--- Testing BTreeMap with custom serializer");

      DB db = DBMaker.newFileDB(path).make();
      Map<Long, MyValue> map = db.createTreeMap("map")
                                 .valueSerializer(new MyValueSerializer())
                                 .make();
      db.commit();

      System.out.println("Putting and committing data");
      map.put(1L, new MyValue("one"));
      map.put(2L, new MyValue("two"));
      db.commit();

      System.out.println("Closing and reopening db");
      db.close();
      map = null;

      db = DBMaker.newFileDB(path).make();
      map = db.getTreeMap("map");

      printEntries(map);
   }

   public static void main(String[] args) {
      try {
         testHashMap(new File("/tmp/hashtest"));
      } catch (Exception e) {
         e.printStackTrace(System.err);
      }

      try {
         testBTreeMap(new File("/tmp/treetest"));
      } catch (Exception e) {
         e.printStackTrace(System.err);
      }
   }
}
```

**Comment by dzlab** [comment]
i'm seeing this issue when using version `3.0.0-M5` with `GroupSerializer` for serializing custmo values.

**Comment by jankotek** [comment]
@dzlab would you provide more details and stacktrace? thanks

**Comment by dzlab** [comment]
I've endup using byte array serliazer, i.e. I serialize/deserialize my object before putting to getting it from the cache. I'll try to reproduce the issue in a separate sample and submit it here.
