### ISSUE TITLE
 IllegalAccessError: WAL not empty; commit first

### ISSUE THREAD

**Issue by jankotek** [jankotek/mapdb#219]
So I'm not doing any puts/writes before my compact thread kicks in,  but 
I'm getting this error, what is the WAL ? This happens right after a make.

Caused by: java.lang.IllegalAccessError: WAL not empty; commit first, than 
compact
at org.mapdb.StoreWAL.compact(StoreWAL.java:742)
at org.mapdb.EngineWrapper.compact(EngineWrapper.java:111)

Should I be reading the MapDb source code to solve my issues or is this an 
appropriate forum to post questions?

credit: Jay Houghton

**Comment by zhoupo** [comment]
Hi,

I put "localDb.commit();" before every "localDb.compact();" but still get the exception:

Exception in thread "Thread-0" java.lang.IllegalAccessError: WAL not empty; commit first, than compact
        at org.mapdb.StoreWAL.compactPreUnderLock(StoreWAL.java:1100)
        at org.mapdb.StoreDirect.compact(StoreDirect.java:810)
        at org.mapdb.EngineWrapper.compact(EngineWrapper.java:130)
        at org.mapdb.EngineWrapper.compact(EngineWrapper.java:130)
        at org.mapdb.DB.compact(DB.java:1626)

My commit(), compact() are located in Thread.run(), and my DBMaker configuration is: 
        DB localDb = DBMaker.newFileDB(new File(filename)).closeOnJvmShutdown().make();

store size: 471M, including *.compact, *.compact.p, *.p, *.t
java -version: java version "1.8.0_11"
uname -r: 2.6.32-279.el6.x86_64

Thanks!
