### ISSUE TITLE
Writer thread failed exception with stack

### ISSUE THREAD

**Issue by ghost** [jankotek/mapdb#258]
If I run the test case below two times, the second run fails with the exception pasted.

Removing "asyncWriteEnable" seems to "fix" the problem.

```
Exception in thread "main" java.lang.RuntimeException: Writer thread failed
    at org.mapdb.AsyncWriteEngine.checkState(AsyncWriteEngine.java:290)
    at org.mapdb.AsyncWriteEngine.update(AsyncWriteEngine.java:389)
    at org.mapdb.Caches$LRU.compareAndSwap(Caches.java:114)
    at org.mapdb.Atomic$Long.compareAndSet(Atomic.java:338)
    at org.mapdb.Queues$SimpleQueue.poll(Queues.java:108)
    at org.mapdb.Queues$SimpleQueue.clear(Queues.java:161)
        at TestMapDB.java:311
Caused by: java.lang.ArrayIndexOutOfBoundsException: 205
    at org.mapdb.StoreWAL.longStackPut(StoreWAL.java:984)
    at org.mapdb.StoreDirect.freePhysPut(StoreDirect.java:992)
    at org.mapdb.StoreWAL.delete(StoreWAL.java:521)
    at org.mapdb.EngineWrapper.delete(EngineWrapper.java:74)
    at org.mapdb.AsyncWriteEngine.access$001(AsyncWriteEngine.java:72)
    at org.mapdb.AsyncWriteEngine.runWriter(AsyncWriteEngine.java:203)
    at org.mapdb.AsyncWriteEngine$WriterRunnable.run(AsyncWriteEngine.java:156)
    at java.lang.Thread.run(Unknown Source)
Exception in thread "MapDB shutdown" java.lang.RuntimeException: Writer thread failed
    at org.mapdb.AsyncWriteEngine.checkState(AsyncWriteEngine.java:290)
    at org.mapdb.AsyncWriteEngine.close(AsyncWriteEngine.java:443)
    at org.mapdb.EngineWrapper.close(EngineWrapper.java:81)
    at org.mapdb.Caches$LRU.close(Caches.java:130)
    at org.mapdb.DBMaker$1.run(DBMaker.java:724)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 205
    at org.mapdb.StoreWAL.longStackPut(StoreWAL.java:984)
    at org.mapdb.StoreDirect.freePhysPut(StoreDirect.java:992)
    at org.mapdb.StoreWAL.delete(StoreWAL.java:521)
    at org.mapdb.EngineWrapper.delete(EngineWrapper.java:74)
    at org.mapdb.AsyncWriteEngine.access$001(AsyncWriteEngine.java:72)
    at org.mapdb.AsyncWriteEngine.runWriter(AsyncWriteEngine.java:203)
    at org.mapdb.AsyncWriteEngine$WriterRunnable.run(AsyncWriteEngine.java:156)
    at java.lang.Thread.run(Unknown Source)

```

Test case:

```

File tmpDir = new File(System.getProperty("user.home")+"/.demo");
tmpDir.mkdir();
File tmp = new File(tmpDir.getAbsolutePath()+"/demo_undolog.txt");

DB db = DBMaker.newFileDB(tmp)
        .closeOnJvmShutdown()
        .compressionEnable()
        .cacheLRUEnable()
        .asyncWriteEnable()                
        .make();        

BlockingQueue<Object> map = db.getStack("undolog");

// Show first 100, if any
for(int j=0; !map.isEmpty() && j < 100; j++)
{
    Object obj = map.poll();
    System.out.println(obj.toString());
}

// Write out 100K elements
map.clear();

for (int i=0; i < 100_000; i++)
{
    CmdPut cmd = new CmdPut(null, 199+i, (char)('a'+(i%26)));
    map.add(cmd);
}

db.commit();
db.close();
```

If I remove  closeOnJvmShutdown, I get a slightly different, but similar exception.

JDK 7, Win8 64 bit, built with top of git tree as of now.

**Comment by RoundSparrow** [comment]
I have the same problem.  In my case - 

1) app starts up 
2) tries to read corrupted database. Detects that it is corrupted, tries to close database.
3) delete database files
4) create new database
4) fails with "Writer thread failed"

Is there some way to completely reset the state of the engine?

**Comment by javalama** [comment]
problem is still there
