### ISSUE TITLE
Excessive locking

### ISSUE THREAD

**Issue by jankotek** [jankotek/mapdb#287]
I'm testing out MapDB and finding some unusual slowness and *a lot* of locking. 

Here's a thread dump of the MapDB parts:

```
"main" prio=6 tid=0x00000000022be800 nid=0x2ae0 runnable [0x00000000025cf000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.pread0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.pread(FileDispatcherImpl.java:66)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:220)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:699)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:681)
	- locked <0x00000007df173370> (a java.lang.Object)
	at org.mapdb.Volume$FileChannelVol.readFully(Volume.java:776)
	at org.mapdb.Volume$FileChannelVol.getLong(Volume.java:804)
	at org.mapdb.StoreWAL.reloadIndexFile(StoreWAL.java:99)
	at org.mapdb.StoreWAL.commit(StoreWAL.java:621)
	at org.mapdb.EngineWrapper.commit(EngineWrapper.java:92)
	at org.mapdb.DB.commit(DB.java:1497)
	- locked <0x00000007df026888> (a org.mapdb.DB)
	at Testing.main(Testing.scala)
```
   Locked ownable synchronizers:
```
	- <0x00000007df026978> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	- <0x00000007df162e18> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1630a0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163118> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163190> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163208> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163280> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1632f8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163370> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1633e8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163460> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1634d8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163550> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1635c8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163640> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1636b8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163730> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1637a8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163820> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163898> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163910> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163988> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163a00> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163a78> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163af0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163b68> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163be0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163c58> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163cd0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163d48> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163dc0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163e38> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163eb0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163f28> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df163fa0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164018> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164090> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164108> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164180> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1641f8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164270> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1642e8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164360> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1643d8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164450> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1644c8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164540> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1645b8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164630> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1646a8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164720> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164798> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164810> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164888> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164900> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164978> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1649f0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164a68> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164ae0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164b58> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164bd0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164c48> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164cc0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164d38> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164db0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164e28> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164ea0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164f18> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df164f90> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165008> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165080> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1650f8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165170> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1651e8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165260> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1652d8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165350> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1653c8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165440> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1654b8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165530> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1655a8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165620> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165698> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165710> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165788> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165800> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165878> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1658f0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165968> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1659e0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165a58> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165ad0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165b48> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165bc0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165c38> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165cb0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165d28> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165da0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165e18> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165e90> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165f08> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165f80> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df165ff8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df166070> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1660e8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df166160> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1661d8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df166250> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1662c8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df166340> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1663b8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df166430> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1664a8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df166520> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df166598> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df166610> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df166688> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df166700> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df166778> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1667f0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df166868> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1668e0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df172978> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df1729f0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df172a68> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df172ae0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df172b58> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df172bd0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	- <0x00000007df172c48> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
```

**Comment by jankotek** [comment]
MapDB 2.0 was rewritten to use less locks. Cache and AsyncWriter are merged under Store locks. Default concurrency value is lower. We even have single threaded mode.
