### ISSUE TITLE
ArrayIndexOutOfBoundsException on createHashMap().makeOrGet[A,B]() in cycle

### ISSUE THREAD

**Issue by kushti** [jankotek/mapdb#309]
Code to reproduce(Scala, MapDB 0.9.11):

```
val memMappedFile = DBMaker.newFileDB(new File("/tmp/griddb"))
                                  .mmapFileEnable()
                                  .closeOnJvmShutdown()
                                  .make()

for(i <- 1 to 10000){
    memMappedFile.createHashMap(s"coll$i").makeOrGet[String,Int]()
}
```

gives:

java.lang.ArrayIndexOutOfBoundsException
    at java.lang.System.arraycopy(Native Method)
    at org.mapdb.BTreeKeySerializer.leadingValuePackRead(BTreeKeySerializer.java:231)
    at org.mapdb.BTreeKeySerializer$3.deserialize(BTreeKeySerializer.java:195)
    at org.mapdb.BTreeMap$NodeSerializer.deserialize(BTreeMap.java:467)
    at org.mapdb.BTreeMap$NodeSerializer.deserialize(BTreeMap.java:288)
    at org.mapdb.Store.deserialize(Store.java:274)
    at org.mapdb.StoreWAL.get2(StoreWAL.java:361)
    at org.mapdb.StoreWAL.get(StoreWAL.java:336)
    at org.mapdb.Caches$HashTable.get(Caches.java:230)
    at org.mapdb.EngineWrapper.get(EngineWrapper.java:60)
    at org.mapdb.BTreeMap.get(BTreeMap.java:603)
    at org.mapdb.BTreeMap.get(BTreeMap.java:590)
    at org.mapdb.DB.catGet(DB.java:100)
    at org.mapdb.DB$HTreeMapMaker.makeOrGet(DB.java:222)

**Comment by shabanovd** [comment]
@jankotek by trunk you mean 1.x one or 2.x one? I start getting this on 1.0.8.

```
java.lang.ArrayIndexOutOfBoundsException
    at org.mapdb.BTreeKeySerializer.leadingValuePackRead(BTreeKeySerializer.java:230)
    at mneme.db.mapdb.serializers.BytesSerializer.deserialize(BytesSerializer.java:54)
    at org.mapdb.BTreeMap$NodeSerializer.deserialize(BTreeMap.java:465)
    at org.mapdb.BTreeMap$NodeSerializer.deserialize(BTreeMap.java:288)
    at org.mapdb.Store.deserialize(Store.java:297)
    at org.mapdb.StoreDirect.get2(StoreDirect.java:486)
    at org.mapdb.StoreWAL.get2(StoreWAL.java:336)
    at org.mapdb.StoreWAL.get(StoreWAL.java:320)
    at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
    at org.mapdb.AsyncWriteEngine.get(AsyncWriteEngine.java:333)
    at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
    at org.mapdb.Caches$LRU.get(Caches.java:84)
    at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
    at org.mapdb.BTreeMap.get(BTreeMap.java:602)
    at org.mapdb.BTreeMap.get(BTreeMap.java:589)
```

**Comment by jankotek** [comment]
@shabanovd 2.0
