### ISSUE TITLE
crash mapDB when application using mapDB stopped forcing

### ISSUE THREAD

**Issue by roopannava** [jankotek/mapdb#311]
I use mapDB in my android application. When I stopped the application via Application Manager -> Force Stop and start it again I get the following error : 

java.io.IOError: java.io.EOFException
        at org.mapdb.Volume$FileChannelVol.getLong(Volume.java:806)
        at org.mapdb.StoreDirect.get2(StoreDirect.java:440)
        at org.mapdb.StoreWAL.get2(StoreWAL.java:352)
        at org.mapdb.StoreWAL.get(StoreWAL.java:336)
        at org.mapdb.Caches$HashTable.get(Caches.java:230)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:60)
        at org.mapdb.TxEngine.get(TxEngine.java:176)
        at org.mapdb.TxEngine$Tx.getNoLock(TxEngine.java:411)
        at org.mapdb.TxEngine$Tx.get(TxEngine.java:386)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:60)
        at org.mapdb.TxEngine.get(TxEngine.java:176)
        at org.mapdb.BTreeMap.<init>(BTreeMap.java:542)
        at org.mapdb.DB.getTreeMap(DB.java:796)

Any idea?

**Comment by jankotek** [comment]
I thing problem could be related to Thread Interrupt problem. Use RandomAccessFile instead.
