### ISSUE TITLE
Bug with Serialization

### ISSUE THREAD

**Issue by csilvav** [jankotek/mapdb#378]
take a look a this error. but everything was fine... it's strange.
```
Exception occurred in target VM: Could not instantiate class 
java.lang.RuntimeException: Could not instantiate class
	at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:483)
	at org.mapdb.SerializerBase.deserialize3(SerializerBase.java:1216)
	at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1132)
	at org.mapdb.SerializerBase.deserialize(SerializerBase.java:867)
	at org.mapdb.SerializerPojo.deserialize(SerializerPojo.java:701)
	at org.mapdb.HTreeMap$2.deserialize(HTreeMap.java:135)
	at org.mapdb.HTreeMap$2.deserialize(HTreeMap.java:121)
	at org.mapdb.Store.deserialize(Store.java:297)
	at org.mapdb.StoreDirect.get2(StoreDirect.java:475)
	at org.mapdb.StoreWAL.get2(StoreWAL.java:368)
	at org.mapdb.StoreWAL.get(StoreWAL.java:352)
	at org.mapdb.Caches$HashTable.get(Caches.java:245)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.HTreeMap.recursiveDirCount(HTreeMap.java:350)
	at org.mapdb.HTreeMap.recursiveDirCount(HTreeMap.java:345)
	at org.mapdb.HTreeMap.sizeLong(HTreeMap.java:325)
	at org.mapdb.HTreeMap.size(HTreeMap.java:305)
	at com.highdeveloper.helperj.Test.main(Test.java:20)
Caused by: java.lang.IndexOutOfBoundsException: Index: 11, Size: 11
	at java.util.ArrayList.rangeCheck(ArrayList.java:638)
	at java.util.ArrayList.get(ArrayList.java:414)
	at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:476)
	... 17 more
```

**Comment by bwzhang2011** [comment]
@jankotek, how about such issue going on ? I'm caring about issues from HTreeMap and please make sure that 2.0 snapshot solved most of the problem and we're looking forward to stable version released soon.

**Comment by TomiViitala** [comment]
Hi, I have a problem in Android 5.0 device with BTreeMap. I am using custom key class for the map. Everything works fine, but if I do some gets (enough of them) on the DP, close application and start it again I get ClassNotFoundException for the custom key class that I am using. ClassNotFoundException is thrown in SerializerPojo.classForName function. After crash, I can again start application succesfully. Same thing repeat if I do some gets (enough) and close application again. I am using 1.0.7 version. Could this be a problem in MapDB? Could 2.0 aplha 1 fix this issue?

**Comment by jankotek** [comment]
@TomiViitala 
There were some troubles with serialization on android. 
Your custom serializer is serialized and stored as part of BTreeMap definition. 

I would recommend to implement 'Externalizable' interface on your serializer. That 
uses different mechanism and could work-around the problem.

2.0 should fix most issues. Most importantly serializers do not have to be 
serializable themselfs. However that part is not finished yet, so right now it will 
probably have the same problem.

**Comment by YmlMark** [comment]
I think this may be the same problem. I've added a zero arg constructor. So far so good.


04-24 15:04:09.493    2379-2379/com.stubhub.music.android W/ActivityThread﹕ ClassLoader.loadClass: The class loader returned by Thread.getContextClassLoader() may fail for processes that host multiple applications. You should explicitly specify a context class loader. For example: Thread.setContextClassLoader(getClass().getClassLoader());
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ java.lang.RuntimeException: Unable to start activity ComponentInfo{com.stubhub.music.android/com.stubhub.music.android.ui.activities.NotificationsActivity}: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.stubhub.music.android.model.entities.StubHubNotification$EventNotification$Kind
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2334)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at android.app.ActivityThread.access$900(ActivityThread.java:169)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at android.os.Looper.loop(Looper.java:146)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5487)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.stubhub.music.android.model.entities.StubHubNotification$EventNotification$Kind
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at org.mapdb.SerializerPojo.classForName(SerializerPojo.java:100)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at org.mapdb.SerializerPojo$FieldInfo.<init>(SerializerPojo.java:204)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at org.mapdb.SerializerPojo$FieldInfo.<init>(SerializerPojo.java:233)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at org.mapdb.SerializerPojo.makeClassInfo(SerializerPojo.java:249)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at org.mapdb.DB.commit(DB.java:1735)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.stubhub.music.android.model.cache.impl.NotificationCache.put(NotificationCache.java:133)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.stubhub.music.android.model.cache.impl.NotificationCache.loadTestNotifications(NotificationCache.java:57)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.stubhub.music.android.model.cache.impl.NotificationCache.<init>(NotificationCache.java:44)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.stubhub.music.android.module.impl.ApplicationModule.provideNotificationCache(ApplicationModule.java:125)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.stubhub.music.android.module.impl.ApplicationModule$$ModuleAdapter$ProvideNotificationCacheProvidesAdapter.get(ApplicationModule$$ModuleAdapter.java:335)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.stubhub.music.android.module.impl.ApplicationModule$$ModuleAdapter$ProvideNotificationCacheProvidesAdapter.get(ApplicationModule$$ModuleAdapter.java:319)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at dagger.internal.Linker$SingletonBinding.get(Linker.java:364)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.stubhub.music.android.module.impl.NotificationsModule$$ModuleAdapter$ProvideInteractorProvidesAdapter.get(NotificationsModule$$ModuleAdapter.java:111)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.stubhub.music.android.module.impl.NotificationsModule$$ModuleAdapter$ProvideInteractorProvidesAdapter.get(NotificationsModule$$ModuleAdapter.java:75)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at dagger.internal.Linker$SingletonBinding.get(Linker.java:364)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.stubhub.music.android.module.impl.NotificationsModule$$ModuleAdapter$ProvidePresenterProvidesAdapter.get(NotificationsModule$$ModuleAdapter.java:191)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.stubhub.music.android.module.impl.NotificationsModule$$ModuleAdapter$ProvidePresenterProvidesAdapter.get(NotificationsModule$$ModuleAdapter.java:152)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at dagger.internal.Linker$SingletonBinding.get(Linker.java:364)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.stubhub.music.android.ui.activities.NotificationsActivity$$InjectAdapter.injectMembers(NotificationsActivity$$InjectAdapter.java:70)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.stubhub.music.android.ui.activities.NotificationsActivity$$InjectAdapter.injectMembers(NotificationsActivity$$InjectAdapter.java:23)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at dagger.ObjectGraph$DaggerObjectGraph.inject(ObjectGraph.java:281)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.stubhub.music.android.ui.activities.AbsActivity.inject(AbsActivity.java:75)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.stubhub.music.android.ui.activities.AbsActivity.onCreate(AbsActivity.java:40)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at com.stubhub.music.android.ui.activities.NotificationsActivity.onCreate(NotificationsActivity.java:77)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at android.app.Activity.performCreate(Activity.java:5451)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ ... 11 more
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ Caused by: java.lang.ClassNotFoundException: com.stubhub.music.android.model.entities.StubHubNotification$EventNotification$Kind
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at java.lang.Class.classForName(Native Method)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at java.lang.Class.forName(Class.java:251)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at org.mapdb.SerializerPojo.classForName(SerializerPojo.java:98)
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ ... 37 more
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ Caused by: java.lang.NoClassDefFoundError: com/stubhub/music/android/model/entities/StubHubNotification$EventNotification$Kind
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ ... 40 more
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ Caused by: java.lang.ClassNotFoundException: Didn't find class "com.stubhub.music.android.model.entities.StubHubNotification$EventNotification$Kind" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
04-24 15:04:10.554    2379-2379/com.stubhub.music.android W/System.err﹕ at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
04-24 15:04:10.564    2379-2379/com.stubhub.music.android W/System.err﹕ at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
04-24 15:04:10.564    2379-2379/com.stubhub.music.android W/System.err﹕ at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
04-24 15:04:10.564    2379-2379/com.stubhub.music.android W/System.err﹕ ... 40 more
04-24 15:04:10.564    2379-2379/com.stubhub.music.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.stubhub.music.android, PID: 2379
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.stubhub.music.android/com.stubhub.music.android.ui.activities.NotificationsActivity}: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.stubhub.music.android.model.entities.StubHubNotification$EventNotification$Kind
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2334)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
            at android.app.ActivityThread.access$900(ActivityThread.java:169)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5487)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.stubhub.music.android.model.entities.StubHubNotification$EventNotification$Kind
            at org.mapdb.SerializerPojo.classForName(SerializerPojo.java:100)
            at org.mapdb.SerializerPojo$FieldInfo.<init>(SerializerPojo.java:204)
            at org.mapdb.SerializerPojo$FieldInfo.<init>(SerializerPojo.java:233)
            at org.mapdb.SerializerPojo.makeClassInfo(SerializerPojo.java:249)
            at org.mapdb.DB.commit(DB.java:1735)
            at com.stubhub.music.android.model.cache.impl.NotificationCache.put(NotificationCache.java:133)
            at com.stubhub.music.android.model.cache.impl.NotificationCache.loadTestNotifications(NotificationCache.java:57)
            at com.stubhub.music.android.model.cache.impl.NotificationCache.<init>(NotificationCache.java:44)
            at com.stubhub.music.android.module.impl.ApplicationModule.provideNotificationCache(ApplicationModule.java:125)
            at com.stubhub.music.android.module.impl.ApplicationModule$$ModuleAdapter$ProvideNotificationCacheProvidesAdapter.get(ApplicationModule$$ModuleAdapter.java:335)
            at com.stubhub.music.android.module.impl.ApplicationModule$$ModuleAdapter$ProvideNotificationCacheProvidesAdapter.get(ApplicationModule$$ModuleAdapter.java:319)
            at dagger.internal.Linker$SingletonBinding.get(Linker.java:364)
            at com.stubhub.music.android.module.impl.NotificationsModule$$ModuleAdapter$ProvideInteractorProvidesAdapter.get(NotificationsModule$$ModuleAdapter.java:111)
            at com.stubhub.music.android.module.impl.NotificationsModule$$ModuleAdapter$ProvideInteractorProvidesAdapter.get(NotificationsModule$$ModuleAdapter.java:75)
            at dagger.internal.Linker$SingletonBinding.get(Linker.java:364)
            at com.stubhub.music.android.module.impl.NotificationsModule$$ModuleAdapter$ProvidePresenterProvidesAdapter.get(NotificationsModule$$ModuleAdapter.java:191)
            at com.stubhub.music.android.module.impl.NotificationsModule$$ModuleAdapter$ProvidePresenterProvidesAdapter.get(NotificationsModule$$ModuleAdapter.java:152)
            at dagger.internal.Linker$SingletonBinding.get(Linker.java:364)
            at com.stubhub.music.android.ui.activities.NotificationsActivity$$InjectAdapter.injectMembers(NotificationsActivity$$InjectAdapter.java:70)
            at com.stubhub.music.android.ui.activities.NotificationsActivity$$InjectAdapter.injectMembers(NotificationsActivity$$InjectAdapter.java:23)
            at dagger.ObjectGraph$DaggerObjectGraph.inject(ObjectGraph.java:281)
            at com.stubhub.music.android.ui.activities.AbsActivity.inject(AbsActivity.java:75)
            at com.stubhub.music.android.ui.activities.AbsActivity.onCreate(AbsActivity.java:40)
            at com.stubhub.music.android.ui.activities.NotificationsActivity.onCreate(NotificationsActivity.java:77)
            at android.app.Activity.performCreate(Activity.java:5451)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
            at android.app.ActivityThread.access$900(ActivityThread.java:169)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5487)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by:
