### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by demon450** [jankotek/MapDB#388]
DBMaker.newFileDB(new File(".", "cache")).closeOnJvmShutdown().mmapFileEnable().commitFileSyncDisable().make();

Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.mapdb.Volume$ByteBufferVol.getInt(Volume.java:339)
	at org.mapdb.StoreDirect.checkHeaders(StoreDirect.java:242)
	at org.mapdb.StoreWAL.checkHeaders(StoreWAL.java:115)
	at org.mapdb.StoreDirect.<init>(StoreDirect.java:207)
	at org.mapdb.StoreWAL.<init>(StoreWAL.java:74)
	at org.mapdb.DBMaker.extendStoreWAL(DBMaker.java:928)
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:722)
	at org.mapdb.DBMaker.make(DBMaker.java:665)
	at com.db.eps.cache.MapDbBackedCacheManagerImpl.<init>(MapDbBackedCacheManagerImpl.java:42)

**Comment by jankotek** [comment]
I believe this is fixed now
