### ISSUE TITLE
After rollback AssertionError: data were read beyond record size, check your serializer is thrown

### ISSUE THREAD

**Issue by kobikis** [jankotek/mapdb#405]
Hi,

I'm trying to use mapdb with transaction but i'm getting this error after rollback and get, if i'm performing commit everything is ok.

Exception in thread "main" java.lang.AssertionError: data were read beyond record size, check your serializer
	at org.mapdb.Store.deserialize(Store.java:301)
	at org.mapdb.StoreDirect.get2(StoreDirect.java:475)
	at org.mapdb.StoreWAL.get2(StoreWAL.java:368)
	at org.mapdb.StoreWAL.get(StoreWAL.java:352)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.HTreeMap.getInner(HTreeMap.java:440)
	at org.mapdb.HTreeMap.get(HTreeMap.java:397)

public static void main(String[] args) {
        DB db;
        ConcurrentMap<Serializable, Serializable> _data ;
        db = DBMaker
                .newMemoryDirectDB()
                .cacheDisable()
                .make();
        _data = db.createHashMap("aaa")
                .make();
        Data data = new Data();
        data.setId(0);
        _data.put(0, SerializationUtils.serialize(data));
        db.rollback();
        Serializable d = _data.get(0);
    }

Thanks,
Kobi

**Comment by nddipiazza** [comment]
can you add some details why this was closed? just experienced it and we were wondering what to do

**Comment by jankotek** [comment]
@nddipiazza 2.0 is no longer supported. Sorry
