### ISSUE TITLE
CCE: : org.mapdb.BTreeKeySerializer$CharArrayKeys cannot be cast to org.mapdb.BTreeKeySerializer$ByteArrayKeys

### ISSUE THREAD

**Issue by jandam** [jankotek/MapDB#410]
MapDB v. 2.0
            BTreeMap<String, long[]> searchMapN = dbSearchIndex.createTreeMap(name)
                    .keySerializer(BTreeKeySerializer.STRING)
                    .valueSerializer(Serializer.LONG_ARRAY)
                    .counterEnable()
                    .makeOrGet();

java.lang.ClassCastException: org.mapdb.BTreeKeySerializer$CharArrayKeys cannot be cast to org.mapdb.BTreeKeySerializer$ByteArrayKeys
	at org.mapdb.BTreeKeySerializer$5.serialize(BTreeKeySerializer.java:1620)
	at org.mapdb.BTreeKeySerializer$5.serialize(BTreeKeySerializer.java:1617)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:610)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:550)
	at org.mapdb.Store.serialize(Store.java:164)
	at org.mapdb.StoreDirect.update(StoreDirect.java:521)
	at org.mapdb.Caches$HashTable.update(Caches.java:338)
	at org.mapdb.EngineWrapper.update(EngineWrapper.java:65)
	at org.mapdb.BTreeMap.put2(BTreeMap.java:969)
	at org.mapdb.BTreeMap.put(BTreeMap.java:853)

**Comment by jandam** [comment]
I have patch for CCE and AIOOBE from this issue:
CCE: fixed by introducing new method StringArrayKeys::getOffset()
AIOOBE: bug in ByteArrayKeys::compare(int, String). String letters must be compared as characters. Not as bytes. Problem is when comparing non Unicode string with unicode.
Example: "CR".compareTo(..., "ČR"). Correct result is "CR" < "ČR". But "Č" is casted to byte as number 12, ASCII code for "C" is 67. So casting to bytes leads to wrong result.

```
Index: ../../Misc/MapDB-master/src/main/java/org/mapdb/BTreeKeySerializer.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- ../../Misc/MapDB-master/src/main/java/org/mapdb/BTreeKeySerializer.java	(revision 3270)
+++ ../../Misc/MapDB-master/src/main/java/org/mapdb/BTreeKeySerializer.java	(revision )
@@ -941,6 +941,8 @@
 
         int length();
 
+        int[] getOffset();
+
         BTreeKeySerializer.StringArrayKeys deleteKey(int pos);
 
         BTreeKeySerializer.StringArrayKeys copyOfRange(int from, int to);
@@ -1027,6 +1029,11 @@
         }
 
         @Override
+        public int[] getOffset() {
+            return offset;
+        }
+
+        @Override
         public ByteArrayKeys deleteKey(int pos) {
             int split = pos==0? 0: offset[pos-1];
             int next = offset[pos];
@@ -1141,8 +1148,8 @@
             int len = Math.min(len1,strLen);
              //$DELAY$
             while(len-- != 0){
-                byte b1 = array[start1++];
-                byte b2 = (byte) string.charAt(start2++);
+                char b1 = (char) (array[start1++] & 0xff);
+                char b2 = string.charAt(start2++);
                 if(b1!=b2){
                     return b1-b2;
                 }
@@ -1269,6 +1276,11 @@
         }
 
         @Override
+        public int[] getOffset() {
+            return offset;
+        }
+
+        @Override
         public CharArrayKeys deleteKey(int pos) {
             int split = pos==0? 0: offset[pos-1];
             int next = offset[pos];
@@ -1622,21 +1634,20 @@
 
     public static final BTreeKeySerializer<String,StringArrayKeys> STRING = new BTreeKeySerializer<String,StringArrayKeys>() {
         @Override
-        public void serialize(DataOutput out, StringArrayKeys keys2) throws IOException {
-            ByteArrayKeys keys = (ByteArrayKeys) keys2;
+        public void serialize(DataOutput out, StringArrayKeys keys) throws IOException {
             int offset = 0;
             //write sizes
-            for(int o:keys.offset){
+            for(int o: keys.getOffset()){
                 DataIO.packInt(out,(o-offset));
                 offset = o;
             }
             //$DELAY$
-            int unicode = keys2.hasUnicodeChars()?1:0;
+            int unicode = keys.hasUnicodeChars()?1:0;
             
             //find and write common prefix
             int prefixLen = keys.commonPrefixLen();
             DataIO.packInt(out,(prefixLen<<1) | unicode);
-            keys2.serialize(out, prefixLen);
+            keys.serialize(out, prefixLen);
         }
 
         @Override
\ No newline at end of file
```
