### ISSUE TITLE
Pump: IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by jandam** [jankotek/mapdb#421]
Exception occurs when source iterator for Pump is empty. (MapDB master)

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.mapdb.Pump.buildTreeMap(Pump.java:500)
	at org.mapdb.DB.createTreeMap(DB.java:946)
	at org.mapdb.DB$BTreeMapMaker.make(DB.java:743)
	at org.mapdb.DB$BTreeMapMaker.makeOrGet(DB.java:750)

        BTreeMap<Long, Record> spatialMapN = db.createTreeMap("record")
                .keySerializer(BTreeKeySerializer.LONG)
                .valueSerializer(new RecordSerializer())
                .nodeSize(120)
                .pumpSource(Collections.emptyIterator())         // <<-- HERE 
                .pumpIgnoreDuplicates()
                .counterEnable()
                .makeOrGet();

**Comment by jankotek** [comment]
This is fixed
