### ISSUE TITLE
Thrown exception while running replay_good_log() in StoreWALTest test file

### ISSUE THREAD

**Issue by mfayoub** [jankotek/MapDB#422]
Hi,

I have this test fault while running StoreWALTest at line 103
java.io.IOError: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
	at org.mapdb.Volume.handleIOException(Volume.java:946)
	at org.mapdb.Volume$MappedFileVol.truncate(Volume.java:557)
	at org.mapdb.StoreWAL.logReset(StoreWAL.java:166)
	at org.mapdb.StoreWAL.replayLogFile(StoreWAL.java:790)
	at org.mapdb.StoreWALTest$1.replayLogFile(StoreWALTest.java:88)
	at org.mapdb.StoreWAL.commit(StoreWAL.java:545)
	at org.mapdb.StoreWALTest.replay_good_log(StoreWALTest.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.io.IOException: The requested operation cannot be performed on a file with a user-mapped section open
	at sun.nio.ch.FileDispatcherImpl.truncate0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.truncate(Unknown Source)
	at sun.nio.ch.FileChannelImpl.truncate(Unknown Source)
	at org.mapdb.Volume$MappedFileVol.truncate(Volume.java:555)
	... 29 more

**Comment by jankotek** [comment]
StoreWAL was rewritten
