### ISSUE TITLE
off-heap cache does not evict entries fast enough; results in "OutOfMemoryError: Direct buffer memory"

### ISSUE THREAD

**Issue by dlg99** [jankotek/mapdb#425]
from https://groups.google.com/forum/#!topic/mapdb/qDbylSwpSU4

I am trying to make use of MapDB as off-heap LRU cache, unfortunately all my attempts to make it expire records as expected have failed so far.
I see that occasionally records are being removed (cache size drops) but eventually OutOfMemory is thrown.
I tried setting cache expiration time (expireAftreWrite), changing expiremaxSize setting etc., eventually test still ends up with the same exception. Please see the code below.

Am I misconfiguring something?

Stack:
```
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:306)
	at org.mapdb.Volume$MemoryVol.makeNewBuffer(Volume.java:578)
	at org.mapdb.Volume$ByteBufferVol.tryAvailable(Volume.java:290)
	at org.mapdb.Volume.ensureAvailable(Volume.java:49)
	at org.mapdb.StoreDirect.freePhysTake(StoreDirect.java:1095)
```

My jvm parameters:
```
-Xmx3g -Xms3g -XX:NewSize=1g -XX:MaxNewSize=1g -XX:MaxDirectMemorySize=6g -XX:PermSize=64m -XX:MaxPermSize=64m  -XX:+UseParNewGC -XX:MaxTenuringThreshold=2 -XX:ParallelGCThreads=10 -XX:+CMSConcurrentMTEnabled -XX:ParallelCMSThreads=6 -XX:ConcGCThreads=6 -XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark -XX:SurvivorRatio=48 -XX:+UnlockDiagnosticVMOptions -XX:ParGCCardsPerStrideChunk=32768 -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled  -XX:CMSInitiatingOccupancyFraction=70 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -XX:-OmitStackTraceInFastThrow  
```
JDK 7, code compiled as jdk 6 compatible.
MapDB 1.0.6.

Code (simplified to the level of simple byte array):

```
import org.junit.Test;
import org.mapdb.DBMaker;
import org.mapdb.Serializer;

import java.security.SecureRandom;
import java.util.Map;
import java.util.Random;

import static org.junit.Assert.assertEquals;

public class MapDbTestUtil {

  private static final Random random = new SecureRandom();

  private static final int NUM_TESTS = Integer.MAX_VALUE;
  private static final int BYTES_SIZE = 250 * 1024 - 32; // 250K minus key size

  @Test
  public void testMapDbCache() throws Exception {

    final int sizeGB = 1;
    Map<String, byte[]> cache = DBMaker
        .newMemoryDirectDB() // off-heap, in memory
        .transactionDisable()
        .cacheLRUEnable()
        .cacheDisable() //internal instance cache, too bad for GC
        //.compressionEnable()
        //.asyncWriteFlushDelay(50)
        //.asyncWriteQueueSize(25)
        //.sizeLimit(2.0d*sizeGB)
        .make()
        .createHashMap("mapdb-unit-test-expiration")
        .counterEnable() //for tests
        .expireMaxSize(10000)
        .expireStoreSize(sizeGB) // can be slightly more than this
        .keySerializer(Serializer.STRING_ASCII) // ids are ascii, save some space
        .valueSerializer(Serializer.BYTE_ARRAY)
        .make();

    byte[] ce = generateByteArray(BYTES_SIZE);
    long count = 0;
    long start = System.currentTimeMillis();
    for (int i = 0; i < NUM_TESTS; i++) {
      String netId = buildId(i);

      cache.put(netId, ce);

      count++;

      if(count == 10000) {
        long delta = System.currentTimeMillis() - start;
        System.out.println("");
        System.out.println(String.format("%d inserts in %d ms (%f/sec)", count, delta, (double)count * 1000/delta));
        validateOne(cache, random.nextInt(i));
        //Thread.sleep(100);
        start = System.currentTimeMillis();
        count = 0;
      } //else {
      //  cache.get("missing");
      //}
    }

  }

  private byte[] generateByteArray(int sz) {
    byte[] res = new byte[sz];
    random.nextBytes(res);
    return res;
  }

  private void validateOne(Map<String, byte[]> cache, int i) {
    System.out.println("");
    String netId = buildId(i);
    byte[] cached = cache.get(netId);

    if (cached == null) {
      System.out.print("cache MISS; cache size: " + cache.size());
      return;
    }
    System.out.print("cache HIT;  cache size: " + cache.size());

    assertEquals(BYTES_SIZE, cached.length);
  }

  private String buildId(int i) {
    String id = "3dd8b8f5ed5567e11936cc572bcc572b" + Integer.toString(i) ;
    id = id.substring(id.length() - 32, id.length());
    return id;
  }

}
```

**Comment by jankotek** [comment]
This part was recently rewritten, so it might be improved. Going to investigate before release.

**Comment by bwzhang2011** [comment]
@jankotek ,how does this going on ? is such confirmed or fixed ?

**Comment by jankotek** [comment]
Expirators now can run in multiple threads on background. That could fix issue, need to run some benchmarks to check.

**Comment by bwzhang2011** [comment]
@jankotek, any update with such issue ? how about the eviction speed, as you pointed out, more benchmarks should be provided.

**Comment by jankotek** [comment]
No update yet

**Comment by bwzhang2011** [comment]
@dlg99, any update with such issue ?

**Comment by jankotek** [comment]
There was a problem with compaction, that is now fixed.
