### ISSUE TITLE
File not found exception (Too many open files)

### ISSUE THREAD

**Issue by souragar** [jankotek/MapDB#428]
Basically I run the following loop to reproduce the issue  .I am using ubuntu 12.04

while(true){
Map<Object, Row> table = DBMaker.newTempTreeMap();
Sys.out(counter++);
}
After the counter reaches 2000 I get the following exception

java.io.IOError: java.io.FileNotFoundException: /tmp/mapdb-temp2437107633928880554db.p (Too many open files)
	at org.mapdb.Volume$FileChannelVol.<init>(Volume.java:672)
	at org.mapdb.Volume.volumeForFile(Volume.java:176)
	at org.mapdb.Volume$1.createPhysVolume(Volume.java:208)
	at org.mapdb.StoreDirect.<init>(StoreDirect.java:203)
	at org.mapdb.DBMaker.extendStoreDirect(DBMaker.java:918)
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:722)
	at org.mapdb.DBMaker.make(DBMaker.java:665)
	at org.mapdb.DBMaker.newTempTreeMap(DBMaker.java:172)

**Comment by jankotek** [comment]
Not really MapDB problem.

Increase maximal number of file handlers in your 
system. 

Or make sure that Map is closed before you open 
new one.

Jan
