### ISSUE TITLE
NotSerializableException only on Linux when transactionDisable == true

### ISSUE THREAD

**Issue by razem-io** [jankotek/MapDB#440]
Hi,

since 3 days our workstations are running on Linux. Sadly mapdb wasn't working as expected. The following error came up:

```
Exception in thread "main" java.io.IOError: java.io.NotSerializableException: org.mapdb.Fun$ArrayComparator
	at org.mapdb.Store.serialize(Store.java:238)
	at org.mapdb.Store.update(Store.java:141)
	at org.mapdb.BTreeMap.put2(BTreeMap.java:1103)
	at org.mapdb.BTreeMap.put(BTreeMap.java:987)
	at org.mapdb.DB.catPut(DB.java:162)
	at org.mapdb.DB.createTreeSet(DB.java:1105)
	at org.mapdb.DB$BTreeSetMaker.make(DB.java:865)
	at org.mapdb.DB$BTreeSetMaker.makeOrGet(DB.java:872)
	at com.example.Testing.<init>(Testing.java:39)
	at com.example.Testing.main(Testing.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.io.NotSerializableException: org.mapdb.Fun$ArrayComparator
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.mapdb.SerializerPojo.serializeUnknownObject(SerializerPojo.java:388)
	at org.mapdb.SerializerBase.serialize(SerializerBase.java:971)
	at org.mapdb.SerializerBase.serialize(SerializerBase.java:917)
	at org.mapdb.Serializer.valueArraySerialize(Serializer.java:1369)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:732)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:668)
	at org.mapdb.Store.serialize(Store.java:163)
```

It's pretty easy to reproduce on Linux. MacOSX and Windows are running the following fine:
```
        DB db = DBMaker.newTempFileDB().make();

        NavigableSet<Object[]> set1 = db.createTreeSet("set1")
                .serializer(BTreeKeySerializer.ARRAY2)
                .makeOrGet();

        System.out.println("1. try Works!");

        db = DBMaker.newTempFileDB().transactionDisable().make();

        NavigableSet<Object[]> set2 = db.createTreeSet("set2")
                .serializer(BTreeKeySerializer.ARRAY2)
                .makeOrGet();

        System.out.println("2. try Works!");
```

Using 2.0.0-SNAPSHOT and Xubuntu 64-bit 14.04 LTS

**Comment by razem-io** [comment]
I just noticed doing the following also does not work to:

```
       DB db = DBMaker.newTempFileDB().make();

        NavigableSet<Object[]> set1 = db.createTreeSet("set1")
                .serializer(BTreeKeySerializer.ARRAY2)
                .makeOrGet();

        db.commit();

        System.out.println("1. try Works!");
```

**Comment by jankotek** [comment]
Thanks for nice and detailed bug report. It was typo from past refactoring, I need more automated tests for newly added classes. 

It is fixed, I deployed fix into snapshot repo

**Comment by jankotek** [comment]
Relevant commit is 3fc4549849a4d2f6ec623cb4a73f3e93fc584439, wrong commit message

**Comment by razem-io** [comment]
Awesome! Thank you for the quick fix! Will test as soon as possible.
