### ISSUE TITLE
Race condition in RECID reusal

### ISSUE THREAD

**Issue by jankotek** [jankotek/mapdb#445]
Recid gets reused and it can throw an exception. Perhaps disable recid reusal on MapDB 1.0
```
java.lang.ClassCastException: org.mapdb.HTreeMap$LinkedNode cannot be cast to org.mapdb.HTreeMap$ExpireLinkNode
	at org.mapdb.HTreeMap.expireLinkBump(HTreeMap.java:1369)
	at org.mapdb.HTreeMap.putInner(HTreeMap.java:526)
	at org.mapdb.HTreeMap.put(HTreeMap.java:480)
	at org.mapdb.HTreeMap$KeySet.add(HTreeMap.java:818)
	at org.mapdb.Issue418Test.test_set(Issue418Test.java:53)
```

**Comment by jankotek** [comment]
Similar error
```
java.lang.ClassCastException: org.mapdb.BTreeMap$DirNode cannot be cast to org.mapdb.HTreeMap$ExpireLinkNode
	org.mapdb.HTreeMap.expireLinkBump(HTreeMap.java:1378)
	org.mapdb.HTreeMap$HashIterator.findNextLinkedNode(HTreeMap.java:1053)
	org.mapdb.HTreeMap$HashIterator.<init>(HTreeMap.java:970)
	org.mapdb.HTreeMap$EntryIterator.<init>(HTreeMap.java:1132)
	org.mapdb.HTreeMap$5.iterator(HTreeMap.java:916)
	org.codehaus.jackson.map.ser.std.MapSerializer.serializeFields(MapSerializer.java:232)
	org.codehaus.jackson.map.ser.std.MapSerializer.serialize(MapSerializer.java:186)
	org.codehaus.jackson.map.ser.std.MapSerializer.serialize(MapSerializer.java:23)
	org.codehaus.jackson.map.ser.StdSerializerProvider._serializeValue(StdSerializerProvider.java:659)
	org.codehaus.jackson.map.ser.StdSerializerProvider.serializeValue(StdSerializerProvider.java:271)
	org.codehaus.jackson.map.ObjectWriter.writeValue(ObjectWriter.java:325)
	org.codehaus.jackson.jaxrs.JacksonJsonProvider.writeTo(JacksonJsonProvider.java:556)
	com.sun.jersey.json.impl.provider.entity.JacksonProviderProxy.writeTo(JacksonProviderProxy.java:160)
	com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
```

**Comment by jankotek** [comment]
Fixed in 24e5b37729ff4a3674e18263e219c721cf8e1089, there was race condition in Hashtable cache

**Comment by jankotek** [comment]
I've been testing MapDB and came across the following problem today. I had a process was using a MapDB Queue<String> for caching SQL writes. Everything was working fine, the process had been running for over 12 hours when all of a sudden, the queue.offer() operation started failing constantly with the following exception:
```
java.lang.ClassCastException: org.mapdb.Queues$SimpleQueue$Node cannot be cast to java.lang.Long
 at org.mapdb.Atomic$Long.get(Atomic.java:315)
 at org.mapdb.Queues$Queue.add(Queues.java:393)
 at org.mapdb.Queues$SimpleQueue.offer(Queues.java:211)
```
Any ideas here? This is a showstopper, we can't adopt MapDB in production with this sort of issue happening. Thanks.

**Comment by jankotek** [comment]
Another exception from `Issue418Test`

    java.lang.NullPointerException
	at org.mapdb.HTreeMap.expirePurgeSegment(HTreeMap.java:1591)
	at org.mapdb.HTreeMap.expirePurge(HTreeMap.java:1576)
	at org.mapdb.HTreeMap$ExpireRunnable.run(HTreeMap.java:1528)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yaitskov** [comment]
I am using 1.0.7 and faced with such a problem. How is it possible that the bug is still alive!

```
 java.lang.ClassCastException: org.mapdb.HTreeMap$LinkedNode cannot be cast to [[J
     [java] 2015-06-23 19:50:24,832 ERROR  stderr -- 	at org.mapdb.HTreeMap.putInner(HTreeMap.java:500)
     [java] 2015-06-23 19:50:24,832 ERROR  stderr -- 	at org.mapdb.HTreeMap.put(HTreeMap.java:488)
```

**Comment by jankotek** [comment]
Can not fix without major redesign. Disable cache or use 2.0 branch.
