### ISSUE TITLE
BTreeMap close() can cause ArrayOutOfBounds exception - 1.0.6

### ISSUE THREAD

**Issue by drcrallen** [jankotek/mapdb#447]
A map maker is defined as follows

```java
private static final DBMaker DB_MAKER = DBMaker
      .newMemoryDirectDB()
      .transactionDisable()
      .asyncWriteEnable()
      .cacheLRUEnable()
      .closeOnJvmShutdown()
      .deleteFilesAfterClose()
      .cacheSize(16384);
```

With a BTreeMap defined as follows (from https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/segment/incremental/OffheapIncrementalIndex.java )
```java
    this.facts = factsDb.createTreeMap(factDbTableName)
                        .keySerializer(timeAndDimsSerializer)
                        .comparator(timeAndDimsSerializer.getComparator())
                        .valueSerializer(Serializer.INTEGER)
                        .make();
```

Whenever `facts.clear()` is called, somehow the iterator/remover can end up in a scenario where the `findChildren` call in `remove2` returns 0, which causes `Object oldVal =   A.vals()[pos-1];` to fail.

This is overall very hard to randomly reproduce, but for the particular cases encountered can be reproduced with certainty, and circumvented by flushing the engine cache (`facts.getEngine().clearCache()`) prior to calling the `clear()` method on the BTreeMap.

Stack trace below

```
java.lang.ArrayIndexOutOfBoundsException: -1
at org.mapdb.BTreeMap.remove2(BTreeMap.java:976) ~[mapdb-1.0.6.jar:?]
at org.mapdb.BTreeMap.remove(BTreeMap.java:949) ~[mapdb-1.0.6.jar:?]
at org.mapdb.BTreeMap$BTreeIterator.remove(BTreeMap.java:908) ~[mapdb-1.0.6.jar:?]
at org.mapdb.BTreeMap.clear(BTreeMap.java:1028) ~[mapdb-1.0.6.jar:?]
at org.mapdb.DB.delete(DB.java:1470) ~[mapdb-1.0.6.jar:?]
at io.druid.segment.incremental.OffheapIncrementalIndex.close(OffheapIncrementalIndex.java:309) ~[druid-processing-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
at com.metamx.common.guava.ResourceClosingYielder.close(ResourceClosingYielder.java:41) ~[java-util-0.26.11.jar:?]
at com.metamx.common.guava.CloseQuietly.close(CloseQuietly.java:36) ~[java-util-0.26.11.jar:?]
at com.metamx.common.guava.YieldingSequenceBase.accumulate(YieldingSequenceBase.java:24) ~[java-util-0.26.11.jar:?]
at io.druid.query.groupby.GroupByQueryQueryToolChest.makeIncrementalIndex(GroupByQueryQueryToolChest.java:209) ~[druid-processing-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
at io.druid.query.groupby.GroupByQueryQueryToolChest.mergeGroupByResults(GroupByQueryQueryToolChest.java:175) ~[druid-processing-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
at io.druid.query.groupby.GroupByQueryQueryToolChest.access$100(GroupByQueryQueryToolChest.java:71) ~[druid-processing-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
at io.druid.query.groupby.GroupByQueryQueryToolChest$3.run(GroupByQueryQueryToolChest.java:121) ~[druid-processing-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
at io.druid.query.FinalizeResultsQueryRunner.run(FinalizeResultsQueryRunner.java:104) ~[druid-processing-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
```

**Comment by jankotek** [comment]
I checked your source code. `TimeAndDims` class is composed of multiple arrays. Are you sure that it is immutable? If some array element would be modified, it would affect comparator and cause very same symptoms you described.

**Comment by jankotek** [comment]
Not enough information to reproduce
