### ISSUE TITLE
NPE if setting a key serializer without a comparator

### ISSUE THREAD

**Issue by cubefriendly** [jankotek/mapdb#450]
Hi,
If I set manually the key serializer I want to use, It seems that I have to set a comparator as well.

If I forget to do it, I get a NPE. I think it would make sens to have some kind of default comparator for each key serializer or at least a helper function to set the comprators because I cannot find the one for INT_ARRAY for example.

keep up the good work!

**Comment by cubefriendly** [comment]
I little more info.
I am currently trying to migrate my code from MapDB 1.0.x to 2.0.x

I just tried and on MapDB 1, it says explicitly, when you use ZERO_OR_POSITIVE_LONG serializer that you cannot set a comparator as it needs its own. So I guess there is such a mechanism to have a pair of serializer and comparator together.

**Comment by jankotek** [comment]
Would you have a stack trace? and code which creates map?

**Comment by cubefriendly** [comment]
Sorry for the late response.

Here is the code
File file = new File(name + ".cube");
        this.db = DBMaker.newFileDB(file).cacheDisable().lockThreadUnsafeEnable().mmapFileEnableIfSupported().transactionDisable().make();
        this.data = db.<int[],String>createTreeMap("data").keySerializer(Serializer.INT_ARRAY).valueSerializer(Serializer.STRING_ASCII).make();

here is the stacktrace

java.lang.NullPointerException
	at org.mapdb.BTreeKeySerializer$BasicKeySerializer.<init>(BTreeKeySerializer.java:165)
	at org.mapdb.DB$BTreeMapMaker.keySerializer(DB.java:738)
	at org.cubefriendly.engine.cube.CubeDataBuilder.name(CubeDataBuilder.java:20)
	at org.cubefriendly.engine.cube.CubeEngineTest.should_be_created_by_setting_the_name_and_data(CubeEngineTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by cubefriendly** [comment]
Ok I found the issue. When HAVE to set a comparator before you set the serializer. If you do it in the right order it works 
I know in my example I have no comparator but I added it first after the serializer and I still had the issue. When you set it before it works

**Comment by jankotek** [comment]
Thanks for doing all the investigation. Seems like simple fix in DB will do.

**Comment by cubefriendly** [comment]
Yes I think so too. Would it be possible to have, like in MapDB1, the COMPARATOR and SERIALIZER coupled with the possibility to override it.

I think you should either:
- Have a default Comparator for each serializer 
- Making the comparator and serializer setting to be set at the same time. For example
withSerializer(SERIALIZER,COMPARATOR) 

I prefer the first solution :)

Happy I could help

**Comment by cubefriendly** [comment]
I checked the status of this issue right now. the API has completely changed and the issue is no more
