### ISSUE TITLE
Cannot use empty pump source

### ISSUE THREAD

**Issue by mattwigway** [jankotek/mapdb#452]
If I try to fill a database using .pumpSource(Iterator<Tuple2<K, V>) and the iterator is empty, I get an IndexOutOfBoundsException. Obviously not a big deal as it doesn't really make sense to use an empty pump source (I discovered this when implementing online backup using pump, and some of my tables were empty; just needed to add a check to skip backing those up).

```
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:532)
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:139)
	at org.mapdb.DataInput2.readUnsignedByte(DataInput2.java:74)
	at org.mapdb.BTreeMap$NodeSerializer.deserialize(BTreeMap.java:416)
	at org.mapdb.BTreeMap$NodeSerializer.deserialize(BTreeMap.java:288)
	at org.mapdb.Store.deserialize(Store.java:297)
	at org.mapdb.StoreDirect.get2(StoreDirect.java:475)
	at org.mapdb.StoreWAL.get2(StoreWAL.java:368)
	at org.mapdb.StoreWAL.get(StoreWAL.java:352)
	at org.mapdb.Caches$HashTable.get(Caches.java:245)
	at org.mapdb.BTreeMap.<init>(BTreeMap.java:541)
	at org.mapdb.DB.createTreeMap(DB.java:862)
	at org.mapdb.DB$BTreeMapMaker.make(DB.java:644)
	at MapDBEmptyPumpSource.main(MapDBEmptyPumpSource.java:30)
```

Test case: https://gist.github.com/mattwigway/a882c7ac360836df939b . This is with MapDB 1.0.6.

**Comment by jankotek** [comment]
It is bug.  Thanks

**Comment by jandam** [comment]
Same problem already reported as #421

**Comment by jankotek** [comment]
Fixed in both branches.
