### ISSUE TITLE
Exception on 1.0.7

### ISSUE THREAD

**Issue by nopper** [jankotek/mapdb#466]
I am using the latest stable version (1.0.7) from maven. I am building a database with:

```
val db = DBMaker.newFileDB(dbFile)
  .transactionDisable()
  .asyncWriteEnable()
  .asyncWriteFlushDelay(100)
  .make()
```

And reopening the archive with the following code:

```
val db = DBMaker.newFileDB(dbFile)
    .transactionDisable()
    .mmapFileEnableIfSupported()
    .readOnly()
    .make()
```

I am just using the database in read only mode and issuing queries on a ConcurrentNavigableMap as follows:

```
val m: ConcurrentNavigableMap[String, Long] = db.getTreeMap("mymap")
m.getOrDefault("some string", 0)
```

Unfortunately after a little bit of querying using multiple threads I got hit by the following error:

```
[error] Exception in thread "Thread-4" java.lang.ArrayIndexOutOfBoundsException: 15
[error]         at org.mapdb.Volume$ByteBufferVol.getLong(Volume.java:372)
[error]         at org.mapdb.StoreDirect.get2(StoreDirect.java:440)
[error]         at org.mapdb.StoreDirect.get(StoreDirect.java:428)
[error]         at org.mapdb.Caches$HashTable.get(Caches.java:246)
[error]         at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
[error]         at org.mapdb.BTreeMap.get(BTreeMap.java:602)
[error]         at org.mapdb.BTreeMap.get(BTreeMap.java:589)
[error]         at java.util.concurrent.ConcurrentMap.getOrDefault(ConcurrentMap.java:80)
```

I am now trying to rebuild the database without the async delay, but it's rather slow. I'll keep you informed.

**Comment by nopper** [comment]
Same error without asyncWriteEnable()

**Comment by jankotek** [comment]
Looks like data corruption. Will have a look.

**Comment by mhuffman-r7** [comment]
We are noticing a similar stack trace (using version 1.0.6) when working with very large indexes. We are experiencing this pretty rarely, but in our production environment.

```
      m_db = DBMaker.newFileDB(new File(m_path.toFile(), DB_NAME))
         .closeOnJvmShutdown()
         .mmapFileEnable()
         .make();
```

```
java.lang.ArrayIndexOutOfBoundsException: 148959648
        at org.mapdb.Volume$ByteBufferVol.getByte(Volume.java:344) ~[mapdb-1.0.6.jar:na]
        at org.mapdb.Volume.getUnsignedShort(Volume.java:91) ~[mapdb-1.0.6.jar:na]
        at org.mapdb.StoreWAL.longStackGetPage(StoreWAL.java:1077) ~[mapdb-1.0.6.jar:na]
        at org.mapdb.StoreWAL.longStackTake(StoreWAL.java:944) ~[mapdb-1.0.6.jar:na]
        at org.mapdb.StoreDirect.freePhysTake(StoreDirect.java:1074) ~[mapdb-1.0.6.jar:na]
        at org.mapdb.StoreDirect.physAllocate(StoreDirect.java:655) ~[mapdb-1.0.6.jar:na]
        at org.mapdb.StoreWAL.put(StoreWAL.java:245) ~[mapdb-1.0.6.jar:na]
        at org.mapdb.Caches$HashTable.put(Caches.java:216) ~[mapdb-1.0.6.jar:na]
        at org.mapdb.EngineWrapper.put(EngineWrapper.java:53) ~[mapdb-1.0.6.jar:na]
        at org.mapdb.HTreeMap.putInner(HTreeMap.java:581) ~[mapdb-1.0.6.jar:na]
        at org.mapdb.HTreeMap.put(HTreeMap.java:480) ~[mapdb-1.0.6.jar:na]
        at org.mapdb.HTreeMap$KeySet.add(HTreeMap.java:818) ~[mapdb-1.0.6.jar:na]
        ...
```

Could this be related?

**Comment by edudar** [comment]
`version`: `1.0.7`

Map file was built with `async` then without it. Fails at the exactly same key in both cases.

```
java.lang.ArrayIndexOutOfBoundsException: 3
	at org.mapdb.Volume$ByteBufferVol.getLong(Volume.java:372)
	at org.mapdb.StoreDirect.get2(StoreDirect.java:440)
	at org.mapdb.StoreDirect.get(StoreDirect.java:428)
	at org.mapdb.Caches$HashTable.get(Caches.java:246)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.HTreeMap.getInner(HTreeMap.java:448)
	at org.mapdb.HTreeMap.get(HTreeMap.java:397)
```

**Comment by edudar** [comment]
I've tried Java 7 instead of 8 and TreeMap instead of Hash but still get various exceptions on read.

This is `Java 7` and `TreeMap`:
```
Exception in thread "main" java.io.IOError: java.io.IOException: Channel not open for writing - cannot extend file to required size
	at org.mapdb.Volume$MappedFileVol.makeNewBuffer(Volume.java:540)
	at org.mapdb.Volume$ByteBufferVol.tryAvailable(Volume.java:327)
	at org.mapdb.Volume.ensureAvailable(Volume.java:49)
	at org.mapdb.StoreDirect.createStructure(StoreDirect.java:264)
	at org.mapdb.StoreDirect.<init>(StoreDirect.java:205)
	at org.mapdb.DBMaker.extendStoreDirect(DBMaker.java:918)
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:722)
	at org.mapdb.DBMaker.make(DBMaker.java:665)
Caused by: java.io.IOException: Channel not open for writing - cannot extend file to required size
	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:851)
	at org.mapdb.Volume$MappedFileVol.makeNewBuffer(Volume.java:534)
	... 14 more
```

Simply changing `TreeMap` to `HashMap` leads to different exception:
```
java.lang.ArrayIndexOutOfBoundsException: 21
	at org.mapdb.Volume$ByteBufferVol.getDataInput(Volume.java:387)
	at org.mapdb.Volume$ByteBufferVol.getDataInput(Volume.java:269)
	at org.mapdb.StoreDirect.get2(StoreDirect.java:448)
	at org.mapdb.StoreDirect.get(StoreDirect.java:428)
	at org.mapdb.Caches$HashTable.get(Caches.java:246)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.HTreeMap.getInner(HTreeMap.java:448)
	at org.mapdb.HTreeMap.get(HTreeMap.java:397)
```

I can provide source and data files if you need one to reproduce this issue.

**Comment by edudar** [comment]
Found out that `.mmapFileEnableIfSupported()` should be invoked for both writer and reader DBs. Otherwise various exceptions fall out randomly.

**Comment by jankotek** [comment]
Can not replicate. Please use 2.0 branch
