### ISSUE TITLE
Pump - AssertionError: keys are not sorted: [2, 2, 65, 137]

### ISSUE THREAD

**Issue by jandam** [jankotek/MapDB#484]
For certain input Pump throws AssertionError. This issue depends on Pump source size and nodeSize (nLoad = 0.75 * nodeSize). Exception is thrown when DirNode is split on last insert.

Test attached:
```java
        try (DB dbWayParam = DBMaker
                .newTempFileDB()
                .mmapFileEnableIfSupported()
                .transactionDisable()
                .closeOnJvmShutdown()
                .deleteFilesAfterClose()
                .make()) {

            List<Long> list = new ArrayList<>(208);
            for (long key = 208; key >= 1L; key--) {
                list.add(key);
            }
            Iterator<Long> source = list.iterator();
            BTreeMap<Long, Long> map = dbWayParam.createTreeMap("pump-test")
                    .keySerializer(BTreeKeySerializer.LONG)
                    .valueSerializer(Serializer.LONG)
                    .nodeSize(12)
                    .counterEnable()
                    .pumpSource(source, Fun.<Long>extractNoTransform())
                    .pumpIgnoreDuplicates()
                    .makeOrGet();
        }
```
Stacktrace:
```
Exception in thread "main" java.lang.AssertionError: keys are not sorted: [2, 2, 65, 137]
	at org.mapdb.BTreeMap$BNode.checkStructure(BTreeMap.java:387)
	at org.mapdb.BTreeMap$DirNode.checkStructure(BTreeMap.java:462)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:736)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:702)
	at org.mapdb.Store.serialize(Store.java:189)
	at org.mapdb.StoreDirect.put(StoreDirect.java:430)
	at org.mapdb.DBMaker$CloseOnJVMShutdown.put(DBMaker.java:1310)
	at org.mapdb.Pump.buildTreeMap(Pump.java:590)
	at org.mapdb.DB.createTreeMap(DB.java:1174)
	at org.mapdb.DB$BTreeMapMaker.make(DB.java:931)
	at org.mapdb.DB$BTreeMapMaker.makeOrGet(DB.java:938)
```

Suggested fix/workaround:
  Check whether source has next value before node split.
```
            //check node sizes and split them if needed
            if (source.hasNext()) {
                for (int i = 0; i < dirKeys.size(); i++) {
            ...
```

**Comment by jankotek** [comment]
Nice catch

**Comment by jankotek** [comment]
I just checked fix. Problem was datapump, had to rewrite it. Thanks for test case, very helpfull.
