### ISSUE TITLE
Fail to close DB after call DB.compact():

### ISSUE THREAD

**Issue by bobwenx** [jankotek/MapDB#486]
i am using MapDB(2.x-SNAPSHOT) on Mac with java 8:
```java
  public static void main(String[] args) throws Exception{
        Path test = JavaFile.createTempFile("test");
        DB db = DBMaker.newFileDB(test.toFile())
               .closeOnJvmShutdown()
               .mmapFileEnableIfSupported()
               .make();
        db.compact();
        db.close();
    }
```
After i call  db.compact(), then call close(). MapDB throws Exception:
```
Exception in thread "main" java.lang.NullPointerException
	at org.mapdb.Volume$MappedFileVol.close(Volume.java:639)
	at org.mapdb.StoreWAL.close(StoreWAL.java:1220)
	at org.mapdb.DBMaker$CloseOnJVMShutdown.close(DBMaker.java:1335)
	at org.mapdb.DB.close(DB.java:1925)
```

However, it did't happen in 1.0.7.

**Comment by bobwenx** [comment]
ok. it didn't happen in 2.0-alpha1 either, i will using 2.0-alpha1(it have metrics log support)
