### ISSUE TITLE
Internal field failure in SerializerPojo?

### ISSUE THREAD

**Issue by RoundSparrow** [jankotek/mapdb#495]
My app has no field named "loadFactor" - I assume it's some internal MapDB error?

.RuntimeException: Could not set field value: loadFactor - class java.util.LinkedHashMap
            at org.mapdb.SerializerPojo$FieldInfo.<init>(SerializerPojo.java:212)

It isn't happening on all uses of my Map - not sure what the factor is at this point.  Looking for suggestions on how to track it down.

**Comment by RoundSparrow** [comment]
Ok, so it seems that if I call commit it is what is trigger this crash:

Could not set field value: loadFactor - class java.util.LinkedHashMap
            at org.mapdb.SerializerPojo$FieldInfo.<init>(SerializerPojo.java:212)
            at org.mapdb.SerializerPojo$FieldInfo.<init>(SerializerPojo.java:233)
            at org.mapdb.SerializerPojo.makeClassInfo(SerializerPojo.java:249)
            at org.mapdb.DB.commit(DB.java:1999)

**Comment by jankotek** [comment]
What version of JVM are you using? Also could you post bit more code example? 

Stack trace is interesting. It seems that `LinkedHashMap` is serialized in some strange way. Its serialization should be handled by different class.

**Comment by tadas-subonis** [comment]
I am seeing the same on Android 5.0, JDK 1.8 . Looks like LinkedHashMap is created by GSON.

**Comment by tadas-subonis** [comment]
The exception itself:
```
 Caused by: java.lang.RuntimeException: Could not set field value: loadFactor - class java.util.LinkedHashMap
            at org.mapdb.SerializerPojo$FieldInfo.<init>(SerializerPojo.java:208)
            at org.mapdb.SerializerPojo$FieldInfo.<init>(SerializerPojo.java:229)
            at org.mapdb.SerializerPojo.registerClass(SerializerPojo.java:252)
            at org.mapdb.SerializerPojo$ObjectOutputStream2.writeClassDescriptor(SerializerPojo.java:600)
            at java.io.ObjectOutputStream.writeClassDesc(ObjectOutputStream.java:790)
            at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1369)
            at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
            at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1612)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
            at org.mapdb.SerializerPojo.serializeUnknownObject(SerializerPojo.java:401)
            at org.mapdb.SerializerBase.serialize2(SerializerBase.java:531)
            at org.mapdb.SerializerBase.serialize(SerializerBase.java:150)
            at org.mapdb.SerializerPojo.serializeUnknownObject(SerializerPojo.java:426)
            at org.mapdb.SerializerBase.serialize2(SerializerBase.java:531)
            at org.mapdb.SerializerBase.serialize(SerializerBase.java:150)
            at org.mapdb.SerializerPojo.serializeUnknownObject(SerializerPojo.java:426)
            at org.mapdb.SerializerBase.serialize2(SerializerBase.java:531)
            at org.mapdb.SerializerBase.serialize(SerializerBase.java:150)
            at org.mapdb.SerializerPojo.serializeUnknownObject(SerializerPojo.java:426)
            at org.mapdb.SerializerBase.serialize2(SerializerBase.java:531)
            at org.mapdb.SerializerBase.serialize(SerializerBase.java:
```

**Comment by RoundSparrow** [comment]
I haven't come back without follow-up as it hasn't happened in a reproducible way for me. It is surely not every time I run the same code.

Overall, my experience with Android + MapDB is that threading is a big factor. Things that were working with pure Java Map objects (loaded in bulk at app startup) start to have all kinds of odd failures and problems - including sometimes the app just plain exiting without exception.  Especially under high loads with 4 cores running intensive operations.

More questions than answers or details at this point.  I've been reworking my thread / database paths to be more isolated and analyzable.

**Comment by jankotek** [comment]
This class:

>EDIT2: It seems that the class is actually com.google.gson.internal.LinkedTreeMap 

Has following method:

```
  /**
   * If somebody is unlucky enough to have to serialize one of these, serialize
   * it as a LinkedHashMap so that they won't need Gson on the other side to
   * deserialize it. Using serialization defeats our DoS defence, so most apps
   * shouldn't use it.
   */
  private Object writeReplace() throws ObjectStreamException {
    return new LinkedHashMap<K, V>(this);
  }
```
It seems MapDB does not handle this case well. Will investigate

**Comment by YmlMark** [comment]
Is it a valid workaround to specify a concrete List implementation such as ArrayList, instead of List, so that MapDB won't use LinkedHashMap?

**Comment by jankotek** [comment]
The problem is with GSON. Workaround is to replace it with different class, such as ``new LinkedHashMap(map)``

**Comment by jankotek** [comment]
I am trying to replicate this issue, but no lack so far. It would be helpful to have some test case.

**Comment by YmlMark** [comment]
As others have noted, this problem rears its ugly head at seemingly random times. Sorry to report that I am now starting to see it  for objects that contain no Lists of any kind.

**Comment by jankotek** [comment]
I added `writeReplace()` method to blacklist, see 958321c1b55116d090251ef2c25f9a98b049b2ff

**Comment by jankotek** [comment]
I now understand wha

**Comment by jankotek** [comment]
I now understand what is going on. There is field which expect certain class (`JSONMap` etc), but this class is transformed to other data type (`LinkedHashMap` etc) after deserialization. And deserialization of this will will fail with ClassCastException, since the field has other type and can not be set. 

Will try some workaround

**Comment by jankotek** [comment]
I just added test case to replicate that MapDB serialization is behaving the same way as Java Serialization (it fails with `ClassCastException`). So after some thinking this is 'feature' and I can not really fix it.

**Comment by YmlMark** [comment]
In my case, it could easily be what you describe, as I am persisting objects created by Retrofit/GSON. Seems like the workaround is to customize GSON deserialization and convert Json arrays into some other kind of Map. Aside from a flood of messages, I have yet to identify any issue with the data actually persisted.
