### ISSUE TITLE
Keys are not sorted stack trace using a master clone of MapDB 2.0

### ISSUE THREAD

**Issue by sselvia** [jankotek/MapDB#499]
Cloned the latest MapDB 2.0 and in order to test some some, I'm getting the following error when using the code below.  My real use case is reading a CSV file using the the iterator, for this example I'm not and using the counter <= 16737175 for my end of file;

DB db = DBMaker.fileDB(Paths.get("D:", "MapDB", file.getName() + "_MapDB20.dbf").toFile())
               .mmapFileEnable()
               .transactionDisable()
               .closeOnJvmShutdown()
               .compressionEnable()
               .asyncWriteEnable()
               .executorEnable()
               .fileChannelEnable()
               .make();

Iterator<Fun.Pair<Integer, String>> source = new Iterator<Fun.Pair<Integer, String>>()
{
  int counter = 0;
  int mapIndex = Integer.MAX_VALUE;

  @Override public boolean hasNext()
  {
    mapIndex--;
    return counter <= 16737175;
  }

  @Override
  public Fun.Pair<Integer, String> next()
  {
    if ((counter % 100000) == 0)
    {
       System.out.println("Counter = " + counter + " | MapIndex = " + mapIndex);
    }

    counter++;
    
    return new Fun.Pair<>(mapIndex, "foobar");          
  }

  @Override public void remove()
  {
  }
};

BTreeMap<Integer, String> csvContentMap = db.treeMapCreate("csvContentMap")
                                            .keySerializer(BTreeKeySerializer.INTEGER)
                                            .valueSerializer(Serializer.STRING)
                                            .pumpSource(source)
                                            .counterEnable()
                                            .make();
                                            
db.commit();
db.close();

Exception in thread "main" java.lang.AssertionError: keys are not sorted: [2129351716, 2129351716, 2129352288, 2129352886, 2129353484, 2129354082, 2129354680, 2129355278]
	at org.mapdb.BTreeMap$BNode.checkStructure(BTreeMap.java:387)
	at org.mapdb.BTreeMap$DirNode.checkStructure(BTreeMap.java:462)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:736)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:702)
	at org.mapdb.Store.serialize(Store.java:189)
	at org.mapdb.StoreCached.flushWriteCacheSegment(StoreCached.java:349)
	at org.mapdb.StoreCached.flushWriteCache(StoreCached.java:325)
	at org.mapdb.StoreCached.flush(StoreCached.java:280)
	at org.mapdb.StoreDirect.commit(StoreDirect.java:762)
	at org.mapdb.Engine$CloseOnJVMShutdown.commit(Engine.java:477)
	at org.mapdb.DB.commit(DB.java:2160)
	at testmapdb.mapdb20.TestMapDB20.loadMapDBTableCSVFields(TestMapDB20.java:369)
	at testmapdb.mapdb20.TestMapDB20.runTests(TestMapDB20.java:65)
	at testmapdb.mapdb20.TestMapDB20.main(TestMapDB20.java:388)

**Comment by jandam** [comment]
Already reported as #484

**Comment by jankotek** [comment]
I just checked fix. Problem was datapump, had to rewrite it. Thanks for test case, very helpfull.
