### ISSUE TITLE
RandomAccessFileVol Error

### ISSUE THREAD

**Issue by whybe** [jankotek/mapdb#504]
After `VolumeIOError` exception occured, It spit `IndexOutOfBoundsException` out over again.

I guess, it exceeded maximum count of **WAL** file, *15*. Am I right?

How can I avoid this kind of situation?

I use https://github.com/jankotek/MapDB/commit/be0f1a1503e471a47674503f6d8837d99dfea582

>
[36704] ERROR [Thread-3]: MessageSubscriber.lambda$storeMessage$85(44) :: IO failed
org.mapdb.DBException$VolumeIOError: IO failed
	at org.mapdb.Volume$RandomAccessFileVol.<init>(Volume.java:1791)
	at org.mapdb.Volume$RandomAccessFileVol$1.makeVolume(Volume.java:1780)
	at org.mapdb.Volume$VolumeFactory.makeVolume(Volume.java:52)
	at org.mapdb.StoreWAL.walStartNextFile(StoreWAL.java:254)
	at org.mapdb.StoreWAL.commit(StoreWAL.java:829)
	at org.mapdb.TxEngine.superCommit(TxEngine.java:326)
	at org.mapdb.TxEngine$Tx.commit(TxEngine.java:549)
	at org.mapdb.DB.commit(DB.java:2169)
	at org.mapdb.TxMaker.execute(TxMaker.java:103)
	at com.uaps.glr.rx.store.MessageStoreService.lambda$null$22(MessageStoreService.java:50)
	at com.uaps.glr.rx.store.MessageStoreService.access$lambda$16(MessageStoreService.java)
	at com.uaps.glr.rx.store.MessageStoreService$$Lambda$29.call(Unknown Source)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7495)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:76)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:34)
	at rx.Observable.unsafeSubscribe(Observable.java:7495)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.handleNewSource(OperatorMerge.java:215)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:185)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:120)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:43)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:32)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.subscribe(Observable.java:7585)
	at rx.Observable.subscribe(Observable.java:7416)
	at com.uaps.glr.rx.subscriber.MessageSubscriber.storeMessage(MessageSubscriber.java:39)
	at com.uaps.glr.rx.subscriber.MessageSubscriber.<init>(MessageSubscriber.java:32)
	at com.uaps.glr.SocketConnection.DataReceive(SocketConnection.java:246)
	at com.uaps.glr.SocketConnectionMgr.run(SocketConnectionMgr.java:108)
Caused by: java.io.FileNotFoundException: mapdb/store.mapdb.wal.15 (Too many open files in system)
	at java.io.RandomAccessFile.open(Native Method)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:216)
	at org.mapdb.Volume$RandomAccessFileVol.<init>(Volume.java:1789)
	... 33 more

repeatedly spit it out
 
> 
[36709] ERROR [Thread-3]: MessageSubscriber.lambda$storeMessage$85(44) :: Index: 15, Size: 15
java.lang.IndexOutOfBoundsException: Index: 15, Size: 15
	at java.util.ArrayList.RangeCheck(ArrayList.java:547)
	at java.util.ArrayList.get(ArrayList.java:322)
	at java.util.Collections$SynchronizedList.get(Collections.java:1820)
	at org.mapdb.StoreWAL.loadLongStackPage(StoreWAL.java:472)
	at org.mapdb.StoreCached.longStackPut(StoreCached.java:140)
	at org.mapdb.StoreDirect.freeDataPut(StoreDirect.java:540)
	at org.mapdb.StoreDirect.freeDataPut(StoreDirect.java:517)
	at org.mapdb.StoreDirect.update2(StoreDirect.java:298)
	at org.mapdb.StoreCached.flushWriteCacheSegment(StoreCached.java:350)
	at org.mapdb.StoreWAL.commit(StoreWAL.java:753)
	at org.mapdb.TxEngine.superCommit(TxEngine.java:326)
	at org.mapdb.TxEngine$Tx.commit(TxEngine.java:549)
	at org.mapdb.DB.commit(DB.java:2169)
	at org.mapdb.TxMaker.execute(TxMaker.java:103)
	at com.uaps.glr.rx.store.MessageStoreService.lambda$null$22(MessageStoreService.java:50)
	at com.uaps.glr.rx.store.MessageStoreService.access$lambda$16(MessageStoreService.java)
	at com.uaps.glr.rx.store.MessageStoreService$$Lambda$29.call(Unknown Source)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7495)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:76)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:34)
	at rx.Observable.unsafeSubscribe(Observable.java:7495)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.handleNewSource(OperatorMerge.java:215)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:185)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:120)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:43)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:32)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.subscribe(Observable.java:7585)
	at rx.Observable.subscribe(Observable.java:7416)
	at com.uaps.glr.rx.subscriber.MessageSubscriber.storeMessage(MessageSubscriber.java:39)
	at com.uaps.glr.rx.subscriber.MessageSubscriber.<init>(MessageSubscriber.java:32)
	at com.uaps.glr.SocketConnection.DataReceive(SocketConnection.java:246)
	at com.uaps.glr.SocketConnectionMgr.run(SocketConnectionMgr.java:108)
```

**Comment by jankotek** [comment]
```
Caused by: java.io.FileNotFoundException: mapdb/store.mapdb.wal.15 (Too many open files in system)
```
This is caused if too many files are opened. It should be a few thousands, not 15. Similar issue was fixed yesterday, so make sure you have latest snapshot. 

Will investigate/

**Comment by whybe** [comment]
When I access mapdb file, I have created new TxMaker instance and commited using TxMaker.execute(). Maybe, mutiple TxMaker instance against an mapdb file makes troubles.
I changed to use single TxMaker instance.
I think that I used TxMaker in a wrong manner, am I right?

**Comment by whybe** [comment]
Related to this issues, I have created socket at the other place.

**Comment by jankotek** [comment]
There was disk handle leak in MapDB. That was fixed recently. Please try with newest version.

**Comment by cthumuluru** [comment]
@jankotek I'm having the same issue with MapDB version 3.0.3. Can you tell me which version has the fix?

**Comment by cthumuluru** [comment]
@jankotek adding stack trace for your reference. 
`Caused by: java.io.FileNotFoundException: <file_name> (Too many open files)
at java.io.RandomAccessFile.open0(Native Method)
at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
at org.mapdb.volume.RandomAccessFileVol.<init>(RandomAccessFileVol.java:51)`
