### ISSUE TITLE
Huge_Insert Example Breaks with File Read Iterator

### ISSUE THREAD

**Issue by alex-ayala** [jankotek/mapdb#508]
The Huge_Load.java in the examples package works well when creating sample random data, but throws a NullPointerException when implementing the source Iterator to read from a file instead (using version 1.0.7 but also replicated in 1.0.6). See example below:

```java
public class Huge_Insert {
	private static final String TEST_FILE_LOC = "<PATH TO 5500 RECORD FILE>";
    
	public static void main(String[] args) throws IOException {

        /** max number of elements to import */
        final long max = (int) 1e6;

        /**
         * Open database in temporary directory
         */
        File dbFile = File.createTempFile("mapdb","temp");
        DB db = DBMaker
                .newFileDB(dbFile)
                /** disabling Write Ahead Log makes import much faster */
                .transactionDisable()
                .make();


        long time = System.currentTimeMillis();

         // WORKS
        /**
         * Source of data which randomly generates strings.
         * In real world this would return data from file.
         */
        /*Iterator<String> source = new Iterator<String>() {

            long counter = 0;

            @Override public boolean hasNext() {
                return counter<max;
            }

            @Override
            public String next() {
                counter++;
                return randomString(randInt(60, 100));
            }

            @Override public void remove() {}
        };*/
        
         // DOES NOT WORK
        Iterator<String> source = new Iterator<String>() {
        	String line = "";
            long counter = 0;
            BufferedReader br = new BufferedReader(new FileReader(testFileLoc));
            @Override public boolean hasNext() {
                boolean hasNext = false;
            	try {
					if (counter<max && br.ready()) {
						hasNext = true;
						line = br.readLine();
					} else {
						hasNext = false;
						br.close();
					}
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            	
            	return hasNext;
            }

            @Override
            public String next() {
            	try {
					br.readLine();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
                counter++;
                return randomString(randInt(50, 90));
            }

            @Override public void remove() {}
        };

         // DOES NOT WORK
        //Iterator<String> source = FileUtils.lineIterator(new File(TEST_FILE_LOC), "UTF-8");
        
        /**
         * BTreeMap Data Pump requires data source to be presorted in reverse order (highest to lowest).
         * There is method in Data Pump we can use to sort data. It uses temporarly files and can handle fairly
         * large data sets.
         */
        source = Pump.sort(source,
                true, 100000,
                Collections.reverseOrder(Fun.COMPARATOR), //reverse  order comparator
                db.getDefaultSerializer()
                //null //sort in single threaded mode
                );



        /**
         * Disk space used by serialized keys should be minimised.
         * Keys are sorted, so only difference between consequential keys is stored.
         * This method is called delta-packing and typically saves 60% of disk space.
         */
        BTreeKeySerializer keySerializer = BTreeKeySerializer.STRING;


        /**
         * Translates Map Key into Map Value.
         */
        Fun.Function1<Integer,String> valueExtractor = new Fun.Function1<Integer, String>() {
            @Override public Integer run(String s) {
                return s.hashCode();
            }
        };

        /**
         * Create BTreeMap and fill it with data
         */
        Map<String,Integer> map = db.createTreeMap("map")
                .pumpSource(source,valueExtractor)
                //.pumpPresort(100000) // for presorting data we could also use this method
                .keySerializer(keySerializer)
                .make();


        System.out.println("Finished; total time: "+(System.currentTimeMillis()-time)/1000+"s; there are "+map.size()+" items in map");
        db.close();

    }

    public static String randomString(int size) {
        String chars = "0123456789abcdefghijklmnopqrstuvwxyz !@#$%^&*()_+=-{}[]:\",./<>?|\\";
        StringBuilder b = new StringBuilder(size);
        Random r = new Random();
        for(int i=0;i<size;i++){
            b.append(chars.charAt(r.nextInt(chars.length())));
        }
        return b.toString();
    }

    public static int randInt(int min, int max) {

        // NOTE: Usually this should be a field rather than a method
        // variable so that it is not re-seeded every call.
        Random rand = new Random();

        // nextInt is normally exclusive of the top value,
        // so add 1 to make it inclusive
        int randomNum = rand.nextInt((max - min) + 1) + min;

        return randomNum;
    }
}
```

As you can see, I don't even need to be returning the line read from the file in the next() method. You'll see i'm also using apache-commons io library to create a file iterator for me in case I was doing something incorrectly, but this also causes the same issue. I generated dummy data so if you have issues replicating I can provide the data i'm using.

Below is the stacktrace of the exception:

```java
Exception in thread "main" java.lang.NullPointerException
	at org.mapdb.BTreeKeySerializer$3.serialize(BTreeKeySerializer.java:183)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:385)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:288)
	at org.mapdb.Store.serialize(Store.java:154)
	at org.mapdb.StoreDirect.put(StoreDirect.java:354)
	at org.mapdb.Caches$HashTable.put(Caches.java:216)
	at org.mapdb.Pump.buildTreeMap(Pump.java:470)
	at org.mapdb.DB.createTreeMap(DB.java:849)
	at org.mapdb.DB$BTreeMapMaker.make(DB.java:644)
	at mapdb.examples.Huge_Insert.main(Huge_Insert.java:140)
```

**Comment by jankotek** [comment]
Can not replicate, please use 2.0 branch.
