### ISSUE TITLE
java.io.IOError: java.io.IOException: The parameter is incorrect

### ISSUE THREAD

**Issue by fabiankessler** [jankotek/mapdb#510]
On this line:

        DB db = DBMaker.newFileDB(persistencePath)
                .closeOnJvmShutdown()
                .make();

My disk looks fine. My last program run did not end in an exception. Now my program can't start anymore.
```
Exception in thread "main" java.io.IOError: java.io.IOException: The parameter is incorrect
	at org.mapdb.Volume$FileChannelVol.putData(Volume.java:840)
	at org.mapdb.StoreWAL.replayLogFile(StoreWAL.java:821)
	at org.mapdb.StoreWAL.<init>(StoreWAL.java:84)
	at org.mapdb.DBMaker.extendStoreWAL(DBMaker.java:928)
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:722)
	at org.mapdb.DBMaker.make(DBMaker.java:665)
	at my.MyClass.build(WordsBuilder.java:45)
Caused by: java.io.IOException: The parameter is incorrect
	at sun.nio.ch.FileDispatcherImpl.pwrite0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.pwrite(FileDispatcherImpl.java:80)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:89)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:738)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:720)
	at org.mapdb.Volume$FileChannelVol.writeFully(Volume.java:766)
	at org.mapdb.Volume$FileChannelVol.putData(Volume.java:838)
	... 9 more
```

My (corrupted?) mapdb files for download: https://mega.co.nz/#!ThI11YrR!93DGd1hJaXVyWfoWC06a1G-xMBEfJyNX40r9wvp5Wvo

Is there any way to recover, without losing data?

**Comment by jankotek** [comment]
Write-ahead-log is corrupted for some reason. Remove .t file and try again. There were a few bugs in older versions, make sure you use lattest 1.0.7 version.

**Comment by fabiankessler** [comment]
I was using 1.0.7, sorry for not specifying in the report.

**Comment by jankotek** [comment]
Closing. I can reproduce issue, but see no way to find what was original cause of this error. WAL is corrupted and points to too large offset:

```
Exception in thread "main" java.io.IOError: java.io.IOException: File too large
	at org.mapdb.Volume$FileChannelVol.putData(Volume.java:939)
	at org.mapdb.StoreWAL.replayLogFile(StoreWAL.java:821)
	at org.mapdb.StoreWAL.<init>(StoreWAL.java:84)
	at org.mapdb.DBMaker.extendStoreWAL(DBMaker.java:984)
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:760)
	at org.mapdb.DBMaker.make(DBMaker.java:701)
	at examples._HelloWorld.main(_HelloWorld.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.io.IOException: File too large
	at sun.nio.ch.FileDispatcherImpl.pwrite0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.pwrite(FileDispatcherImpl.java:66)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:89)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:745)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:731)
	at org.mapdb.Volume$FileChannelVol.writeFully(Volume.java:865)
	at org.mapdb.Volume$FileChannelVol.putData(Volume.java:937)
	... 11 more
```
