### ISSUE TITLE
ArrayIndexOutOfBoundsException during HTreeMap.remove

### ISSUE THREAD

**Issue by andsel** [jankotek/mapdb#511]
During an invokation to remove method I got the following stacktrace. I'm using actual master sources but the with version 2.0-alpha2 I don't have this fail. Another strange thing is that debugging the code I don't have the fail, so I suspect is related to some timing in the construction of SerialiazerPojo.
When the bug manifest itself I can see that the ClassInfo[] classes is empty.

-----------------------------------------

Caused by: java.lang.RuntimeException: Could not instantiate class
	at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:526)
	at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1416)
	at org.mapdb.SerializerBase.deserializeHashSet(SerializerBase.java:1678)
	at org.mapdb.SerializerBase.access$600(SerializerBase.java:30)
	at org.mapdb.SerializerBase$49.deserialize(SerializerBase.java:779)
	at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1414)
	at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1402)
	at org.mapdb.HTreeMap$1.deserialize(HTreeMap.java:156)
	at org.mapdb.HTreeMap$1.deserialize(HTreeMap.java:129)
	at org.mapdb.Store.deserialize(Store.java:296)
	at org.mapdb.StoreWAL.get2(StoreWAL.java:600)
	at org.mapdb.Store.get(Store.java:146)
	at org.mapdb.HTreeMap.putInner(HTreeMap.java:893)
	at org.mapdb.HTreeMap.put(HTreeMap.java:849)
	at org.eclipse.moquette.spi.persistence.MapDBPersistentStore.updateSubscriptions(MapDBPersistentStore.java:255)
	at org.eclipse.moquette.spi.impl.subscriptions.SubscriptionsStore.deactivate(SubscriptionsStore.java:180)
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.processConnectionLost(ProtocolProcessor.java:557)
	at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:158)
	at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:57)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	... 3 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:492)
	... 22 more

-----------------------------------------

**Comment by jankotek** [comment]
Storage format was changing a lot until recently. Could you try with last alpha3 version?

**Comment by andsel** [comment]
The index out of bound is solved, but now with alpha3 I got this one


java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:66)
	at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:173)
	at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:62)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:64)
	... 6 more
Caused by: org.mapdb.DBException$VolumeIOError: IO failed
	at org.mapdb.Volume$RandomAccessFileVol.getLong(Volume.java:1904)
	at org.mapdb.Volume$ReadOnly.getLong(Volume.java:1680)
	at org.mapdb.StoreDirect.offsetsGet(StoreDirect.java:371)
	at org.mapdb.StoreDirect.delete2(StoreDirect.java:418)
	at org.mapdb.StoreCached.flushWriteCacheSegment(StoreCached.java:342)
	at org.mapdb.StoreWAL.commit(StoreWAL.java:774)
	at org.mapdb.DB.commit(DB.java:2391)
	at org.eclipse.moquette.spi.persistence.MapDBPersistentStore.cleanInFlight(MapDBPersistentStore.java:194)
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.executePublish(ProtocolProcessor.java:321)
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:300)
	... 11 more
Caused by: java.io.EOFException
	at java.io.RandomAccessFile.readInt(RandomAccessFile.java:786)
	at java.io.RandomAccessFile.readLong(RandomAccessFile.java:819)
	at org.mapdb.Volume$RandomAccessFileVol.getLong(Volume.java:1902)
