### ISSUE TITLE
AssertionError in getAtomicVar

### ISSUE THREAD

**Issue by jrumbinas** [jankotek/mapdb#513]
Calling DB.getAtomicVar() for non existing record will result in exception error (in 1.0.7)
#### Exception
```
java.lang.AssertionError
	at org.mapdb.StoreWAL.put(StoreWAL.java:199)
	at org.mapdb.Caches$HashTable.put(Caches.java:216)
	at org.mapdb.EngineWrapper.put(EngineWrapper.java:53)
	at org.mapdb.DB.createAtomicVar(DB.java:1393)
	at org.mapdb.DB.getAtomicVar(DB.java:1418)
```

#### Cause
```java
    synchronized public <E> Atomic.Var<E> getAtomicVar(String name){
        ...
        if(type==null){
            ...
            return createAtomicVar(name, null, getDefaultSerializer());
        }
        return ret;
    }
```

**Comment by jankotek** [comment]
Store does not allow null values, which is initial value for Atomic.Var. I changed default value to empty string `""`. This is not issue in 2.0, since store handles null values.
