### ISSUE TITLE
java.lang.AssertionError: data were not fully read, check your serializer 

### ISSUE THREAD

**Issue by fabiankessler** [jankotek/mapdb#515]
Exception in thread "main" java.lang.AssertionError: data were not fully read, check your serializer 
	at org.mapdb.Store.deserialize(Store.java:299)
	at org.mapdb.StoreDirect.get2(StoreDirect.java:475)
	at org.mapdb.StoreWAL.get2(StoreWAL.java:336)
	at org.mapdb.StoreWAL.get(StoreWAL.java:320)
	at org.mapdb.Caches$HashTable.get(Caches.java:246)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.BTreeMap$BTreeIterator.advance(BTreeMap.java:924)
	at org.mapdb.BTreeMap$BTreeValueIterator.next(BTreeMap.java:1066)
	at (my code)Words.printStats(Words.java:129)
	at (my code)printStats(SingleTypeWordsData2.java:53)
	at (my code)DiscoveryApp2.<init>(DiscoveryApp2.java:36)
	at (my code)App.<init>(App.java:38)
	at (my code)App.main(App.java:43)

My environment:
Version 1.0.7
Windows 8.1 64bit
SSD Disk

Committing after every change.
No custom serializer, nothing special.

One program run finished successfully.
Next the program cannot start, it aborts with this Error.

The broken db is here: 
https://mega.co.nz/#!WlRGWRjZ!edBjNo83zbyCi66KozO9ngY4pHsST5utcLfIORJ6Y8g

I can re-generate my data, it just takes hours. Because I am committing after every change.
What am I doing wrong, why do I run into corrupted DBs all the time, what can I change?

**Comment by apanasyuk** [comment]
Hi.

Looks like we also have faced with similar problem. Here is our case:

SUSE Linux 11
ReiserFS
MapDB 1.0.7
x64

db = DBMaker.newFileDB(file)
            .cacheDisable()
            .closeOnJvmShutdown()
            .compressionEnable()
            .mmapFileEnableIfSupported()
            .make();

map = db.createHashMap(mapName)
        .expireAfterWrite(7, TimeUnit.DAYS)
        .valueSerializer(new CustomMessageSerializer())
        .counterEnable()
        .makeOrGet();

Application has single thread that updates DB. Transaction commited every 100 inserts. Map has number of secondary indexes. DB queried by multiple reader threads.

Periodically when application stopped by kill -9 DB becomes corrupted. 

After restart writer thread hangs up on first insert into mapdb. I have sampled below  call tree in jProfiler. Suppose its infinity loop inside mapdb caused by unexpected exception during deserialization.

https://dl.dropboxusercontent.com/u/5101819/mapdb.bug.png

Also after restart mapdb expiry thread thread fails with below exceptions.

Most of times:
java.lang.AssertionError: data were not fully read, check your serializer 
        at org.mapdb.Store.deserialize(Store.java:299)
        at org.mapdb.StoreDirect.get2(StoreDirect.java:475)
        at org.mapdb.StoreWAL.get2(StoreWAL.java:336)
        at org.mapdb.StoreWAL.get(StoreWAL.java:320)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
        at org.mapdb.HTreeMap.expirePurgeSegment(HTreeMap.java:1589)
        at org.mapdb.HTreeMap.expirePurge(HTreeMap.java:1576)
        at org.mapdb.HTreeMap$ExpireRunnable.run(HTreeMap.java:1528)
        at java.lang.Thread.run(Thread.java:745)

Observed sometime:
java.io.IOError: java.io.IOException: Zero Header, data corrupted
        at org.mapdb.SerializerBase.deserialize(SerializerBase.java:881)
        at org.mapdb.Fun$Tuple5.<init>(Fun.java:288)
        at org.mapdb.SerializerBase.deserialize3(SerializerBase.java:1203)
        at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1132)
        at org.mapdb.SerializerBase.deserialize(SerializerBase.java:867)
        at org.mapdb.SerializerPojo.deserialize(SerializerPojo.java:701)
        at org.mapdb.HTreeMap$2.deserialize(HTreeMap.java:135)
        at org.mapdb.HTreeMap$2.deserialize(HTreeMap.java:121)
        at org.mapdb.Store.deserialize(Store.java:297)
        at org.mapdb.StoreDirect.get2(StoreDirect.java:475)
        at org.mapdb.StoreWAL.get2(StoreWAL.java:336)
        at org.mapdb.StoreWAL.get(StoreWAL.java:320)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
        at org.mapdb.HTreeMap.expirePurgeSegment(HTreeMap.java:1598)
        at org.mapdb.HTreeMap.expirePurge(HTreeMap.java:1576)
        at org.mapdb.HTreeMap$ExpireRunnable.run(HTreeMap.java:1528)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Zero Header, data corrupted
        ... 17 more

I will be glad to provide further details if required.

**Comment by micw** [comment]
@jankotek Hi, is this fixed? In which version? (changelogs for v1/v2 seems to be offline)
Thank you! Michael.

**Comment by eckig** [comment]
Any update on this? The bug seems to remain until now?
