### ISSUE TITLE
second call to DB.makeOrGet() hangs after first attempt throws Serializer not serializable

### ISSUE THREAD

**Issue by Groostav** [jankotek/mapdb#517]
And the follow up to #345 is that now, if you give MapDB a serializer that results in `DB.makeOrGet()` throwing, if you call it a second time it just hangs. 

The first execption is, as you'd expect:
```
java.io.IOError: java.io.NotSerializableException: com.empowerops.common.Serializer$3
	at org.mapdb.Store.serialize(Store.java:228)
	at org.mapdb.StoreWAL.update(StoreWAL.java:403)
	at org.mapdb.Caches$HashTable.update(Caches.java:269)
	at org.mapdb.EngineWrapper.update(EngineWrapper.java:63)
	at org.mapdb.BTreeMap.put2(BTreeMap.java:746)
	at org.mapdb.BTreeMap.put(BTreeMap.java:643)
	at org.mapdb.DB.catPut(DB.java:112)
	at org.mapdb.DB.createHashMap(DB.java:437)
	at org.mapdb.DB$HTreeMapMaker.make(DB.java:216)
	at org.mapdb.DB$HTreeMapMaker.makeOrGet(DB.java:222)
	at com.empowerops.front_end.persistence.StoreFacade.getTable(StoreFacade.java:51)
	//... our domain
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.NotSerializableException: com.empowerops.common.Serializer$3
	at org.mapdb.SerializerPojo.assertClassSerializable(SerializerPojo.java:323)
	at org.mapdb.SerializerPojo.registerClass(SerializerPojo.java:243)
	at org.mapdb.SerializerPojo.serializeUnknownObject(SerializerPojo.java:392)
	at org.mapdb.SerializerBase.serialize2(SerializerBase.java:531)
	at org.mapdb.SerializerBase.serialize(SerializerBase.java:150)
	at org.mapdb.SerializerPojo.serializeUnknownObject(SerializerPojo.java:426)
	at org.mapdb.SerializerBase.serialize2(SerializerBase.java:531)
	at org.mapdb.SerializerBase.serialize(SerializerBase.java:150)
	at org.mapdb.SerializerPojo.serializeUnknownObject(SerializerPojo.java:426)
	at org.mapdb.SerializerBase.serialize2(SerializerBase.java:531)
	at org.mapdb.SerializerBase.serialize(SerializerBase.java:150)
	at org.mapdb.SerializerBase.serialize(SerializerBase.java:94)
	at org.mapdb.SerializerPojo.serialize(SerializerPojo.java:696)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:397)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:288)
	at org.mapdb.Store.serialize(Store.java:154)
	... 23 more
```

and if that second block gets called a second time, rather than failing again, it _hangs_ here:

```
	park(), in Unsafe
	parkNanos(): 333, LockSupport
	lock():2882, BTreeMap
	put2()686, BTreeMap
	put():643, BTreeMap
        catPut():105, DB
	createHashMap():493, DB
	make():216, DB$HTreeMapMaker
	makeOrGet():222DB$HTreeMapMaker
```

**Comment by jankotek** [comment]
Fixed in 1.0, not problem in 2.0 since we do not require serializers to be serializable
