### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Error while opening store. Make sure you have right password, compression or encryption is well configured

### ISSUE THREAD

**Issue by KIC** [jankotek/mapdb#524]
I use mapDB 1.0.7 and I am pretty sure this is a great thing! But I got stuck very early. I try to load the same mem mapped TreeMap on two different Machines (two different jvm during debug). 

EDIT: I have changed my class and create the map differently like so:

```java
private static final long serialVersionUID = -3158441942676405723L;
    private static final String PATH = "/tmp/";
    private transient DB db = null;
    private transient BTreeMap<K, V> sortedData = null;
    private final String iMapName, partitionId;

    public OffHeapMapDBPartition(String iMapName, String partitionId) {
        this.iMapName = Base64.getEncoder().encodeToString(iMapName.getBytes());
        this.partitionId = partitionId;
    }

    public BTreeMap<K, V> getMap() {
        if (db == null) {
            db = DBMaker.newFileDB(new File(PATH + iMapName + ".mapdb"))
                    //.asyncWriteEnable()
                    .closeOnJvmShutdown()
                    .transactionDisable()
                    .mmapFileEnable()
                    .make();
        }

        if (sortedData != null) {
            return sortedData;
        } else {
            return sortedData = db.getTreeMap(partitionId);
        }
    }
}
```
Now when I getMap on another jvm I face another exception:

```
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Error while opening store. Make sure you have right password, compression or encryption is well configured.
	at com.mindbusters.hazelcast.navigablemap.mapstore.AbstractNavigableMapStore.waitForDone(AbstractNavigableMapStore.java:43)
	at com.mindbusters.hazelcast.navigablemap.DistributedNavigableMap.subMap(DistributedNavigableMap.java:102)
	at com.mindbusters.hazelcast.navigablemap.DistributedNavigableMap.subMap(DistributedNavigableMap.java:64)
	at com.mindbusters.utils.navigablemaptest.TestNavigableTable2.main(TestNavigableTable2.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Error while opening store. Make sure you have right password, compression or encryption is well configured.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.hazelcast.executor.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:189)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:186)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.PoolExecutorThreadFactory$ManagedThread.run(PoolExecutorThreadFactory.java:59)
Caused by: java.lang.IllegalArgumentException: Error while opening store. Make sure you have right password, compression or encryption is well configured.
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:777)
	at org.mapdb.DBMaker.make(DBMaker.java:665)
	at com.mindbusters.hazelcast.navigablemap.partitions.OffHeapMapDBPartition.getMap(OffHeapMapDBPartition.java:32)
	at com.mindbusters.hazelcast.navigablemap.partitions.OffHeapMapDBPartition.clear(OffHeapMapDBPartition.java:96)
	at com.mindbusters.hazelcast.navigablemap.callables.SetPartitionData.call(SetPartitionData.java:44)
	at com.mindbusters.hazelcast.navigablemap.callables.SetPartitionData.call(SetPartitionData.java:16)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.hazelcast.executor.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:187)
	... 5 more
Caused by: java.lang.UnsupportedOperationException
	at org.mapdb.SerializerBase.getEngine(SerializerBase.java:1538)
	at org.mapdb.SerializerBase.deserialize3(SerializerBase.java:1209)
	at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1132)
	at org.mapdb.SerializerBase.deserialize(SerializerBase.java:867)
	at org.mapdb.Store.deserialize(Store.java:297)
	at org.mapdb.StoreDirect.get2(StoreDirect.java:475)
	at org.mapdb.StoreDirect.get(StoreDirect.java:428)
	at org.mapdb.Caches$HashTable.get(Caches.java:246)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:771)
	... 12 more
```

Earlier: The problem was that I ran into a checksum exception:
```
Caused by: java.io.IOError: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
	at org.mapdb.StoreDirect.checkHeaders(StoreDirect.java:258)
	at org.mapdb.StoreDirect.<init>(StoreDirect.java:207)
	at org.mapdb.DBMaker.extendStoreDirect(DBMaker.java:918)
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:722)
	at org.mapdb.DBMaker.make(DBMaker.java:665)
	at com.mindbusters.hazelcast.navigablemap.partitions.OffHeapMapDBPartition.getMap(OffHeapMapDBPartition.java:38)
	at com.mindbusters.hazelcast.navigablemap.partitions.OffHeapMapDBPartition.getDataMap(OffHeapMapDBPartition.java:67)
	at com.mindbusters.hazelcast.navigablemap.partitions.OffHeapMapDBPartition.clear(OffHeapMapDBPartition.java:82)
	at com.mindbusters.hazelcast.navigablemap.callables.SetPartitionData.call(SetPartitionData.java:44)
	at com.mindbusters.hazelcast.navigablemap.callables.SetPartitionData.call(SetPartitionData.java:16)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.hazelcast.executor.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:187)
	... 5 more
Caused by: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
	... 17 more
```

But I have not closed the store in any way, this is a fresh new store never closed.

And this is how I create the map:

```java
public class OffHeapMapDBPartition <K extends Comparable, V> implements ISortedPartition<K,V> {
    private static final long serialVersionUID = -3158441942676405723L;
    private static final String PATH = "/tmp/";
    private transient BTreeMap<K, V> sortedData = null;
    private final String iMapName, partitionId;

    public OffHeapMapDBPartition(String iMapName, String partitionId) {
        this.iMapName = iMapName;
        this.partitionId = partitionId;
    }

    public BTreeMap<K, V> getMap() {
        return sortedData != null
                ? sortedData
                : (
                    sortedData = DBMaker.newFileDB(new File(PATH + iMapName + ".mapdb"))
                        .asyncWriteEnable()
                        //.closeOnJvmShutdown()
                        .transactionDisable()
                        .mmapFileEnable()
                        .make()
                        .getTreeMap(partitionId)
                );
    }
}
```

and when I try to open in another jvm I will get:
```
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Error while opening store. Make sure you have right password, compression or encryption is well configured.
	at com.mindbusters.hazelcast.navigablemap.mapstore.AbstractNavigableMapStore.waitForDone(AbstractNavigableMapStore.java:43)
	at com.mindbusters.hazelcast.navigablemap.DistributedNavigableMap.subMap(DistributedNavigableMap.java:102)
	at com.mindbusters.hazelcast.navigablemap.DistributedNavigableMap.subMap(DistributedNavigableMap.java:64)
	at com.mindbusters.utils.navigablemaptest.TestNavigableTable2.main(TestNavigableTable2.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Error while opening store. Make sure you have right password, compression or encryption is well configured.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.hazelcast.executor.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:189)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:186)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.PoolExecutorThreadFactory$ManagedThread.run(PoolExecutorThreadFactory.java:59)
Caused by: java.lang.IllegalArgumentException: Error while opening store. Make sure you have right password, compression or encryption is well configured.
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:777)
	at org.mapdb.DBMaker.make(DBMaker.java:665)
	at com.mindbusters.hazelcast.navigablemap.partitions.OffHeapMapDBPartition.getMap(OffHeapMapDBPartition.java:32)
	at com.mindbusters.hazelcast.navigablemap.partitions.OffHeapMapDBPartition.clear(OffHeapMapDBPartition.java:96)
	at com.mindbusters.hazelcast.navigablemap.callables.SetPartitionData.call(SetPartitionData.java:44)
	at com.mindbusters.hazelcast.navigablemap.callables.SetPartitionData.call(SetPartitionData.java:16)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.hazelcast.executor.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:187)
	... 5 more
Caused by: java.lang.UnsupportedOperationException
	at org.mapdb.SerializerBase.getEngine(SerializerBase.java:1538)
	at org.mapdb.SerializerBase.deserialize3(SerializerBase.java:1209)
	at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1132)
	at org.mapdb.SerializerBase.deserialize(SerializerBase.java:867)
	at org.mapdb.Store.deserialize(Store.java:297)
	at org.mapdb.StoreDirect.get2(StoreDirect.java:475)
	at org.mapdb.StoreDirect.get(StoreDirect.java:428)
	at org.mapdb.Caches$HashTable.get(Caches.java:246)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:771)
	... 12 more
```

**Comment by jankotek** [comment]
Single storage can be opened from only one JVM. Multiple processes are not supported yet.

**Comment by KIC** [comment]
Hmm that is too bad. It would be a really big feature supporting multiple JVM's accessing the same data. Anyway thanks for the hint!

**Comment by jankotek** [comment]
There is plan to do that via shared 
memory, but it will take some 
time, it is not priority at all.
