### ISSUE TITLE
multi-thread transaction commit hang

### ISSUE THREAD

**Issue by bobwenx** [jankotek/mapdb#525]
MapDB version: 1.0.7
JVM: 1.8.0_45
OS: OS X 10

test code that reproduce the problem:
```java
      ExecutorService executorService = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors() * 2);
      TxMaker txMaker = DBMaker.newFileDB(JavaFile.createTempFile("testMapDbTx").toFile())
                                 .cacheSize(1024 * 64)
                                 .mmapFileEnablePartial()
                                 .snapshotEnable()
                                 .makeTxMaker();

       db = txMaker.makeTx();
       db.createHashMap("subscriptions")
                          .keySerializer(new Serializer.CompressionWrapper<>(Serializer.STRING))
                          .counterEnable()
                          .make();
        db.commit();

        CountDownLatch latch = new CountDownLatch(1024 * 64);
        long begin = System.currentTimeMillis();
        for(int i = 0 ; i< (1024 * 64); i++){
            final int finalI = i;
            executorService.submit(() -> {
                DB transaction = txMaker.makeTx();
                transaction.getHashMap("subscriptions").put("test-key-" + finalI, "AnyObject");
                transaction.commit();
                latch.countDown();
            });
        }

        System.out.println(latch.await(10, TimeUnit.MINUTES));
        System.out.println("tx time esaped:" + (System.currentTimeMillis() - begin));
        txMaker.close();
```

in my environment, the above code will never finish. when i debug it, i see the thread blocking are most case by `transaction.commit()`, after half of transaction committed, it just hang there without return.

**Comment by bobwenx** [comment]
ok,after i surround async task with try/catch/finally. the code no longer hang:
```java
try {
    DB transaction = txMaker.makeTx();
     transaction.getHashMap("subscriptions").put("test-key-" + finalI, "AnyObject");
     transaction.commit();
catch (Exception e) {
       e.printStackTrace();
}finally{
       latch.countDown();
}
```

but this cause new problem, the `TxEngine` will throw `org.mapdb.TxRollbackException` if i try to commit transaction per task in multi-thread environment. Does it means MapDB's transaction only operation on `HashMap` level,  not the row level(the entry i put info hashMap)?

**Comment by bwzhang2011** [comment]
@bobwenx, did you test with mapdb2.0 snapshot ?

**Comment by bobwenx** [comment]
no, `2.x` still in `snapshot` status.

**Comment by bobwenx** [comment]
And the test code in code branch(both `master` & `1.x`) only test transaction with global commit, not per task.
see:https://github.com/jankotek/mapdb/blob/d9c5b818020e0d623364c6d2e7f179899978d919/src/test/java/org/mapdb/TxMakerTest.java

**Comment by bobwenx** [comment]
I have tested the 2.0 snapshot on master branch, and the result still same:
```java
org.mapdb.TxRollbackException
	at org.mapdb.TxEngine$Tx.commit(TxEngine.java:525)
	at org.mapdb.DB.commit(DB.java:2391)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

**Comment by jankotek** [comment]
I replicated issue with code bellow. TxRollbackException is thrown when there is conflict on write. You should catch this exception and try again until your code succeeds. Closing because this is not really a bug

```
package org.mapdb;

import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

public class Issue525Test {

    @Test
    public void test() throws IOException, InterruptedException {
        ExecutorService executorService =    Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors() * 2);
        final TxMaker txMaker = DBMaker.newFileDB(File.createTempFile("mapdb", ""))
                .cacheSize(1024 * 64)
                .mmapFileEnablePartial()
                .snapshotEnable()
                .makeTxMaker();

        DB db = txMaker.makeTx();
        db.createHashMap("subscriptions")
                .keySerializer(new Serializer.CompressionWrapper(Serializer.STRING))
                .counterEnable()
                .make();
        db.commit();

        final CountDownLatch latch = new CountDownLatch(1024 * 64);
        long begin = System.currentTimeMillis();
        for(int i = 0 ; i< (1024 * 64); i++) {
            final int finalI = i;
            executorService.submit(new Runnable() {
                @Override
                public void run() {
                    try {
                        DB transaction = txMaker.makeTx();
                        transaction.getHashMap("subscriptions").put("test-key-" + finalI, "AnyObject");
                        transaction.commit();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    latch.countDown();
                }
            });
        }
        System.out.println(latch.await(10, TimeUnit.MINUTES));
        System.out.println("tx time esaped:" + (System.currentTimeMillis() - begin));
        txMaker.close();
    }

}
```

**Comment by bobwenx** [comment]
@jankotek, Yes,  from the perspective of mapdb, this is not a bug. but i wonder why this exception be thrown? what if do is try to append sequenced entry in a shared hash map.
Does it means MapDB's transaction only works in HashMap level, not the row level(the entry i put info hashMap)? And if i try to update entry in a shared HashMap, i have to faces problems in optimistic locking failure(snapshot conflict)?

**Comment by jankotek** [comment]
Transactions are working at record level, in this case conflict is with  Hash Dir Nodes. Tree is empty, so conflict is more often, once map grows to couple of thousands entries, conflicts will become less frequent.
