### ISSUE TITLE
BTreeMap throws IndexOutOfBoundsException under concurrent access

### ISSUE THREAD

**Issue by jankotek** [jankotek/mapdb#534]
There is race condition in 1.0 and 2.0. It is caused by wrong levels. 

```
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at java.util.Collections$SynchronizedList.get(Collections.java:2417)
        at org.mapdb.BTreeMap.put2(BTreeMap.java:1179)
        at org.mapdb.BTreeMap.put(BTreeMap.java:1024)
        at org.mapdb.BTreeMapParTest$1.call(BTreeMapParTest.java:42)
        at org.mapdb.Exec$1.run(Exec.java:29)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by jankotek** [comment]
Fixed in both branches
