### ISSUE TITLE
compaction of HTreeMap causes fatal error

### ISSUE THREAD

**Issue by dmk23** [jankotek/mapdb#542]
Using 2.0-beta1, created direct memory DB, generated HTreeMap, populated it with records. Attempts to compact DB causes a fatal error. Note, this is not a problem if BTreeMap is used instead.

```
Exception in thread "main" java.lang.AssertionError
        at org.mapdb.StoreDirect.compactIndexPage(StoreDirect.java:1075)
        at org.mapdb.StoreDirect.compactIndexPages(StoreDirect.java:1023)
        at org.mapdb.StoreDirect.compact(StoreDirect.java:920)
        at org.mapdb.DB.compact(DB.java:2431)
        at com.app.Test.main(Test.java:1170)
Jul 05, 2015 2:47:15 AM org.mapdb.Volume finalize
WARNING: Open Volume was GCed, possible file handle leak.
```

The map and the DB are static field in the main class, so they should never get GC'd

**Comment by jankotek** [comment]
There is rounding conversion error. Will fix in 2.0-beta2
