### ISSUE TITLE
MapDB 1.0.7 - NPE in org.mapdb.StoreDirect.longStackTake

### ISSUE THREAD

**Issue by michaelr524** [jankotek/mapdb#544]
java.lang.NullPointerException
	at org.mapdb.StoreDirect.longStackTake(StoreDirect.java:940)
	at org.mapdb.StoreDirect.freeIoRecidTake(StoreDirect.java:1051)
	at org.mapdb.StoreDirect.put(StoreDirect.java:363)
	at org.mapdb.Caches$HashTable.put(Caches.java:216)
	at org.mapdb.EngineWrapper.put(EngineWrapper.java:53)
	at org.mapdb.HTreeMap.putInner(HTreeMap.java:589)
	at org.mapdb.HTreeMap.put(HTreeMap.java:488)
	at org.mapdb.HTreeMap$KeySet.add(HTreeMap.java:826)

After I got this exception in one thread, other threads (with other DB files) failed with this exception:

java.lang.IllegalAccessError: already closed
	at org.mapdb.EngineWrapper$1.get(EngineWrapper.java:472)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.HTreeMap.getInner(HTreeMap.java:448)
	at org.mapdb.HTreeMap.getPeek(HTreeMap.java:436)
	at org.mapdb.HTreeMap.containsKey(HTreeMap.java:300)
	at org.mapdb.HTreeMap$KeySet.contains(HTreeMap.java:813)

Does anyone know what could possibly cause this error?

This is how I construct my DB:

            db = DBMaker.newTempFileDB()
                    .deleteFilesAfterClose()
                    .closeOnJvmShutdown()
                    .mmapFileEnableIfSupported()
                    .transactionDisable()
                    .make();

**Comment by jankotek** [comment]
MapDB most is most likely accessed after it was 
closed. Old store is dereferenced on close to 
prevent memory leaks. So MapDB starts throwing 
NPE after its closed. 

I would check your datamodel. There is possibly 
background thread. Database could be also closed 
by shutdown hook, but other shutdown hook might 
still access it.

**Comment by michaelr524** [comment]
Hi Jan, 

Thanks for the prompt answer. 
Unfortunately no additional logs were available, but the devops guy confirmed this happened while the program was shutting down.
