### ISSUE TITLE
Head checksum broken, mapdb:2.0-beta2

### ISSUE THREAD

**Issue by romanman** [jankotek/mapdb#547]
```
Caused by: org.mapdb.DBException$HeadChecksumBroken: Head checksum broken, perhaps db was not closed correctly?
	at org.mapdb.StoreDirect.initOpen(StoreDirect.java:153)
	at org.mapdb.StoreDirect.init(StoreDirect.java:112)
	at org.mapdb.DBMaker$Maker.makeEngine(DBMaker.java:1228)
```
```
OS: windows8_64
Java: 8
```

I get it on start after vm process kill, 
had a hope that the `closeOnJvmShutdown()`
will help. Any advice ?

p.s: no transaction used, that is how I create the mapdb structures

```
        DB db = DBMaker.fileDB(dbFile)
                .transactionDisable()
                .fileMmapEnableIfSupported()
                .closeOnJvmShutdown()
                .make();

        Map<Long, List<IndexedBlockStore.BlockInfo>> indexDB = db.hashMapCreate("index")
                .keySerializer(Serializer.LONG)
                .valueSerializer(BLOCK_INFO_SERIALIZER)
                .counterEnable()
                .makeOrGet();

```

Thanks 
Roman

**Comment by jankotek** [comment]
Hi, In order to get crash protection and recovery you need to keep Write Ahead Log enabled. So do not disable transations. It is slower but safer.

**Comment by romanman** [comment]
Thanks
