### ISSUE TITLE
org.mapdb.DBException$EngineGetVoid: Recid passed to Engine.get() does not exist. Possible data corruption!

### ISSUE THREAD

**Issue by lamfire** [jankotek/mapdb#550]
final DB db = DBMaker.fileDB(file).fileMmapEnable().fileChannelEnable().asyncWriteEnable().asyncWriteFlushDelay(1000).asyncWriteQueueSize(10000).make();
        final BTreeMap<Long,Long> map = db.treeMap("TreeMap");

mapdb version: 2.0-beta2
jvm process : kill -9 xxxx
reopen and read
Exception in thread "main" org.mapdb.DBException$EngineGetVoid: Recid passed to Engine.get() does not exist. Possible data corruption!
	at org.mapdb.StoreDirect.indexValGet(StoreDirect.java:1186)
	at org.mapdb.StoreWAL.indexValGet(StoreWAL.java:469)
	at org.mapdb.StoreWAL.get2(StoreWAL.java:645)
	at org.mapdb.Store.get(Store.java:224)
	at org.mapdb.BTreeMap$BTreeIterator.advance(BTreeMap.java:1328)
	at org.mapdb.BTreeMap.sizeLong(BTreeMap.java:1795)
	at org.mapdb.BTreeMap.size(BTreeMap.java:1782)

**Comment by jankotek** [comment]
I just fixed one issue in StoreWAL which could have cause it. But will need more testing.
