### ISSUE TITLE
Out Of Memory Exception while rehashing

### ISSUE THREAD

**Issue by jigarMShah** [jankotek/mapdb#580]
Hi jankotek,

Problem statement: Convert large JSON file(> 100MB) to CSV file.
I have written my own logic (logic.png - tried to represent my logic here) to read the arbitrary JSON file and generate output rows.
I have written logic using Jackson which read data as a stream and generate output rows from different nested objects/array which are present into JSON file.

Here, I am using MapDB to keep the huge volume data in set<String> before merging it with different object's data, but getting the "Out Of Memory" exception.

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.mapdb.Store$LongLongMap.rehash(Store.java:1441)
	at org.mapdb.Store$LongLongMap.insert(Store.java:1388)
	at org.mapdb.Store$LongLongMap.put(Store.java:1344)
	at org.mapdb.StoreWAL.indexValPut(StoreWAL.java:499)
	at org.mapdb.StoreDirect.preallocate(StoreDirect.java:601)
	at org.mapdb.StoreCached.put(StoreCached.java:434)
	at org.mapdb.HTreeMap.putInner(HTreeMap.java:1007)
	at org.mapdb.HTreeMap.put(HTreeMap.java:884)
	at org.mapdb.HTreeMap$KeySet.add(HTreeMap.java:1263)
	at java.util.AbstractCollection.addAll(Unknown Source)
	at com.json.api.parser.JsonReader.extractJSONObject(JsonReader.java:337)
	at com.json.api.parser.JsonReader.extractJSONValue(JsonReader.java:562)
	at com.json.api.parser.JsonReader.extractJSONArray(JsonReader.java:549)
	at com.json.api.parser.JsonReader.extractJSONValue(JsonReader.java:565)
	at com.json.api.parser.JsonReader.extractJSONObject(JsonReader.java:370)
	at com.json.api.parser.JsonReader.extractJSONValue(JsonReader.java:562)
	at com.json.api.parser.JsonReader.extractJSONObject(JsonReader.java:363)
	at com.json.api.parser.JsonReader.extractJSONValue(JsonReader.java:562)
	at com.json.api.parser.JsonReader.initJsonReader(JsonReader.java:155)
	at com.json.api.parser.JsonReader.<init>(JsonReader.java:58)
	at com.json.api.parser.JsonReader.main(JsonReader.java:577)

I keep clearing the set<String> before and after committing.
I have tried using Set of StringBuilder, but getting InvalidArgument exception for hash key.
![logic](https://cloud.githubusercontent.com/assets/14271906/9848741/6dafad60-5b01-11e5-8744-480ac8a5e402.png)

**Comment by jigarMShah** [comment]
Hi @jankotek 
Could you please respond to this one.

**Comment by jankotek** [comment]
would you post your DBMaker config? I think you need to disable transactions.

**Comment by bwzhang2011** [comment]
@jigarMShah, any update with such issue ?

**Comment by jankotek** [comment]
Hi, please call commit from time to time, that will keep Async Write Queue smaller. Or disable Async Write completely.
