### ISSUE TITLE
IndexOutOfBoundsException in HTreeMap

### ISSUE THREAD

**Issue by mkalinin** [jankotek/mapdb#587]
hey there,
we have faced with following problem
```
java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
  at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[na:1.8.0_60]
  at java.util.ArrayList.get(ArrayList.java:429) ~[na:1.8.0_60]
  at java.util.Collections$SynchronizedList.get(Collections.java:2417) ~[na:1.8.0_60]
  at org.mapdb.StoreWAL.loadLongStackPage(StoreWAL.java:552) ~[mapdb-2.0-beta6.jar:na]
  at org.mapdb.StoreCached.longStackTake(StoreCached.java:176) ~[mapdb-2.0-beta6.jar:na]
  at org.mapdb.StoreDirect.freeRecidTake(StoreDirect.java:1657) ~[mapdb-2.0-beta6.jar:na]
  at org.mapdb.StoreDirect.preallocate(StoreDirect.java:594) ~[mapdb-2.0-beta6.jar:na]
  at org.mapdb.StoreCached.put(StoreCached.java:434) ~[mapdb-2.0-beta6.jar:na]
  at org.mapdb.Engine$CloseOnJVMShutdown.put(Engine.java:448) ~[mapdb-2.0-beta6.jar:na]
  at org.mapdb.HTreeMap.putInner(HTreeMap.java:1007) ~[mapdb-2.0-beta6.jar:na]
  at org.mapdb.HTreeMap.put(HTreeMap.java:884) ~[mapdb-2.0-beta6.jar:na]
  at org.ethereum.db.BlockQueueImpl.add(BlockQueueImpl.java:130) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
  at org.ethereum.net.eth.sync.SyncQueue.produceQueue(SyncQueue.java:104) [ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
  at org.ethereum.net.eth.sync.SyncQueue.access$000(SyncQueue.java:33) [ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
  at org.ethereum.net.eth.sync.SyncQueue$1.run(SyncQueue.java:78) [ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
  at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```
It arises each time after about `10-12` hours of instant work with the structure. We use transactional database and create `HTreeMap` with following code:
```
db.hashMapCreate(STORE_NAME)
    .keySerializer(Serializer.LONG)
    .valueSerializer(Serializers.BLOCK_WRAPPER)
    .makeOrGet();
```
Where `Serializers.BLOCK_WRAPPER` is a custom one based on `BYTE_ARRAY` serializer. 
MapDB version is `2.0-beta6`.

Do you have any ideas about this problem? I can provide you with any info required to discover the reason, just let me know if I can do anything.

Thanks in advance

**Comment by mkalinin** [comment]
btw, we also met following error within previous one. It's about another structure, these structures are built in different databases which are stored in different folders. But it might be related to each other

```
org.mapdb.DBException$DataCorruption: null
  at org.mapdb.StoreWAL.walStartNextFile(StoreWAL.java:291) ~[mapdb-2.0-beta6.jar:na]
  at org.mapdb.StoreWAL.commit(StoreWAL.java:958) ~[mapdb-2.0-beta6.jar:na]
  at org.mapdb.Engine$CloseOnJVMShutdown.commit(Engine.java:487) ~[mapdb-2.0-beta6.jar:na]
  at org.mapdb.DB.commit(DB.java:2597) ~[mapdb-2.0-beta6.jar:na]
  at org.ethereum.db.HashStoreImpl.pollBatch(HashStoreImpl.java:151) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
  at org.ethereum.net.eth.sync.SyncQueue.pollHashes(SyncQueue.java:281) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
  at org.ethereum.net.eth.handler.EthHandler.sendGetBlocks(EthHandler.java:342) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
  at org.ethereum.net.eth.handler.EthHandler.changeState(EthHandler.java:473) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
  at org.ethereum.net.server.Channel.changeSyncState(Channel.java:251) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
  at org.ethereum.net.eth.sync.PeersPool.changeState(PeersPool.java:207) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
  at org.ethereum.net.eth.sync.BlockRetrievingState.doMaintain(BlockRetrievingState.java:30) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
  at org.ethereum.net.eth.sync.SyncManager.maintainState(SyncManager.java:471) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
  at org.ethereum.net.eth.sync.SyncManager.access$800(SyncManager.java:38) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
  at org.ethereum.net.eth.sync.SyncManager$1$1.run(SyncManager.java:120) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_60]
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_60]
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_60]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
  at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

**Comment by jankotek** [comment]
Hi, I had similar issue, I believe it is fixed in recent snapshot (but there is storage format change). Beta8 will be released in a few days. Please reopen this issue if it persist after that.

**Comment by mkalinin** [comment]
Hi, thanks a lot!

**Comment by romanman** [comment]
@mkalinin  @jankotek : got it thanks 
how we can try the snapshot?
 we have long runs so we can start 
right away.

**Comment by jankotek** [comment]
There is a snapshot repo
http://www.mapdb.org/doc/getting-started.html#maven

**Comment by romanman** [comment]
cool, thanks

**Comment by mkalinin** [comment]
hello @jankotek 
We have faced with it again with `2.0-beta8` version. It's quite rare but breaks our main logic during long runs.
```
java.lang.IndexOutOfBoundsException: Index: 15, Size: 15
    at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[na:1.8.0_60]
    at java.util.ArrayList.get(ArrayList.java:429) ~[na:1.8.0_60]
    at java.util.Collections$SynchronizedList.get(Collections.java:2417) ~[na:1.8.0_60]
    at org.mapdb.StoreWAL.loadLongStackPage(StoreWAL.java:512) ~[mapdb-2.0-beta8.jar:na]
    at org.mapdb.StoreCached.longStackTake(StoreCached.java:176) ~[mapdb-2.0-beta8.jar:na]
    at org.mapdb.StoreDirect.freeRecidTake(StoreDirect.java:1663) ~[mapdb-2.0-beta8.jar:na]
    at org.mapdb.StoreDirect.preallocate(StoreDirect.java:600) ~[mapdb-2.0-beta8.jar:na]
    at org.mapdb.StoreCached.put(StoreCached.java:433) ~[mapdb-2.0-beta8.jar:na]
    at org.mapdb.Engine$CloseOnJVMShutdown.put(Engine.java:448) ~[mapdb-2.0-beta8.jar:na]
    at org.mapdb.HTreeMap.putNew(HTreeMap.java:974) ~[mapdb-2.0-beta8.jar:na]
    at org.mapdb.HTreeMap.putInner(HTreeMap.java:949) ~[mapdb-2.0-beta8.jar:na]
    at org.mapdb.HTreeMap.put(HTreeMap.java:879) ~[mapdb-2.0-beta8.jar:na]
    at org.ethereum.db.BlockQueueImpl.add(BlockQueueImpl.java:129) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
    at org.ethereum.sync.SyncQueue.addNew(SyncQueue.java:211) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
    at org.ethereum.net.eth.handler.EthHandler.processNewBlock(EthHandler.java:247) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
    at org.ethereum.net.eth.handler.EthHandler.channelRead0(EthHandler.java:126) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
    at org.ethereum.net.eth.handler.EthLegacy.channelRead0(EthLegacy.java:49) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
    at org.ethereum.net.eth.handler.Eth61.channelRead0(Eth61.java:63) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
    at org.ethereum.net.eth.handler.Eth61.channelRead0(Eth61.java:30) ~[ethereumj-core-1.0.0-stage-SNAPSHOT.jar:na]
```

**Comment by jankotek** [comment]
I believe this is now fixed (yet again) in current snapshot.

But current snapshot changes format and does not have crash recovery yet. New beta will follow in a few days.

**Comment by mkalinin** [comment]
thanks @jankotek 
Our code is running with latest snapshot now. Need to test it for some period of time

**Comment by jankotek** [comment]
There is new 2.0-beta10 release. I believe this is now fixed.
