### ISSUE TITLE
NPE in HTreeMap expiration

### ISSUE THREAD

**Issue by jankotek** [jankotek/mapdb#588]
Looks like some sort of hashing issue.

From mailing list:

```
DISK_DB = DBMaker.fileDB(file).cacheSize(65_536).make()
DISK_DB.hashMapCreate("DISK").keySerializer(Serializer.UUID)
        .valueSerializer(new 
MyClass.CustomSerializer()).expireAfterWrite(6, TimeUnit.HOURS).makeOrGet()
```

I do have multiple threads but not tons of stuff going on.
```
! java.lang.NullPointerException: null
! at org.mapdb.HTreeMap.expirePurgeSegment(HTreeMap.java:2095) 
~[bodyguard-0.0.287.jar:na]
! at org.mapdb.HTreeMap.expirePurge(HTreeMap.java:2038) 
~[bodyguard-0.0.287.jar:na]
! at org.mapdb.HTreeMap.put(HTreeMap.java:893) ~[bodyguard-0.0.287.jar:na]
```
After a will change exceptions to:
```
! org.mapdb.DBException$DataCorruption: inconsistent hash
! at org.mapdb.HTreeMap.expirePurgeSegment(HTreeMap.java:2096) 
~[bodyguard-0.0.287.jar:na]
! at org.mapdb.HTreeMap.expirePurge(HTreeMap.java:2038) 
~[bodyguard-0.0.287.jar:na]
! at org.mapdb.HTreeMap.put(HTreeMap.java:893) ~[bodyguard-0.0.287.jar:na]
```
Restart does not recover it.

**Comment by esnellman** [comment]
Thanks man!
