### ISSUE TITLE
NSE: Could not serialize unknown object: RecordSerializerN

### ISSUE THREAD

**Issue by jandam** [jankotek/mapdb#602]
RecordSerializerN is my serializable class.
```
class RecordSerializerN extends Serializer<RecordN> implements Serializable {
    private static final long serialVersionUID = -7712313262727669450L;
...
}
```
MapDB code:
```
DB dbNodeParam2 = DBMaker
                        .fileDB(new File("/tmp/pokus0"))
                        .mmapFileEnableIfSupported()
                        .transactionDisable()
                        .make();
                DB.BTreeMapMaker mm = dbNodeParam2.treeMapCreate(nameSpatialN)
                        .keySerializer(BTreeKeySerializer.LONG)
                        .valueSerializer(new RecordSerializerN())
                        .nodeSize(120)
                        .counterEnable();

                Iterator<Fun.Pair> sn = (Iterator)builderN.build(progressProvider, true);
                Pump.archiveTreeMap(sn, "/tmp/pokus1", Volume.MappedFileVol.FACTORY, mm);
```
Exception:
```
java.io.IOError: java.io.NotSerializableException: Could not serialize unknown object: com.crcdata.addin.map3dww.layer.osm.RecordSerializerN
	at org.mapdb.Store.serialize(Store.java:388)
	at org.mapdb.StoreArchive.put(StoreArchive.java:146)
	at org.mapdb.Pump.buildTreeMap(Pump.java:496)
	at org.mapdb.StoreArchive.rewriteNamedCatalog(StoreArchive.java:193)
	at org.mapdb.Pump.archiveTreeMap(Pump.java:964)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.NotSerializableException: Could not serialize unknown object: RecordSerializerN
	at org.mapdb.SerializerBase.serializeUnknownObject(SerializerBase.java:1801)
	at org.mapdb.SerializerBase.serialize(SerializerBase.java:1000)
	at org.mapdb.SerializerBase.serialize(SerializerBase.java:946)
	at org.mapdb.Serializer$35.serialize(Serializer.java:2237)
	at org.mapdb.Serializer.valueArraySerialize(Serializer.java:2317)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:817)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:753)
	at org.mapdb.Store.serialize(Store.java:309)
	... 13 more
```

**Comment by jandam** [comment]
I found that fix for this is on TODO list.
StoreArchive:rewriteNamedCatalog line 203

**Comment by jankotek** [comment]
Wont fix
