### ISSUE TITLE
nulls in composite keys cause DB corruption

### ISSUE THREAD

**Issue by dmk23** [jankotek/mapdb#610]
I have some code using BTreeMap with composite keys and by mistake used a null in the object array key. The write fails when actual serialization is attempted on DB shutdown:

```
Exception in thread "MapDB shutdown hook" java.lang.NullPointerException
	at org.mapdb.DataIO$DataOutputByteArray.writeUTF(DataIO.java:1070)
	at org.mapdb.Serializer$3.serialize(Serializer.java:111)
	at org.mapdb.Serializer$3.serialize(Serializer.java:108)
	at org.mapdb.BTreeKeySerializer$ArrayKeySerializer.serialize(BTreeKeySerializer.java:678)
	at org.mapdb.BTreeKeySerializer$ArrayKeySerializer.serialize(BTreeKeySerializer.java:631)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:814)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:753)
	at org.mapdb.Store.serialize(Store.java:304)
	at org.mapdb.StoreCached.flushWriteCacheSegment(StoreCached.java:388)
	at org.mapdb.StoreCached.flushWriteCache(StoreCached.java:364)
	at org.mapdb.StoreCached.flush(StoreCached.java:320)
	at org.mapdb.StoreDirect.close(StoreDirect.java:1071)
	at org.mapdb.Engine$CloseOnJVMShutdown.close(Engine.java:473)
	at org.mapdb.Engine$CloseOnJVMShutdown$1.run(Engine.java:426)
	at java.lang.Thread.run(Thread.java:745)
```

The problem is when the process is restarted using the same DB I try to run a diagnostic iterator on the full map to display the contents. Unfortunately this causes this hard failure -

```
java.lang.NullPointerException
	at org.mapdb.BTreeMap.<init>(BTreeMap.java:976)
	at org.mapdb.DB.treeMap(DB.java:1465)
	at org.mapdb.DB$BTreeMapMaker.makeOrGet(DB.java:1224)
        ... application code ...
```

Accidental use of nulls in keys should fail gracefully, rather than corrupt databases. It is quite disturbing that a software error in the client app could cause the loss of data...

Additionally, another set of errors could be introduced if composite keys are not validated when first used and the actual exception appears on flush/close/shutdown. There ought to be an option to enforce validation of keys whenever they are used (yes, at a performance cost, but for some applications that may still be valuable - especially in the test/debug mode).

This issue was observed in **2.0-beta8**

**Comment by jankotek** [comment]
Could not replace, closing
