### ISSUE TITLE
MapDB 1.0.8 EOFException

### ISSUE THREAD

**Issue by mmarin-m** [jankotek/mapdb#615]
I am using version 1.0.8 of mapDB and after 5000 to 7000 insertions starts throwing this error:

com.services.AException: MapDB error: addItemSingle(String, List<String>)
	at com.components.EMapDB.addItemSingle(EMapDB.java:270)
	at com.components.ESI.storeInMap(ESI.java:1123)
	at com.components.ESI.populate(ESI.java:998)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOError: java.io.EOFException
	at org.mapdb.Volume$FileChannelVol.getSixLong(Volume.java:965)
	at org.mapdb.StoreDirect.longStackTake(StoreDirect.java:959)
	at org.mapdb.StoreDirect.freeIoRecidTake(StoreDirect.java:1062)
	at org.mapdb.StoreDirect.put(StoreDirect.java:374)
	at org.mapdb.EngineWrapper.put(EngineWrapper.java:53)
	at org.mapdb.HTreeMap.putInner(HTreeMap.java:589)
	at org.mapdb.HTreeMap.put(HTreeMap.java:488)
	at com.components.EMapDB.addItemSingle(EMapDB.java:267)
	... 6 more
Caused by: java.io.EOFException
	at org.mapdb.Volume$FileChannelVol.readFully(Volume.java:947)
	at org.mapdb.Volume$FileChannelVol.getSixLong(Volume.java:956)
	... 13 more

this is the mapDB configuration:

db = DBMaker.newFileDB(new File(name))
          .transactionDisable()
          .asyncWriteEnable()
          .asyncWriteQueueSize(10000) //optionally change queue size
          .closeOnJvmShutdown()
          .make();

also I am using 3 HTreeMap and storing String as Key and List<String> as values.

**Comment by jankotek** [comment]
Use MapDB 2.  It is more stable at this point.

**Comment by neworld** [comment]
Important fixes for MapDB 2 beta is released every two week. That doesn't sound stable. Is really good idea to use MapDB 2 for heavy usage in prod?
