### ISSUE TITLE
java.io.IOException: The parameter is incorrect on mapDB 1.0.8

### ISSUE THREAD

**Issue by mmarin-m** [jankotek/mapdb#618]
I got this error using mapDB 1.0.8:

```
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Writer thread failed
at org.mapdb.AsyncWriteEngine.checkState(AsyncWriteEngine.java:262)
at org.mapdb.AsyncWriteEngine.get(AsyncWriteEngine.java:326)
at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
at org.mapdb.HTreeMap.getInner(HTreeMap.java:448)
at org.mapdb.HTreeMap.get(HTreeMap.java:397)
at com.asp.components.MapDB.getItemInfoSingle(MapDB.java:360)
... 6 more
Caused by: java.io.IOError: java.io.IOException: The parameter is incorrect
at org.mapdb.Volume$FileChannelVol.putData(Volume.java:930)
at org.mapdb.StoreDirect.put2(StoreDirect.java:405)
at org.mapdb.StoreDirect.update2(StoreDirect.java:551)
at org.mapdb.StoreDirect.update(StoreDirect.java:502)
at org.mapdb.EngineWrapper.update(EngineWrapper.java:63)
at org.mapdb.AsyncWriteEngine.access$101(AsyncWriteEngine.java:76)
at org.mapdb.AsyncWriteEngine.runWriter(AsyncWriteEngine.java:220)
at org.mapdb.AsyncWriteEngine$WriterRunnable.run(AsyncWriteEngine.java:172)
... 1 more
Caused by: java.io.IOException: The parameter is incorrect
at sun.nio.ch.FileDispatcherImpl.pwrite0(Native Method)
at sun.nio.ch.FileDispatcherImpl.pwrite(Unknown Source)
at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
at sun.nio.ch.IOUtil.write(Unknown Source)
at sun.nio.ch.FileChannelImpl.writeInternal(Unknown Source)
at sun.nio.ch.FileChannelImpl.write(Unknown Source)
at org.mapdb.Volume$FileChannelVol.writeFully(Volume.java:865)
at org.mapdb.Volume$FileChannelVol.putData(Volume.java:928)
... 8 more
```

The mapDB configuration is:
```
db = DBMaker.newFileDB(new File(name))
          .transactionDisable()
          .cacheDisable()
          .asyncWriteEnable()
          .asyncWriteQueueSize(10000) //optionally change queue size
          .closeOnJvmShutdown()
          .make();
```

**Comment by jankotek** [comment]
I think there is a race condition, the async writer thread tries to write into file which was already closed. Disable async writer.
