### ISSUE TITLE
ArrayIndexOutOfBoundsException exception with 1.0.7

### ISSUE THREAD

**Issue by chabhishek123** [jankotek/mapdb#624]
Hi , 
 I am using MapDB version : 1.0.7. The data file is not corrupted. We are seeing an issue in production, any help to resolve this issue is highly appreciated

java.lang.ArrayIndexOutOfBoundsException: 33714195
       at org.mapdb.Volume$ByteBufferVol.getDataInput(Volume.java:387) ~[mapdb-1.0.7.jar:na]
       at org.mapdb.Volume$ByteBufferVol.getDataInput(Volume.java:269) ~[mapdb-1.0.7.jar:na]
       at org.mapdb.StoreDirect.get2(StoreDirect.java:448) ~[mapdb-1.0.7.jar:na]
       at org.mapdb.StoreDirect.get(StoreDirect.java:428) ~[mapdb-1.0.7.jar:na]
       at org.mapdb.Caches$HashTable.get(Caches.java:246) ~[mapdb-1.0.7.jar:na]
       at org.mapdb.EngineWrapper.get(EngineWrapper.java:58) ~[mapdb-1.0.7.jar:na]
       at org.mapdb.BTreeMap$BTreeIterator.advance(BTreeMap.java:924) ~[mapdb-1.0.7.jar:na]
       at org.mapdb.BTreeMap$BTreeKeyIterator.next(BTreeMap.java:1047) ~[mapdb-1.0.7.jar:na]

**DB is created as :**
public MapDbDataStore(DataStoreDefinition dataStoreDef) {
		this.name = dataStoreDef.getName();
		
		if (this.name == null) {
			throw new MicrolibConfigException("data-store name is empty in " + dataStoreDef);
		}
		
		this.dbFile = resolveDbFile(dataStoreDef);
		
		DBMaker dbMaker = DBMaker.newFileDB(dbFile);
		
		dbMaker.transactionDisable().closeOnJvmShutdown();
		
		dbMaker = dbMaker.mmapFileEnableIfSupported();
		
		if (dataStoreDef.isCompressed()) {
			dbMaker = dbMaker.compressionEnable();
		}

		this.diskDb = make(dbMaker, dataStoreDef, false);

	}

**Comment by jankotek** [comment]
No idea where is the problem. If you disable transactions, store gets corrupted very easily.
