### ISSUE TITLE
java.lang.IndexOutOfBoundsException when trying to get object from mapdb

### ISSUE THREAD

**Issue by suyogkotecha** [jankotek/mapdb#625]
Hello there,
We at Yahoo, are using mapdb to store events and read them when the thread is idle. But we are getting following exception. We are unable to find out the real cause.
Any pointer would be useful.

Thanks,
Suyog

```
Nov 17, 2015 11:54:24 PM com.google.common.util.concurrent.ServiceManager$ServiceListener failed
SEVERE: Service AdsEventService [FAILED] has failed in the RUNNING state.
java.lang.IndexOutOfBoundsException
        at java.nio.Buffer.checkIndex(Buffer.java:540)
        at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:139)
        at org.mapdb.DataInput2.readUnsignedByte(DataInput2.java:74)
        at org.mapdb.DataInput2.read(DataInput2.java:136)
        at java.io.InputStream.read(InputStream.java:179)
        at java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2320)
        at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2333)
        at java.io.ObjectInputStream$BlockDataInputStream.readUTFBody(ObjectInputStream.java:3074)
        at java.io.ObjectInputStream$BlockDataInputStream.readUTF(ObjectInputStream.java:2874)
        at java.io.ObjectInputStream.readString(ObjectInputStream.java:1639)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1342)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
        at com.yahoo.ads.targeting.dot.action.SerializerActionState.deserialize(SerializerActionState.java:27)
        at com.yahoo.ads.targeting.dot.action.SerializerActionState.deserialize(SerializerActionState.java:14)
        at org.mapdb.Queues$SimpleQueue$NodeSerializer.deserialize(Queues.java:69)
        at org.mapdb.Queues$SimpleQueue$NodeSerializer.deserialize(Queues.java:52)
        at org.mapdb.Store.deserialize(Store.java:297)
        at org.mapdb.StoreDirect.get2(StoreDirect.java:486)
        at org.mapdb.StoreWAL.get2(StoreWAL.java:336)
        at org.mapdb.StoreWAL.get(StoreWAL.java:320)
        at org.mapdb.Caches$HashTable.get(Caches.java:246)
        at org.mapdb.Queues$SimpleQueue.poll(Queues.java:130)
        at com.yahoo.ads.targeting.dot.AdsEventService.processIntervalTasks(AdsEventService.java:243)
        at com.yahoo.ads.targeting.dot.AdsEventService.runOneIteration(AdsEventService.java:231)
        at com.yahoo.ads.targeting.dot.AdsEventService.run(AdsEventService.java:215)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
        at java.lang.Thread.run(Thread.java:745)

Exception in thread "AdsEventService" java.lang.IndexOutOfBoundsException
        at java.nio.Buffer.checkIndex(Buffer.java:540)
        at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:139)
        at org.mapdb.DataInput2.readUnsignedByte(DataInput2.java:74)
        at org.mapdb.DataInput2.read(DataInput2.java:136)
        at java.io.InputStream.read(InputStream.java:179)
        at java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2320)
        at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2333)
        at java.io.ObjectInputStream$BlockDataInputStream.readUTFBody(ObjectInputStream.java:3074)
        at java.io.ObjectInputStream$BlockDataInputStream.readUTF(ObjectInputStream.java:2874)
        at java.io.ObjectInputStream.readString(ObjectInputStream.java:1639)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1342)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
        at com.yahoo.ads.targeting.dot.action.SerializerActionState.deserialize(SerializerActionState.java:27)
        at com.yahoo.ads.targeting.dot.action.SerializerActionState.deserialize(SerializerActionState.java:14)
        at org.mapdb.Queues$SimpleQueue$NodeSerializer.deserialize(Queues.java:69)
        at org.mapdb.Queues$SimpleQueue$NodeSerializer.deserialize(Queues.java:52)
        at org.mapdb.Store.deserialize(Store.java:297)
        at org.mapdb.StoreDirect.get2(StoreDirect.java:486)
        at org.mapdb.StoreWAL.get2(StoreWAL.java:336)
        at org.mapdb.StoreWAL.get(StoreWAL.java:320)
        at org.mapdb.Caches$HashTable.get(Caches.java:246)
        at org.mapdb.Queues$SimpleQueue.poll(Queues.java:130)
        at com.yahoo.ads.targeting.dot.AdsEventService.processIntervalTasks(AdsEventService.java:243)
        at com.yahoo.ads.targeting.dot.AdsEventService.runOneIteration(AdsEventService.java:231)
        at com.yahoo.ads.targeting.dot.AdsEventService.run(AdsEventService.java:215)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by shabanovd** [comment]
What version in use?

**Comment by suyogkotecha** [comment]
We're using 1.0.8

On Wednesday, November 18, 2015, Dmitriy Shabanov <notifications@github.com>
wrote:

> What version in use?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jankotek/mapdb/issues/625#issuecomment-157641186>.
>


-- 
Thanks,
Suyog Kotecha,
Alumnus, University of Southern California
Alumnus, College of Engineering, Pune

**Comment by shabanovd** [comment]
Can it be a bug at your serializer?

**Comment by jankotek** [comment]
Hi, there could be two issues. First is possible data corruption. (are transactions enables?)

Other option is what I call 'unbounded serialization'. MapDB deserialization does not have a boundaries. Deserialization should read exactly the same number of bytes as serialization wrote. If deserialization expects something like EOF exception or -1, it will cause all sort of issues, including this. 

I think easiest solution is to upgrade to 2.0 which address most of this issues.

**Comment by suyogkotecha** [comment]
@jankotek 
We have transaction enabled. We have following serializer code. I am unable to catch issues with this.

public class SerializerActionState implements Serializer<ActionState>, Serializable {

    @Override
    public void serialize(DataOutput out, ActionState value) throws IOException {
        ObjectOutputStream objectStream = new ObjectOutputStream((OutputStream) out);
        objectStream.writeObject(value);
        objectStream.flush();
    }

    @Override
    public ActionState deserialize(DataInput in, int available) throws IOException {
        try {
            ObjectInputStream objectStream = new ObjectInputStream((InputStream) in);
            return (ActionState) objectStream.readObject();
        } catch (ClassNotFoundException e) {
            throw new IOException(e);
        }
    }

    @Override
    public int fixedSize() {
        return -1;
    }
}

**Comment by jankotek** [comment]
Does this bug happens if you enable compression? `DBMaker.compressionEnableI()`

**Comment by suyogkotecha** [comment]
We don't have it enabled.

On Sunday, November 29, 2015, Jan Kotek <notifications@github.com> wrote:

> Does this bug happens if you enable compression?
> DBMaker.compressionEnableI()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jankotek/mapdb/issues/625#issuecomment-160397274>.
>


-- 
Thanks,
Suyog Kotecha,
Alumnus, University of Southern California
Alumnus, College of Engineering, Pune

**Comment by jankotek** [comment]
Dont know how to fix this. Closing.
