### ISSUE TITLE
"WAL corrupted" on empty commit

### ISSUE THREAD

**Issue by catena2w** [jankotek/mapdb#634]
When I call db.commit() without any changes before db close, I get "WAL corrupted" error on next db load.
E.g. this code
``` scala
  emptyCommit(0)
  emptyCommit(1)

  def emptyCommit(run: Int): Unit = {
    println("run:" + run)
    val db =
      DBMaker.appendFileDB(new File("/tmp/scorex/testApp/segmentsStorage.mapDB"))
        .fileMmapEnableIfSupported()
        .closeOnJvmShutdown()
        .checksumEnable()
        .make()

    val map: HTreeMap[Long, AuthDataBlock[DataSegment]] = db.hashMapCreate("segments")
      .keySerializer(Serializer.LONG)
      .makeOrGet()

    for (i <- 1 to 10) {
      val value = AuthDataBlock(Random.nextString(4).getBytes, Seq())
      map.put(i, value)
      db.commit()
    }
    db.commit()
    db.close()
  }
```
will print something like 

```
run:0
run:1
Nov 23, 2015 6:57:53 PM org.mapdb.WriteAheadLog skipRollbacks
INFO: WAL corrupted, skipping
org.mapdb.DBException$DataCorruption: WAL corrupted 0 - 2245
	at org.mapdb.WriteAheadLog.skipRollbacks(WriteAheadLog.java:499)
	at org.mapdb.WriteAheadLog.replayWALSkipRollbacks(WriteAheadLog.java:448)
	at org.mapdb.WriteAheadLog.open(WriteAheadLog.java:347)
	at org.mapdb.StoreAppend.initOpen(StoreAppend.java:288)
	at org.mapdb.StoreAppend.init(StoreAppend.java:194)
	at org.mapdb.DBMaker$Maker.makeEngine(DBMaker.java:1504)
	at org.mapdb.DBMaker$Maker.make(DBMaker.java:1284)
```

**Comment by jankotek** [comment]
It is just warning in console, but I agree it should not be there
