### ISSUE TITLE
IndexOutOfBoundsException while accessing values of a map

### ISSUE THREAD

**Issue by ramv-dailymotion** [jankotek/mapdb#673]
Not sure why insert is being invoked when accessing the entries. This only happens when `cacheHardRefEnable()` is specified on the `HTreeMap<String, String[]>`

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 8241
	at org.mapdb.Store$LongObjectMap.insert(Store.java:1630)
	at org.mapdb.Store$LongObjectMap.put(Store.java:1594)
	at org.mapdb.Store$Cache$HardRef.put(Store.java:1180)
	at org.mapdb.Store.get(Store.java:255)
	at org.mapdb.Engine$ReadOnlyWrapper.get(Engine.java:367)
	at org.mapdb.Engine$CloseOnJVMShutdown.get(Engine.java:453)
	at org.mapdb.HTreeMap.getInner(HTreeMap.java:649)
```

## Test Case

```java

import org.junit.Test;
import org.mapdb.DB;
import org.mapdb.DBMaker;
import org.mapdb.HTreeMap;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Random;

public class TestMapDb {

    public String[] getRandomStringArray(){
        Random r = new Random();
        int size = r.ints(1, 20).iterator().nextInt();
        String[] strings = new String[size];
        for(int i=0; i<size; i++){
            strings[i] = "val-"+i;
        }
        return strings;
    }
    @Test
    public void testFailure() throws Exception{
        Path path = Files.createTempFile("test", "db");
        DB dbDisk = DBMaker
                .fileDB(path.toFile())
                .closeOnJvmShutdown()
                .make();
        HTreeMap<String, String[]> onDisk = dbDisk
                .hashMapCreate("onDisk")
                .counterEnable()
                .make();

        for(int i=0; i<100000; i++){
            onDisk.put("key-"+i, getRandomStringArray());
        }
        dbDisk.commit();
        onDisk.close();
        dbDisk.close();
        DB dbDisk2 = DBMaker
                .fileDB(path.toFile())
                .closeOnJvmShutdown()
                .transactionDisable()
                .fileMmapEnable()
                .readOnly()
                // diabling locks because this file is read only
                .lockDisable()
                .cacheHardRefEnable()
                .make();
        HTreeMap<String, String[]> onDisk2 = dbDisk2
                .hashMapCreate("onDisk")
                .counterEnable()
                .makeOrGet();
        onDisk2.entrySet().parallelStream().forEach(entry -> {
            System.out.println(String.format("%s: val size: %d", entry.getKey(), entry.getValue().length));
        });
    }
}
```

```stacktrace

java.lang.ArrayIndexOutOfBoundsException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at com.dailymotion.rc.common.model.test.TestMapDb.testFailure(TestMapDb.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 8241
	at org.mapdb.Store$LongObjectMap.insert(Store.java:1630)
	at org.mapdb.Store$LongObjectMap.put(Store.java:1594)
	at org.mapdb.Store$Cache$HardRef.put(Store.java:1180)
	at org.mapdb.Store.get(Store.java:255)
	at org.mapdb.Engine$ReadOnlyWrapper.get(Engine.java:367)
	at org.mapdb.Engine$CloseOnJVMShutdown.get(Engine.java:453)
	at org.mapdb.HTreeMap.getInner(HTreeMap.java:649)
	at org.mapdb.HTreeMap.get(HTreeMap.java:583)
	at org.mapdb.HTreeMap$Entry2.getValue(HTreeMap.java:1648)
	at com.dailymotion.rc.common.model.test.TestMapDb.lambda$testFailure$0(TestMapDb.java:57)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by jankotek** [comment]
Problem is with `lockDisable()` option. It makes the store thread unsafe, and cache expect thread safe store. Not going to fix.
