### ISSUE TITLE
IndexOutOfBoundsException while db.commit

### ISSUE THREAD

**Issue by pozharko** [jankotek/mapdb#674]
I have plenty of IndexOutOfBoundsException errors on db.commit:
```
java.lang.IndexOutOfBoundsException
	at org.mapdb.Volume.hash(Volume.java:459)
	at org.mapdb.WriteAheadLog.checksum(WriteAheadLog.java:180)
	at org.mapdb.WriteAheadLog.commit(WriteAheadLog.java:167)
	at org.mapdb.StoreWAL.commit(StoreWAL.java:653)
	at org.mapdb.Engine$CloseOnJVMShutdown.commit(Engine.java:487)
	at org.mapdb.DB.commit(DB.java:2647)
```

or on DBMaker.make

```
java.lang.IndexOutOfBoundsException
	at org.mapdb.Volume.hash(Volume.java:459)
	at org.mapdb.WriteAheadLog.checksum(WriteAheadLog.java:180)
	at org.mapdb.WriteAheadLog.commit(WriteAheadLog.java:167)
	at org.mapdb.StoreWAL.commit(StoreWAL.java:653)
	at org.mapdb.Engine$CloseOnJVMShutdown.commit(Engine.java:487)
	at org.mapdb.BTreeMap.preinitCatalog(BTreeMap.java:183)
	at org.mapdb.DB.reinit(DB.java:253)
	at org.mapdb.DB.<init>(DB.java:220)
	at org.mapdb.DBMaker$Maker.make(DBMaker.java:1297)
```

Code, that creates DB is: 

   ```
   DBMaker.fileDB(new File(fileName))
        .closeOnJvmShutdown()
        .cacheSize(2048)
        .checksumEnable()
        .fileMmapEnable()
        .make()
```

**Comment by jankotek** [comment]
So far I could not replicate the issue. StackTrace indicates that commit log file is smaller than it should be. 

What type of data are you adding into MapDB? What is average size of keys and values? What are  map settings (hashmap/treemap, serializers..)?

**Comment by jankotek** [comment]
Could not replicate
