### ISSUE TITLE
ArrayIndexOutOfBoundsException in BTreeMap.put

### ISSUE THREAD

**Issue by iluxo** [jankotek/mapdb#676]
I got this exception in server log.

```
java.lang.ArrayIndexOutOfBoundsException: -5938
        at org.mapdb.CompressLZF.expand(CompressLZF.java:390)
        at org.mapdb.Store.deserialize(Store.java:287)
        at org.mapdb.StoreWAL.get2(StoreWAL.java:345)
        at org.mapdb.StoreWAL.get(StoreWAL.java:320)
        at org.mapdb.Caches$HashTable.get(Caches.java:246)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
        at org.mapdb.BTreeMap.put2(BTreeMap.java:663)
        at org.mapdb.BTreeMap.put(BTreeMap.java:643)
```

What can be the cause? Can't reproduce locally so far.

Version 1.0.7.
DB creation code:
```

DBMaker.newFileDB(<file>).compressionEnable().closeOnJvmShutdown().cacheSize(1000000).make();
```

**Comment by jankotek** [comment]
No idea.

**Comment by iluxo** [comment]
Ok, sorry :)
