### ISSUE TITLE
3.0.0-M3: org.mapdb.DBException$WrongConfiguration: Store does not support Reserved Recids: class org.mapdb.StoreDirect

### ISSUE THREAD

**Issue by omar391** [jankotek/mapdb#680]
I don't understand what this "WrongConfiguration" mean. However, as issues suggest, this should have fixed in db-3 milestone 3. My usage is as follows-

db = DBMaker.fileDB(dbName).make(); //this line throws err
map = db.hashMap(storeName).createOrOpen();
map.put("...")

any suggestion? I am just in darkness on how should I start with this lib.

My system: win 10-64 bit, Idea ide.

**Comment by jankotek** [comment]
Stack trace?

**Comment by apowney** [comment]
I also get this problem with 3.0.0-M3. 

`	public void testReopenExistingFile() {
		for( int i = 0 ; i < 2 ; i++ ) {
			DB db = DBMaker.fileDB( "test.db" ).make();
			db.close();
		}
	}
`
Stack-trace:

org.mapdb.DBException$WrongConfiguration: Store does not support Reserved Recids: class org.mapdb.StoreDirect
	at org.mapdb.DB.<init>(DB.kt:104)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:100)
	at org.mapdb.test.issues.Issue680TestCase.testReopenExistingFile(Issue680TestCase.java:32)

Isn't this the same as issue #672?

**Comment by omar391** [comment]
For me, my stacks are:

Exception in thread "Thread-1" org.mapdb.DBException$WrongConfiguration: Store does not support Reserved Recids: class org.mapdb.StoreDirect
	at org.mapdb.DB.<init>(DB.kt:104)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:100)

**Comment by sargunster** [comment]
I'm also getting this problem in my project https://github.com/pokesource/ditto when I reopen the database after closing.
```
Exception in thread "main" org.mapdb.DBException$WrongConfiguration: Store does not support Reserved Recids: class org.mapdb.StoreDirect
	at org.mapdb.DB.<init>(DB.kt:104)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:100)
	at com.github.pokesource.ditto.data.Cache.<init>(Cache.kt:15)
	at com.github.pokesource.ditto.MainKt.startServices(Main.kt:87)
	at com.github.pokesource.ditto.MainKt.main(Main.kt:17)
```

**Comment by dkornishev** [comment]
same here (M3).  Is there a work-around?
```
Exception in thread "main" org.mapdb.DBException$WrongConfiguration: Store does not support Reserved Recids: class org.mapdb.StoreDirect
	at org.mapdb.DB.<init>(DB.kt:104)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:100)
	at com.aetherworks.skunkworks.mapdb.MapDbPrototype.main(MapDbPrototype.java:23)
```

**Comment by cy6erGn0m** [comment]
In fact I have the same both with M2 and M3. It just can't open existing database

**Comment by jankotek** [comment]
Fixed. M4 will be out in a few days.
