### ISSUE TITLE
Random java.lang.RuntimeException:Writer thread failed exception

### ISSUE THREAD

**Issue by jerdeb** [jankotek/mapdb#692]
I am currently having a problem with MapDB v 1.0.9. I am having the following exception being thrown randomly:

`java.lang.RuntimeException: Writer thread failed
	at org.mapdb.AsyncWriteEngine.checkState(AsyncWriteEngine.java:262)
	at org.mapdb.AsyncWriteEngine.get(AsyncWriteEngine.java:326)
	at org.mapdb.Caches$HashTable.get(Caches.java:246)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.HTreeMap.putInner(HTreeMap.java:500)
	at org.mapdb.HTreeMap.put(HTreeMap.java:488)
	at eu.diachron.qualitymetrics.intrinsic.consistency.EstimatedUsageOfIncorrectDomainOrRangeDatatypes.compute(EstimatedUsageOfIncorrectDomainOrRangeDatatypes.java:83)
	at de.unibonn.iai.eis.luzzu.io.impl.StreamProcessor$MetricProcess$1.run(StreamProcessor.java:545)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
	at java.util.HashMap$KeyIterator.next(HashMap.java:956)
	at org.mapdb.SerializerBase.serializeCollection(SerializerBase.java:829)
	at org.mapdb.SerializerBase.serialize2(SerializerBase.java:364)
	at org.mapdb.SerializerBase.serialize(SerializerBase.java:150)
	at org.mapdb.SerializerBase.serialize(SerializerBase.java:94)
	at org.mapdb.SerializerPojo.serialize(SerializerPojo.java:696)
	at org.mapdb.HTreeMap$2.serialize(HTreeMap.java:129)
	at org.mapdb.HTreeMap$2.serialize(HTreeMap.java:121)
	at org.mapdb.Store.serialize(Store.java:154)
	at org.mapdb.StoreDirect.update(StoreDirect.java:495)
	at org.mapdb.EngineWrapper.update(EngineWrapper.java:63)
	at org.mapdb.AsyncWriteEngine.access$101(AsyncWriteEngine.java:76)
	at org.mapdb.AsyncWriteEngine.runWriter(AsyncWriteEngine.java:220)
	at org.mapdb.AsyncWriteEngine$WriterRunnable.run(AsyncWriteEngine.java:172)
	at java.lang.Thread.run(Thread.java:745)
`

I tried to debug and replicate the problem but it seems that this happens when I am trying to insert over 20M entries in the HTreeMap. Furthermore, this method is used within a multi-threading environment.

I initialised MapDB as follows:
`		DB mapDB = DBMaker.newFileDB(new File(mapDbDir + "mapasyncdb-" + timestamp)).closeOnJvmShutdown().deleteFilesAfterClose().transactionDisable().mmapFileEnable().asyncWriteFlushDelay(2000).asyncWriteEnable().make(); `

I create an HTreeMap as follows:
`	public static <T> Set<T> createHashSet(DB mapDBFile, String name){
		Set<T> _hashSet = null;
		synchronized (mapDBFile) {
			_hashSet = mapDBFile.createHashSet(name).make();
		}
		return _hashSet;
	} `

Could you please tell me what the problem could be?

For more information these are the two classes causing this problem:
(1) https://github.com/diachron/quality/blob/master/lod-qualitymetrics/lod-qualitymetrics-intrinsic/src/main/java/eu/diachron/qualitymetrics/intrinsic/consistency/EstimatedUsageOfIncorrectDomainOrRangeDatatypes.java
(2) https://github.com/diachron/quality/blob/master/lod-qualitymetrics/lod-qualitymetrics-intrinsic/src/main/java/eu/diachron/qualitymetrics/intrinsic/consistency/AdvancedEntitiesAsMembersOfDisjointClasses.java

The factory class handling MapDB:
https://github.com/diachron/quality/blob/master/metric-utilities/src/main/java/de/unibonn/iai/eis/diachron/mapdb/MapDbFactory.java

Cheers,
Jeremy

**Comment by jankotek** [comment]
I would recommend to disable async write. 

My bet this cause a problem

	protected HTreeMap<String, Set<String>> typesOfResource = MapDbFactory.createHashMap(mapDb, UUID.randomUUID().toString());
	
HashSet value is not thread safe. If its deserialized on background thread it fails. Also MapDB requires values to be immutable and this is not.
