### ISSUE TITLE
why the error happened?

### ISSUE THREAD

**Issue by zhouyibing** [jankotek/mapdb#702]
My idea is IntelliJ IDEA 14.1.4. 
The mapdb version is 3.0.0-beta2
Caused by: java.lang.NoClassDefFoundError: org/eclipse/collections/impl/list/mutable/primitive/LongArrayList
	at org.mapdb.StoreDirectAbstract.<init>(StoreDirectAbstract.kt:37)
	at org.mapdb.StoreDirect.<init>(StoreDirect.kt:27)
	at org.mapdb.StoreDirect$Companion.make(StoreDirect.kt:51)
	at org.mapdb.StoreDirect$Companion.make$default(StoreDirect.kt:50)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:405)

How to solve this problem?

**Comment by jankotek** [comment]
You need Eclipse Collections in 
your classpath. MapDB now 
depends on external libraries.
