### ISSUE TITLE
ArrayIndexOutOfBoundsException on BTreeMap.put

### ISSUE THREAD

**Issue by shabanovd** [jankotek/mapdb#707]
Mapdb version 3.0.0-beta3, single thread put and remove operations
```
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at org.mapdb.DataIO.arrayPut(DataIO.java:531)
	at org.mapdb.serializer.GroupSerializerObjectArray.valueArrayPut(GroupSerializerObjectArray.java:44)
	at org.mapdb.serializer.GroupSerializerObjectArray.valueArrayPut(GroupSerializerObjectArray.java:14)
	at org.mapdb.BTreeMap.copyAddKeyLeaf(BTreeMap.kt:625)
	at org.mapdb.BTreeMap.put2(BTreeMap.kt:385)
	at org.mapdb.BTreeMap.put(BTreeMap.kt:293)
```

**Comment by zhouyibing** [comment]
I also appear this problem

java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at org.mapdb.serializer.SerializerEightByte.valueArrayPut(SerializerEightByte.java:38)
	at org.mapdb.BTreeMap.copyAddKeyLeaf(BTreeMap.kt:625)
	at org.mapdb.BTreeMap.put2(BTreeMap.kt:385)
	at org.mapdb.BTreeMap.putIfAbsent(BTreeMap.kt:843)

**Comment by shabanovd** [comment]
@jankotek it fail because pos is -1, it calculated [here](https://github.com/jankotek/mapdb/blob/master/src/main/java/org/mapdb/BTreeMap.kt#L620)
