### ISSUE TITLE
org.mapdb.DBException$DataCorruption: after db-crash

### ISSUE THREAD

**Issue by rehm** [jankotek/mapdb#714]
Hi, i use mapDB for a huge import task. After some random time the import abort with: 

```
mapdb Error in `java': malloc(): smallbin double linked list corrupted
```

Re-Open the db - throw:

```
Exception in thread "main" org.mapdb.DBException$DataCorruption: Header checksum broken. Store was not closed correctly and might be corrupted. Use `DBMaker.checksumHeaderBypass()` to recover your data. Use clean shutdown or enable transactions to protect the store in the future.
        at org.mapdb.StoreDirectAbstract.fileHeaderCheck(StoreDirectAbstract.kt:109)
        at org.mapdb.StoreDirect.<init>(StoreDirect.kt:100)
        at org.mapdb.StoreDirect$Companion.make(StoreDirect.kt:53)
        at org.mapdb.StoreDirect$Companion.make$default(StoreDirect.kt:52)
        at org.mapdb.DBMaker$Maker.make(DBMaker.kt:415)
        at org.hucompute.galaxy.Galaxy.<init>(Galaxy.java:39)
        at org.hucompute.galaxy.Galaxy.main(Galaxy.java:154)

```

any idea, how to debug this? 

best wishes

**Comment by jankotek** [comment]
That original error looks strange. Looks like JVM error. Will investigate

Second error is caused by data corruption.

**Comment by jankotek** [comment]
The original error message refers to memory corruption. MapDBB wrote to address it should not. Current version does not use Unsafe and it should not happen in theory. 

Would you post more details (DBMaker config), how import works etc. 

Also can you replicate the issue? Or did it happen only once?
