### ISSUE TITLE
Application hangs with latest version of mapdb 3.0.0-M6

### ISSUE THREAD

**Issue by amitvc** [jankotek/mapdb#717]
Simple application using following dependency hangs up in classloader. The dependency is below --
<dependency>
      <groupId>org.mapdb</groupId>
      <artifactId>mapdb</artifactId>
      <version>3.0.0-M6</version>
</dependency>
The sample code is below -
DB db = DBMaker.fileDB("file.db")
				// TODO memory mapped files enable here
				.make();
		ConcurrentMap<String, String> map = db.hashMap("map", Serializer.STRING, Serializer.STRING).make();
		for(int i=0; i < 100; i++) {
			String id = UUID.randomUUID().toString();
			map.put(id, id+(i*10));
			System.out.println("Writing");
		}
		db.close();

There are no exceptions or anything thrown either. I am running this in eclipse.

**Comment by shabanovd** [comment]
Latest version is 3.0.0-beta5

@jankotek maven-badge point to wrong version that lead to confusion.

**Comment by amitvc** [comment]
I will try that version and post feedback.

**Comment by amitvc** [comment]
Still the same problem.

**Comment by shabanovd** [comment]
Can you get stacktrace?

**Comment by jankotek** [comment]
Could not replicate  so far. Is database file new, or does it contain data from previous version? Also code above does not use class loader.

**Comment by amitvc** [comment]
If I comment out the code as below - I get the Hello World print statement.
System.out.println("Hello World!");
		/*DB db = DBMaker.fileDB("file.db").make();
		ConcurrentMap<String, String> map = db.hashMap("map", Serializer.STRING, Serializer.STRING).make();
		for(int i=0; i < 100; i++) {
			String id = UUID.randomUUID().toString();
			map.put(id, id+(i*10));
			System.out.println("Writing");
		}
		db.close();
*/

**Comment by amitvc** [comment]
Here is the stack trace --
Thread [main] (Suspended (exception UnsupportedClassVersionError))	
	Launcher$AppClassLoader(ClassLoader).loadClass(String, boolean) line: 437	
	Launcher$AppClassLoader.loadClass(String, boolean) line: 308	
	Launcher$AppClassLoader(ClassLoader).loadClass(String) line: 358	
	Class<T>.getDeclaredMethods0(boolean) line: not available [native method]	
	Class<T>.privateGetDeclaredMethods(boolean) line: 2615	
	Class<T>.getMethod0(String, Class<?>[]) line: 2856	
	Class<T>.getMethod(String, Class<?>...) line: 1668	
	LauncherHelper.getMainMethod(PrintStream, Class<?>) line: 494	
	LauncherHelper.checkAndLoadMain(boolean, int, String) line: 486

**Comment by amitvc** [comment]
And this is brand new database.

**Comment by amitvc** [comment]
Could it be version of java problem ?

**Comment by amitvc** [comment]
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/mapdb/Serializer : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.getMainMethod(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Sour

**Comment by shabanovd** [comment]
what java version do you use?

**Comment by amitvc** [comment]
1.7.0_79.

**Comment by shabanovd** [comment]
last mapdb require java 1.8

**Comment by amitvc** [comment]
Ok. I'll update and retest.

**Comment by amitvc** [comment]
This has been resolved. Thanks for all your help.
