### ISSUE TITLE
I get NoClassDefFoundError. Please help. 

### ISSUE THREAD

**Issue by roohitavaf** [jankotek/mapdb#727]
Hello, 
I have started using MapDB. Fist of all I don't know the documentation provided in the website works for which version? 

I used mapdb-RC1.jar. I added it to the Eclipse Referenced Library as an external jar and used the code provided in the get started, but I get the following error: 

Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/NoWhenBranchMatchedException
	at org.mapdb.DBMaker.memoryDB(DBMaker.kt:71)
	at Test.main(Test.java:13)
Caused by: java.lang.ClassNotFoundException: kotlin.NoWhenBranchMatchedException
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

**Comment by lkolek** [comment]
try to use maven or gradle. That way you'll get all dependencies needed.

**Comment by jankotek** [comment]
MapDB depends on external libraries, full list of dependencies is here:
http://mvnrepository.com/artifact/org.mapdb/mapdb/3.0.0-RC1
