### ISSUE TITLE
ArrayIndexOutOfBounds on IndexTreeList.add

### ISSUE THREAD

**Issue by riversidetraveler** [jankotek/mapdb#730]
I'm currently running into an ArrayIndexOutOfBounds adding tens of thousands of elements to a tempFileDb backed IndexTreeList:

```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at org.mapdb.DataOutput2.write(DataOutput2.java:65)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1189)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.mapdb.elsa.ElsaSerializerPojo.serializeUnknownObject(ElsaSerializerPojo.java:474)
	at org.mapdb.elsa.ElsaSerializerBase.serialize(ElsaSerializerBase.java:1093)
	at org.mapdb.elsa.ElsaSerializerBase.serialize(ElsaSerializerBase.java:1026)
	at org.mapdb.DB$defaultSerializer$1.serialize(DB.kt:225)
	at org.mapdb.StoreDirectAbstract.serialize(StoreDirectAbstract.kt:240)
	at org.mapdb.StoreDirect.put(StoreDirect.kt:586)
	at org.mapdb.IndexTreeList.add(IndexTreeList.kt:24)
```

The setup for the list is fairly simple:

```java
DB db = DBMaker.tempFileDB().closeOnJvmShutdown().make();
IndexTreeList resultTarget = db
                       .indexTreeList(UUID.randomUUID().toString())
                       .create();
```

and from there I just call `resultTarget.add(item)`

I'm using the `tempFileDB` as a way of getting list elements out of memory and onto disk in a heap constrained environment. My tests currently run with  `-Xmx512m`. 

The items I'm adding are `<Map<String, Object>>` with exactly 26 map entries and an average serialized size of 1855 bytes. 

I'm running 3.0 RC1.

**Comment by jankotek** [comment]
What version are you using?##SELECTION_END##

**Comment by riversidetraveler** [comment]
Just edited the description-- I'm using 3.0 RC1:

```xml
        <dependency>
            <groupId>org.mapdb</groupId>
            <artifactId>mapdb</artifactId>
            <version>3.0.0-RC1</version>
        </dependency>
```

**Comment by jankotek** [comment]
Another question: Is the map modified after it was inserted into Index List? MapDB requires entries to be immutable, if new entry is inserted to map, it could cause similar issue.

**Comment by riversidetraveler** [comment]
The map is not modified. I'm going to do some work on this code today and will build a test that isolates the activity to just loading the IndexTreeList with the Map<String, Object> elements. If the issue is reproducible in isolation I'll share the test with you.

**Comment by riversidetraveler** [comment]
I put together a [gist](https://gist.github.com/riversidetraveler/61645ae7094876d92281d01c14b85803) with a set of steps roughly analogous to the code that was running when the stack trace above was thrown. I was NOT able to reproduce the issue however. I've successfully tested down to a heap constrained to 8m. The test leads me to believe that the issue lies elsewhere and MapDB's tempFileDB is doing the right thing and getting the data out of memory and onto disk.
