### ISSUE TITLE
BtreeMap not working for custom pojo

### ISSUE THREAD

**Issue by shankyty** [jankotek/mapdb#744]
public interface SomeInterface extends Serializable {
   getter1();
   getter2();
}

public class DataPojo {
      enumType var1;
      int var2;
}

private NavigableMap<Long, DataPojo> dataMap = DBMaker.memoryDB().make().treeMap("dataMap", Serializer.LONG, Serializer.JAVA).create();

for(DataPojo row : list) {
      dataMap.put(row.getStartIp(), row);
    }

gives

org.mapdb.DBException$SerializationError
	at org.mapdb.StoreDirectAbstract.serialize(StoreDirectAbstract.kt:243)
	at org.mapdb.StoreDirect.update(StoreDirect.kt:626)
	at org.mapdb.BTreeMap.put2(BTreeMap.kt:389)
	at org.mapdb.BTreeMap.put(BTreeMap.kt:292)
        ...
Caused by: java.io.NotSerializableException: my.package
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.mapdb.serializer.SerializerJava.valueArraySerialize(SerializerJava.java:50)
	at org.mapdb.BTreeMapJava$NodeSerializer.serialize(BTreeMapJava.java:171)
	at org.mapdb.BTreeMapJava$NodeSerializer.serialize(BTreeMapJava.java:136)
	at org.mapdb.StoreDirectAbstract.serialize(StoreDirectAbstract.kt:240)
	... 36 more

**Comment by shankyty** [comment]
Not sure why it was not working at that time but now it is working fine thanks
