### ISSUE TITLE
org.mapdb.DBException$VolumeIOError on commit()

### ISSUE THREAD

**Issue by scauwe** [jankotek/mapdb#746]
Hi all,

I was trying out mapdb with a simple test. When I run the following code once, it works. The second time (without deleting te database file), I get an exception:
```
Exception in thread "main" org.mapdb.DBException$VolumeIOError
	at org.mapdb.volume.RandomAccessFileVol.putData(RandomAccessFileVol.java:141)
	at org.mapdb.StoreWAL$commit$4.value(StoreWAL.kt:624)
	at org.eclipse.collections.impl.map.mutable.primitive.LongLongHashMap.forEachKeyValue(LongLongHashMap.java:988)
	at org.mapdb.StoreWAL.commit(StoreWAL.kt:622)
	at org.mapdb.DB.commit(DB.kt:435)
	at info.vancauwenberge.idm.driver.txtprotocol.util.StateFile.main(StateFile.java:33)
Caused by: java.io.IOException: The parameter is incorrect
	at java.io.RandomAccessFile.writeBytes(Native Method)
	at java.io.RandomAccessFile.write(RandomAccessFile.java:525)
	at org.mapdb.volume.RandomAccessFileVol.putData(RandomAccessFileVol.java:139)
	... 5 more
```
Version: 3.0.0 (maven).

Code:
```
		System.out.println("Opening Db");
		DB db = DBMaker
				.fileDB(new File("C:\\Temp\\mapdb"))
				.closeOnJvmShutdown()
				.transactionEnable()
				.make();
		HTreeMap map = db
				.hashMap("map")
				.keySerializer(Serializer.STRING)
				.valueSerializer(Serializer.JAVA)
				.createOrOpen();
		//Putting data in
		System.out.println("Storing data");
		map.put("something", "here");
		for (int i = 0; i < 100; i++) {
			map.put(""+i, "value-a"+i);
		}
		System.out.println("Commiting transaction");
		db.commit();  //Here I get the stacktrace the second time.
		System.out.println("Loading data");
		for (int i = 0; i < 100; i++) {
			System.out.println(map.get(""+i));
		}
		System.out.println(map.get("something"));
		System.out.println("Clearing data");
		map.clear();
		System.out.println("Commiting transaction");
		db.commit();
		System.out.println("Loading data");
		for (int i = 0; i < 1000; i++) {
			System.out.println(map.get(""+i));
		}
		System.out.println(map.get("something"));
		System.out.println("Done");
```

**Comment by scauwe** [comment]
Note: If I remove .transactionEnable(), I can run the code multiple times.
