### ISSUE TITLE
Problem with delete

### ISSUE THREAD

**Issue by Miger88** [jankotek/mapdb#751]
Hello
I  am trying to use the mapDB for a small test. Therefore I need to add some data to the db and delete it. Adding Data works just fine.  I can do this multiple times without errors.

Delete the Hashmap works fine too, but only one time. 

If I then try again to add data everything is fine. But the second call of my delete Method gives then the following Error:

FATAL EXCEPTION: main
                                                                                               Process: com.example.michael.dbmanager_debug_application, PID: 4902
                                                                                               java.lang.InternalError: data were not fully read, check your serializer 
                                                                                                   at org.mapdb.Store.deserialize(Store.java:265)
                                                                                                   at org.mapdb.StoreDirect.get2(StoreDirect.java:431)
                                                                                                   at org.mapdb.StoreWAL.get2(StoreWAL.java:318)
                                                                                                   at org.mapdb.StoreWAL.get(StoreWAL.java:302)
                                                                                                   at org.mapdb.EngineWrapper.get(EngineWrapper.java:60)
                                                                                                   at org.mapdb.AsyncWriteEngine.get(AsyncWriteEngine.java:361)
                                                                                                   at org.mapdb.Caches$HashTable.get(Caches.java:213)
                                                                                                   at org.mapdb.HTreeMap.recursiveDirClear(HTreeMap.java:734)
                                                                                                   at org.mapdb.HTreeMap.recursiveDirClear(HTreeMap.java:728)
                                                                                                   at org.mapdb.HTreeMap.recursiveDirClear(HTreeMap.java:728)
                                                                                                   at org.mapdb.HTreeMap.recursiveDirClear(HTreeMap.java:728)
                                                                                                   at org.mapdb.HTreeMap.clear(HTreeMap.java:704)
                                                                                                   at org.mapdb.DB.delete(DB.java:1135)

For add i Use the following
```
map = db.createHashMap("NAME").make();
        for(int i = 1; i <= dataarray.getSize(); i++){
            map.put("timestamp" + (oldSize + i), "" + dataarray.getZeitstempel(i-1));
            map.put("header" + (oldSize + i), "" + dataarray.getHeader(i-1));
            map.put("data" + (oldSize + i), "" + dataarray.getData(i-1));
            fahrtxmap.put("size", "" + (oldSize + dataarray.getSize()));
```
For delete I use  `db.delete("NAME")`.

Can you help me to find my mistake?

**Comment by jankotek** [comment]
Sorry 1.0 and 2.0 is not supported anymore
