### ISSUE TITLE
IndexOutOfBoundsException mapdb

### ISSUE THREAD

**Issue by manishpujari84** [jankotek/mapdb#770]
I am getting below exception only on unix machine.

```
DB db=DBMaker
                .fileDB(new File("/opt/home/mydir/opendacs.db")).closeOnJvmShutdown().fileMmapEnable().make();
```

```
java.lang.IndexOutOfBoundsException: null
    at java.nio.Buffer.checkIndex(Buffer.java:540) ~[na:1.8.0_71]
    at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253) ~[na:1.8.0_71]
    at org.mapdb.DataInput2$ByteBuffer.unpackInt(DataInput2.java:389) ~[mapdb-3.0.1.jar:na]
    at org.mapdb.DataInput2.readUTF(DataInput2.java:491) ~[mapdb-3.0.1.jar:na]
    at org.mapdb.DB$Companion$NAME_CATALOG_SERIALIZER$1.deserialize(DB.kt:51) ~[mapdb-3.0.1.jar:na]
    at org.mapdb.DB$Companion$NAME_CATALOG_SERIALIZER$1.deserialize(DB.kt:45) ~[mapdb-3.0.1.jar:na]
    at org.mapdb.StoreDirectAbstract.deserialize(StoreDirectAbstract.kt:226) ~[mapdb-3.0.1.jar:na]
    at org.mapdb.StoreDirect.get(StoreDirect.kt:543) ~[mapdb-3.0.1.jar:na]
    at org.mapdb.DB.nameCatalogLoadLocked(DB.kt:350) ~[mapdb-3.0.1.jar:na]
    at org.mapdb.DB.nameCatalogLoad(DB.kt:343) ~[mapdb-3.0.1.jar:na]
    at org.mapdb.DB.nameCatalogVerifyGetMessages(DB.kt:1839) ~[mapdb-3.0.1.jar:na]
    at org.mapdb.DB.<init>(DB.kt:272) ~[mapdb-3.0.1.jar:na]
    at org.mapdb.DB.<init>(DB.kt:40) ~[mapdb-3.0.1.jar:na]
    at org.mapdb.DBMaker$Maker.make(DBMaker.kt:477) ~[mapdb-3.0.1.jar:na]
```

**Comment by jankotek** [comment]
hi, could you try with 3.0.2 release?
