### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by lichengwu** [jankotek/mapdb#773]
> java.lang.ArrayIndexOutOfBoundsException: 71

```
at org.mapdb.HTreeMap$leafValueExternalSerializer$1.deserialize(HTreeMap.kt:230)
at org.mapdb.HTreeMap$leafValueExternalSerializer$1.deserialize(HTreeMap.kt:214)
at org.mapdb.StoreDirectAbstract.deserialize(StoreDirectAbstract.kt:229)
at org.mapdb.StoreDirect.get(StoreDirect.kt:546)
at org.mapdb.HTreeMap.leafGet(HTreeMap.kt:1372)
at org.mapdb.HTreeMap$sizeLong$$inlined$lockRead$lambda$1.value(HTreeMap.kt:713)
at org.mapdb.IndexTreeLongLongMap$forEachKeyValue$1.visit(IndexTreeLongLongMap.kt:447)
at org.mapdb.IndexTreeLongLongMap$forEachKeyValue$1.visit(IndexTreeLongLongMap.kt:44)
at org.mapdb.IndexTreeListJava.treeFold(IndexTreeListJava.java:606)
at org.mapdb.IndexTreeListJava.treeFold(IndexTreeListJava.java:604)
at org.mapdb.IndexTreeListJava.treeFold(IndexTreeListJava.java:604)
at org.mapdb.IndexTreeListJava.treeFold(IndexTreeListJava.java:604)
at org.mapdb.IndexTreeListJava.treeFold(IndexTreeListJava.java:604)
at org.mapdb.IndexTreeLongLongMap.forEachKeyValue(IndexTreeLongLongMap.kt:446)
at org.mapdb.HTreeMap.sizeLong(HTreeMap.kt:712)
at org.mapdb.HTreeMap.getSize(HTreeMap.kt:701)
at org.mapdb.HTreeMap.size(HTreeMap.kt:18)
```

**Comment by lichengwu** [comment]
Is the db file broken?

**Comment by cthumuluru** [comment]
@jankotek  was there a fix for this issue? I'm also seeing the same issue.
