### ISSUE TITLE
AssertionError at org.mapdb.HTreeMap.expireEvictEntry(HTreeMap.kt:913)

### ISSUE THREAD

**Issue by the-magical-llamicorn** [jankotek/mapdb#777]
My Code:

<pre>
//Creating the db
dataBase = DBMaker
                .fileDB(file + "/store.db")
                .allocateStartSize(allocatedSize) // 12GB
                .allocateIncrement(allocateIncrement) //1GB
                .fileMmapEnableIfSupported()
                .fileMmapPreclearDisable()
                .make();
        indexed = dataBase
                .hashSet("Indexed")
                .serializer(Serializer.STRING_ASCII)
                .expireAfterCreate(reindexTime) // 10 Days
                .layout(16, 16, 7)
                .createOrOpen();
        stack = dataBase
                .indexTreeList("Stack", Serializer.STRING_ASCII)
                .layout(16, 8)
                .createOrOpen();
        dataBase.checkThreadSafe();

// this method is called concurrently to itself and get()
public void accept(final String s) {
        if (indexed.contains(s)) return;
        else {
            indexed.add(s);
            stack.add(s);
        }
    }

// this method is called concurrently to itself and accept(String)
public String get() { // may be more performant to catch the extremely rare "IndexOutOfBounds"
                                  // than to synchronize
            if (! stack.isEmpty()) return stack.remove(stack.size()-1);
            else return null;
    }
</pre>

"Indexed" is a record
a unique String should not be added to "stack" if it as already been added within the "reindexTime"

After running for a couple of minutes, I get:
<pre>
java.lang.AssertionError
	at org.mapdb.HTreeMap.expireEvictEntry(HTreeMap.kt:913)
	at org.mapdb.HTreeMap$expireEvictSegment$1.take(HTreeMap.kt:881)
	at org.mapdb.QueueLong.takeUntil(QueueLong.kt:153)
	at org.mapdb.HTreeMap.expireEvictSegment(HTreeMap.kt:859)
	at org.mapdb.HTreeMap.put(HTreeMap.kt:322)
	at org.mapdb.HTreeMap$KeySet.add(HTreeMap.kt:988)
</pre>

**Comment by the-magical-llamicorn** [comment]
What is going on
