### ISSUE TITLE
Deadlock during Expiration

### ISSUE THREAD

**Issue by marklonsdale** [jankotek/mapdb#781]
Are there any known issues with deadlocks occurring during expiration with HashMap, with version 3.0.2 ?

We create our DB using the following declarations

	db = DBMaker.fileDB(file)
				.fileMmapEnable()
				.fileMmapPreclearDisable()
				.cleanerHackEnable()
				.transactionEnable()
				.make();

        ScheduledExecutorService executor=Executors.newScheduledThreadPool(2);

        dbMap=db.hashMap(STELLUS_REPORT_STORE) 
    				.expireAfterCreate(2, TimeUnit.MINUTES)
    				.expireExecutor(executor)
    				.expireExecutorPeriod(60000)
    				.counterEnable()
    				.createOrOpen();

Everything seems to hang when doing a 'commit' on the db following a 'put',  if expiration is in progress. 

Stack trace for the 3 threads can be seen below
```
1 - OS Monitor Thread doing db.commit()

"OSMonitor" #31 prio=5 os_prio=0 tid=0x00007f758435d800 nid=0xc534 waiting on condition [0x00007f75ecb8d000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000f00f8318> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:943)
        at org.mapdb.Utils$SingleEntryReadWriteLock$newWriteLock$1.lock(Utils.kt:176)
        at org.mapdb.Utils.lockWriteAll(Utils.kt:260)
        at org.mapdb.StoreWAL.commit(StoreWAL.kt:591)
        at org.mapdb.DB.commit(DB.kt:435)
        at com.stellus.store.StellusReportStoreMapDB.push(StellusReportStoreMapDB.java:100)
        - locked <0x00000000f0036118> (a com.stellus.store.StellusReportStoreMapDB)
        at com.stellus.store.StellusReportStoreMapDB.push(StellusReportStoreMapDB.java:39)
        at com.stellus.service.osmonitor.OSService$OSMonitor.run(OSService.java:152)
        at java.lang.Thread.run(Thread.java:745)

2 - Expiration Thread 1 appears to be hung up

"pool-2-thread-2" #27 prio=5 os_prio=0 tid=0x00007f758434e000 nid=0xc530 waiting on condition [0x00007f75ed190000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000f00f85b8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
        at org.mapdb.StoreWAL.get(StoreWAL.kt:933)
        at org.mapdb.DB.loadClassInfos(DB.kt:331)
        at org.mapdb.DB.access$loadClassInfos(DB.kt:32)
        at org.mapdb.DB$elsaSerializer$4.getClassInfo(DB.kt:210)
        at org.mapdb.elsa.ElsaSerializerPojo.getClassInfo(ElsaSerializerPojo.java:119)
        at org.mapdb.elsa.ElsaSerializerPojo.deserializeUnknownHeader(ElsaSerializerPojo.java:521)
        at org.mapdb.elsa.ElsaSerializerBase.deserialize(ElsaSerializerBase.java:1493)
        at org.mapdb.elsa.ElsaSerializerBase.deserializeLinkedHashMap(ElsaSerializerBase.java:1622)
        at org.mapdb.elsa.ElsaSerializerBase.access$1000(ElsaSerializerBase.java:30)
        at org.mapdb.elsa.ElsaSerializerBase$70.deserialize(ElsaSerializerBase.java:960)
        at org.mapdb.elsa.ElsaSerializerBase.deserialize(ElsaSerializerBase.java:1491)
        at org.mapdb.elsa.ElsaSerializerBase.deserializeArrayList(ElsaSerializerBase.java:1539)
        at org.mapdb.elsa.ElsaSerializerBase.access$200(ElsaSerializerBase.java:30)
        at org.mapdb.elsa.ElsaSerializerBase$62.deserialize(ElsaSerializerBase.java:887)
        at org.mapdb.elsa.ElsaSerializerBase.deserialize(ElsaSerializerBase.java:1491)
        at org.mapdb.elsa.ElsaSerializerPojo.deserializeUnknownHeader(ElsaSerializerPojo.java:553)
        at org.mapdb.elsa.ElsaSerializerBase.deserialize(ElsaSerializerBase.java:1493)
        at org.mapdb.elsa.ElsaSerializerBase.deserialize(ElsaSerializerBase.java:1479)
        at org.mapdb.DB$defaultSerializer$1.deserialize(DB.kt:221)
        at org.mapdb.StoreDirectAbstract.deserialize(StoreDirectAbstract.kt:229)
        at org.mapdb.StoreWAL.get(StoreWAL.kt:527)
        at org.mapdb.HTreeMap.valueUnwrap(HTreeMap.kt:1198)
        at org.mapdb.HTreeMap.removeprotected(HTreeMap.kt:496)
        at org.mapdb.HTreeMap.expireEvictEntry(HTreeMap.kt:914)
        at org.mapdb.HTreeMap$expireEvictSegment$1.take(HTreeMap.kt:881)
        at org.mapdb.QueueLong.takeUntil(QueueLong.kt:153)
        at org.mapdb.HTreeMap.expireEvictSegment(HTreeMap.kt:859)
        at org.mapdb.HTreeMap$1.run(HTreeMap.kt:146)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

3 - Expiration Thread 2 appears to be hung up

"pool-2-thread-1" #26 prio=5 os_prio=0 tid=0x00007f758434d000 nid=0xc52f waiting on condition [0x00007f75ed292000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000f00f8708> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
        at org.mapdb.StoreWAL.get(StoreWAL.kt:933)
        at org.mapdb.QueueLong.getTail(QueueLong.kt:61)
        at org.mapdb.QueueLong.takeUntil(QueueLong.kt:146)
        at org.mapdb.HTreeMap.expireEvictSegment(HTreeMap.kt:859)
        at org.mapdb.HTreeMap$1.run(HTreeMap.kt:146)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)


```

**Comment by jankotek** [comment]
Thread 2
a) Class info is being loaded by `ElsaSerializerPojo` during deserialization
b) deserialization is done in Store.get under read lock

Thread3
c) trying to get value from store, but that is locked by b)

so there is deadlock: a) waits for c), c) waits for b)

**Comment by jankotek** [comment]
TODO: 

- add `Serializer.externalDeps`, or similar flag. It will copy `byte[]` value and perform deserialization outside read lock. 

- Change `Utils.lockWriteAll` to use timeouts. If timeout expires, unlock everything, and try again latter.

**Comment by jankotek** [comment]
Not fully fixed,

SerializerPOJO deserialization/serialization should be done outside StoreLock
