### ISSUE TITLE
Database corruption in 1.0.9

### ISSUE THREAD

**Issue by scottcarey** [jankotek/mapdb#786]
````
      .cacheWeakRefEnable()
      .mmapFileEnableIfSupported
      .closeOnJvmShutdown
      .commitFileSyncDisable()
      .make
````

After a `kill -15` shutdown, that should trigger the closeOnJvmShutdown, the database is occasionally corrupted one of a few different ways.    My understanding is that 'commitFileSyncDisable' is data-safe, but may lose some recent transactions.   It does not appear to be.

The first way I see an issue is:

````
app stderr | java.lang.NegativeArraySizeException
        at com.rr.sinks.storage.SyncMetaImpl$BitVectorSerializer$.deserialize(SyncMetaImpl.scala:810)
        at com.rr.sinks.storage.SyncMetaImpl$BitVectorSerializer$.deserialize(SyncMetaImpl.scala:801)
        at org.mapdb.HTreeMap$2.deserialize(HTreeMap.java:135)
        at org.mapdb.HTreeMap$2.deserialize(HTreeMap.java:121)
        at org.mapdb.Store.deserialize(Store.java:297)
        at org.mapdb.StoreDirect.get2(StoreDirect.java:486)
        at org.mapdb.StoreWAL.get2(StoreWAL.java:336)
        at org.mapdb.StoreWAL.get(StoreWAL.java:320)
        at org.mapdb.Caches$WeakSoftRef.get(Caches.java:481)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
        at org.mapdb.HTreeMap.recursiveDirClear(HTreeMap.java:777)
        at org.mapdb.HTreeMap.clear(HTreeMap.java:747)
````

The line in my code that is throwing:

````scala
override def deserialize(in: DataInput, avail: Int): BitVector = {
      val bytes = new Array[Byte](in.readInt())
````

`in.readInt` is returning a negative value, which is impossible as long as the serialize completed.  The data is corrupt or truncated.  What is interesting is that this is happening at start-up on a dataset that I clear!   Why deserialize when clearing?  It appears to be WAL recovery that is triggering this and broken.

The other error is similar -- corrupted data:

````
java.lang.AssertionError: data were not fully read, check your serializer 
app stderr | Exception in thread "main" java.lang.AssertionError: data were not fully read, check your serializer 
app stderr |    at org.mapdb.Store.deserialize(Store.java:299)
        at org.mapdb.StoreDirect.get2(StoreDirect.java:486)
        at org.mapdb.StoreWAL.get2(StoreWAL.java:336)
        at org.mapdb.StoreWAL.get(StoreWAL.java:320)
        at org.mapdb.Caches$WeakSoftRef.get(Caches.java:481)
        at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
        at org.mapdb.BTreeMap$BTreeIterator.advance(BTreeMap.java:925)
        at org.mapdb.BTreeMap$BTreeEntryIterator.next(BTreeMap.java:1088)
        at org.mapdb.BTreeMap$BTreeEntryIterator.next(BTreeMap.java:1073)
````

The serializer is fine, this ONLY happens after shutdown and restart when the shutdown happens simultaneous to concurrent writing.

Things I may try:   

- turning off .mmapFileEnableIfSupported
- turning off .closeOnJvmShutdown and using my own shutdown hook that sleeps before close -- in hopes that oustanding transactions end before closing
- turning off .commitFileSyncDisable(), which will wreck my performance but might prevent corruption

Things I can't try:
 mapdb2 or mapdb3, because that will result in classpath conflicts.   My library is used by other applications, and some of those applications are using mapdb 1.0.x.    Major versions should (ethically, morally, for the good of the world!) change packages to avoid such conflicts.  As it is I have to carefully coordinate versions with other libraries and applications, which is a completely unnecessary burden imposed by _not_ changing packages.

**Comment by jankotek** [comment]
I would try to enable checksum and maybe compression. Otherwise no idea. it is old branch, so not going to investigate :(

There is `mapdb-renamed` package which renames package on 1.0 branch
