### ISSUE TITLE
wal.0 not found/access denied ( bug? in 3.0.2)

### ISSUE THREAD

**Issue by steffengrondahl** [jankotek/mapdb#788]
I constantly get a FileNotFoundException when trying to write to file:
```
Exception in thread "main" org.mapdb.DBException$VolumeIOError
	at org.mapdb.volume.RandomAccessFileVol.<init>(RandomAccessFileVol.java:63)
	at org.mapdb.volume.RandomAccessFileVol$1.makeVolume(RandomAccessFileVol.java:26)
	at org.mapdb.volume.VolumeFactory.makeVolume(VolumeFactory.java:20)
	at org.mapdb.WriteAheadLog.startNextFile(WriteAheadLog.java:128)
	at org.mapdb.WriteAheadLog.ensureFileReady(WriteAheadLog.java:1009)
	at org.mapdb.WriteAheadLog.walPutRecord(WriteAheadLog.java:955)
	at org.mapdb.StoreWAL.put(StoreWAL.kt:405)
	at org.mapdb.HTreeMap.valueWrap(HTreeMap.kt:1208)
	at org.mapdb.HTreeMap.putprotected(HTreeMap.kt:344)
	at org.mapdb.HTreeMap.put(HTreeMap.kt:324)
	at nu.steffengrondahl.persistentmap.App.main(App.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.io.FileNotFoundException: C:\temp\db.wal.0 (Adgang nægtet)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.mapdb.volume.RandomAccessFileVol.<init>(RandomAccessFileVol.java:51)
```

Adgang nægtet = access denied
Code:

```
import org.mapdb.*; 
...
DB db = DBMaker.fileDB("C:\\temp\\db").fileMmapEnableIfSupported().transactionEnable().closeOnJvmShutdown().make();
java.util.Map<String, String> map = db.hashMap("mymap", Serializer.STRING, Serializer.STRING).createOrOpen();

for(int i=0; i<10000; i++) {
   map.put("id"+i, java.util.UUID.randomUUID().toString());
   db.commit();
}
```

Yes I know, committing every add is overkill, but this shouldn't make the wal.0 file inaccessible. 
Tested on Windows 10, 32 bit JVM. 
I don't get the bug with version 1.0.8.  
It seems like the wal.0 is deleted every time it's flushed!?
I might be able to create fewer inserts (put + commit), but sometimes the exception occurs after just a few inserts.

**Comment by gordonbyron** [comment]
I am experiencing the same issue.  It is intermittent on my app but seems to be with commits happening in close succession.

**Comment by scottcarey** [comment]
What if you use FileChannel instead of RandomAccessFile ?

**Comment by thecoop** [comment]
We've got the same issue, and it happens when using filechannel or random access file (mmap fails with a different exception). In our case, the code is quite complex, so we've been unable to get a simpler test case so far
