### ISSUE TITLE
Version 3.0.2: org.mapdb.DBException$PointerChecksumBroken: Broken bit parity

### ISSUE THREAD

**Issue by reuschling** [jankotek/mapdb#794]
Hi,
after a two days run with ~70 000 000 000 entities, treemap, datasink, I've sadly got an Broken bit parity Exception during the DataSink.create() invocation. I have now a 2.5TB file on the hard disk, but can not load it - is it possible to ignore the error and create the final treemap? Can I make something different to avoid this error? Or is this just a hardware bit switch? Here is the according code:

```
public static class DataPoint extends ArrayList<String> implements Serializable
{
        private static final long serialVersionUID = -3660080037783514247L;
        public DataPoint()
        {
            super(5);
        }
}

DB db = DBMaker.fileDB(new File("dbFile")).closeOnJvmShutdown().make();
TreeMapSink<Long, DataPoint> sIds2DataPointSink =
                    db.treeMap("ids2DataPoint", Serializer.LONG, Serializer.ELSA).valuesOutsideNodesEnable().createFromSink();
for(...)
{
   //insert 70G DataPoint entities, each filled with 5 Strings
   sIds2DataPointSink.put(lId, finalDataPoint);
}
//here the error occurs
sIds2DataPointSink.create();
```

stacktrace:
```
org.mapdb.DBException$PointerChecksumBroken: Broken bit parity
        at org.mapdb.DataIO.parity1Get(DataIO.java:440)
        at org.mapdb.DataIO.unpackRecid(DataIO.java:172)
        at org.mapdb.serializer.SerializerRecid.valueArrayDeserialize(SerializerRecid.java:62)
        at org.mapdb.serializer.SerializerRecid.valueArrayDeserialize(SerializerRecid.java:13)
        at org.mapdb.BTreeMapJava$NodeSerializer.deserialize(BTreeMapJava.java:194)
        at org.mapdb.BTreeMapJava$NodeSerializer.deserialize(BTreeMapJava.java:136)
        at org.mapdb.StoreDirectAbstract.deserialize(StoreDirectAbstract.kt:229)
        at org.mapdb.StoreDirect.get(StoreDirect.kt:527)
        at org.mapdb.BTreeMap.getNode(BTreeMap.kt:800)
        at org.mapdb.BTreeMap.loadLeftEdges(BTreeMap.kt:216)
        at org.mapdb.BTreeMap.<init>(BTreeMap.kt:209)
        at org.mapdb.DB$TreeMapMaker.create2(DB.kt:1106)
        at org.mapdb.DB$TreeMapMaker.create2(DB.kt:987)
        at org.mapdb.DB$Maker.make2(DB.kt:1401)
        at org.mapdb.DB$TreeMapMaker$createFromSink$1.create(DB.kt:1081)
        at org.mapdb.DB$TreeMapMaker$createFromSink$1.create(DB.kt:1068)
```

The environment was a Linux  openSUSE Leap 42.2, Oracle Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

**Comment by jankotek** [comment]
I am trying to reproduce this issue
