### ISSUE TITLE
Header checksum broken

### ISSUE THREAD

**Issue by manishpujari84** [jankotek/mapdb#796]
Hi,

I am using mapDB 3.0.2. I am getting below exception even deleting mapDB files. Kindly help to resolve it?
Please note, this code works on windows but create problems only on Linux.
Code -
DB db = DBMaker
                .fileDB("<file path>/<file_name>.db").closeOnJvmShutdown().fileMmapEnable()
                		.transactionEnable().make();

Exception-
Caused by: org.mapdb.DBException$DataCorruption: Header checksum broken. Store was not closed correctly and might be corrupted. Use `DBMaker.checksumHeaderBypass()` to recover your data. Use clean shutdown or enable transactions to protect the store in the future.
	at org.mapdb.StoreDirectAbstract.fileHeaderCheck(StoreDirectAbstract.kt:113)
	at org.mapdb.StoreWAL.<init>(StoreWAL.kt:148)
	at org.mapdb.StoreWAL$Companion.make(StoreWAL.kt:56)
	at org.mapdb.StoreWAL$Companion.make$default(StoreWAL.kt:55)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:464)

**Comment by manishpujari84** [comment]
Please note, this code works on windows but create problems only on Linux.
