### ISSUE TITLE
KotlinNPE when streaming over a subset of a SortedTableMap

### ISSUE THREAD

**Issue by scottcarey** [jankotek/mapdb#800]
MapDB 3.0.3

Approximate code to reproduce:

````java
Volume vol = MappedFileVol.FACTORY.makeVolume(file, false);
SortedTableMap.Sink<byte[], byte[]> sink = SortedTableMap.create(
    vol, Serializer.BYTE_ARRAY, Serializer.BYTE_ARRAY).createFromSink();

sink.put(new byte[] { 1, 1 });
sink.put(new byte[] { 1, 2 });
sink.create().close();

SortedTableMap<byte[], byte[]> stm = SortedTableMap.open(
    MappedFileVol.FACTORY.makeVolume(file, true),
    Serializer.BYTE_ARRAY,
    Serializer.BYTE_ARRAY);

// producing a subMap that is 'after' all keys will cause trouble:

stm.subMap(new byte[] { 3 }, new byte[] { 4 })
  .entrySet()
  .stream()
  .map(entry -> entry.getKey().length + entry.getValue().length)
  .collect(Collectors.toList());

// it works fine if the subMap is 'before' all the keys, or covers some of them.
````

trace:
````
kotlin.KotlinNullPointerException
	at org.mapdb.SortedTableMap$entryIterator$2.findStart(SortedTableMap.kt:1656)
	at org.mapdb.SortedTableMap$entryIterator$2.<init>(SortedTableMap.kt:1638)
	at org.mapdb.SortedTableMap.entryIterator(SortedTableMap.kt:1625)
	at org.mapdb.BTreeMapJava$SubMap.entryIterator(BTreeMapJava.java:1081)
	at org.mapdb.BTreeMapJava$EntrySet.iterator(BTreeMapJava.java:560)
	at java.util.Spliterators$IteratorSpliterator.estimateSize(Spliterators.java:1821)
	at java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:408)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:511)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
````

**Comment by jankotek** [comment]
I could not replicate the issue, but i think I found mistake in code.

**Comment by scottcarey** [comment]
I can confirm this is fixed.  My tests fails with 3.0.3 but works with 3.1.0-SNAPSHOT.

My actual test is quite a bit more complicated than the attempt to condense it above.

How close is a 3.1.0 release?

**Comment by jankotek** [comment]
It is also fixed in 3.0.x branch. will release that some time this week

**Comment by scottcarey** [comment]
Thanks @jankotek   I'll use the next 3.0.x release as soon as it is available.

**Comment by scottcarey** [comment]
@jankotek when do you expect a 3.0.x release containing this bugfix?

**Comment by jankotek** [comment]
@scottcarey 3.0.x will be out in few days.

**Comment by scottcarey** [comment]
@jankotek any update on a 3.0.x release?  Or 3.1 ?
