### ISSUE TITLE
AssertionError while attempting to read from MapDB

### ISSUE THREAD

**Issue by bxnkole** [jankotek/mapdb#805]
Hi Jankotek, great application you have here!

I've been using MapDB (1.0.8) to store configuration for a desktop application deployed to over 5000 computers. Lately an issue has come up where records cannot be retrieved from the db file, adversely affecting user experience. See stack trace below:

```
java.lang.AssertionError
	at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:444)
	at org.mapdb.SerializerBase.deserialize3(SerializerBase.java:1216)
	at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1132)
	at org.mapdb.SerializerBase.deserialize(SerializerBase.java:867)
	at org.mapdb.SerializerPojo.deserialize(SerializerPojo.java:701)
	at org.mapdb.BTreeKeySerializer$BasicKeySerializer.deserialize(BTreeKeySerializer.java:89)
	at org.mapdb.BTreeMap$NodeSerializer.deserialize(BTreeMap.java:440)
	at org.mapdb.BTreeMap$NodeSerializer.deserialize(BTreeMap.java:288)
	at org.mapdb.Store.deserialize(Store.java:297)
	at org.mapdb.StoreDirect.get2(StoreDirect.java:486)
	at org.mapdb.StoreWAL.get2(StoreWAL.java:336)
	at org.mapdb.StoreWAL.get(StoreWAL.java:320)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.AsyncWriteEngine.get(AsyncWriteEngine.java:333)
	at org.mapdb.Caches$HashTable.get(Caches.java:246)
	at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
	at org.mapdb.BTreeMap.get(BTreeMap.java:602)
	at org.mapdb.BTreeMap.get(BTreeMap.java:589)

```

I dug into MapDB source and I discovered that the AssertionError is manually thrown when comparing headers in **SerializerPojo** class

```
if(head != Header.POJO) 
	throw new AssertionError();	

```		
The value of head variable in this case is 191 while Header.POJO resolves to 173. Any ideas about how the 191 value came about? Why is this header comparison required? How can I go about solving this problem?

My DB instance was instantiated like this:
	
```
byte[] passwordBytes = new byte[]{1, 2, 3}; //not actual password 
File f = new File("dbFile.dat");
DB appConfigDb = DBMaker.newFileDB(f).closeOnJvmShutdown().asyncWriteEnable().encryptionEnable(passwordBytes).make();
Map<String, String> appConfigDbMap = appConfigDb.getTreeMap("treemap");
```

I set values like this:

```
public synchronized void setProperty(String key, String value) {
        if (key != null && value != null) {
            appConfigDbMap.put(key, value);
            appConfigDb.commit();
        }
}
```

And get like this:

```
public String getProperty(String key, String defaultValue) {
        try {
            String value = appConfigDbMap.get(key);
            if (value == null || "".equals(value)) {
                return defaultValue;
            } else {
                return value;
            }
        } catch (Exception e) {
            log.error("Error, returning app config value", e);
            return defaultValue;
        }
    }
```

P.S Switching to a newer version of MapDB is a very expensive option for me as it implies I'd have to roll out a new application version to all the computers using this.

Thanks

**Comment by jankotek** [comment]
Hi, I am sorry but  I no longer support 1.x branch. I would be happy to help out for money (mailto: jan at kotek dot net)

The exception is most likely result of an data corruption. There are some unfixed bugs which could cause it.
