### ISSUE TITLE
Wrong check at SortedTableMap for page size

### ISSUE THREAD

**Issue by jankotek** [jankotek/mapdb#815]
From gitter:

 use mapdb and I want to use the SortedTableMap with a page size greater than 1MB. Lets say 4MB
  Volume volume = MappedFileVol.FACTORY.makeVolume(file, false);
 SortedTableMap.Sink<Integer, String> sink = SortedTableMap
        .create(volume, Serializer.INTEGER, // key serializer
            Serializer.STRING) // value serializer
        .pageSize(4 * 1024 * 1024) // set Page Size to 4MB
        .nodeSize(8) // set Node Size to 8 entries
        .createFromSink()
but I got an error:
 Exception in thread "main" java.nio.BufferOverflowException
    at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:363)
    at org.mapdb.volume.ByteBufferVol.putData(ByteBufferVol.java:86)
    at org.mapdb.SortedTableMap$Companion$createFromSink$1.flushPage(SortedTableMap.kt:224)
    at org.mapdb.SortedTableMap$Companion$createFromSink$1.create(SortedTableMap.kt:140)
    at org.mapdb.SortedTableMap$Companion$createFromSink$1.create(SortedTableMap.kt:111)

Rafael Troilo @rtroilo Feb 27 18:51
after increasing the sliceShift
 Volume volume = MappedFileVol.FACTORY.makeVolume(file, false,0L,22,0,false);
it works, I could write to the sink, everything looks good. But I can not reopen the SortedTableMap
  volume = MappedFileVol.FACTORY.makeVolume(file, true,0L,22,0,false);
    // read-only=true
    map = SortedTableMap.open(volume, Serializer.INTEGER, Serializer.STRING);
 Exception in thread "main" org.mapdb.DBException$DataCorruption: Wrong page size: 4194304
    at org.mapdb.SortedTableMap$Companion.open(SortedTableMap.kt:94)
    at org.mapdb.SortedTableMap.open(SortedTableMap.kt)

Rafael Troilo @rtroilo Feb 27 18:57
The problem is, there is a check if the pagesize is in a certain range:
             val pageSize = volume.getLong(PAGE_SIZE_OFFSET)
            if (pageSize <= 0 || pageSize > CC.PAGE_SIZE)
                throw DBException.DataCorruption("Wrong page size: " + pageSize)

Rafael Troilo @rtroilo Feb 27 19:07
Is there any reason for this check?
I now open the Map with
map = new SortedTableMap<>(Serializer.INTEGER, Serializer.STRING, volume.getLong(32L), volume,false);
and it seems to work as expected

**Comment by jankotek** [comment]
Fixed, applied to 3.1 and 3.0 branch

**Comment by rtroilo** [comment]
Hello Jan,

great work! Thank you! 

Bye,
Rafael
