### ISSUE TITLE
org.mapdb.DBException$VolumeEOF

### ISSUE THREAD

**Issue by xiaoquanWu** [jankotek/mapdb#828]
I used mapdb(3.0.2) like this:
``` java
  DB db = DBMaker.fileDB(this.dbFile)
                .fileMmapEnableIfSupported()
                .cleanerHackEnable() 
                .checksumHeaderBypass()
                .allocateStartSize(500 * 1024 * 1024L) //500M
                .allocateIncrement(100 * 1024 * 1024L) //100M
                .executorEnable()
                .closeOnJvmShutdown()
                .make();
indexRequestCaches = db.hashMap('indexcache', Serializer.STRING, new IndexRequestWrapper.IndexRequestWrapperSerializer())
        .expireExecutor(Executors.newScheduledThreadPool(5))
        .expireExecutorPeriod(600L * 1000)  //10m
        .expireCompactThreshold(0.5d)
        .createOrOpen();
```
But after running a period of time (about 5 day), I get a error:
``` java
Exception in thread "main" org.mapdb.DBException$VolumeEOF: Get/Set beyond file size. Requested offset: 827300768, volume size: 536870912
	at org.mapdb.volume.ByteBufferVol.getSlice(ByteBufferVol.java:45)
	at org.mapdb.volume.ByteBufferVol.getDataInput(ByteBufferVol.java:138)
	at org.mapdb.volume.ByteBufferVol.getDataInput(ByteBufferVol.java:20)
	at org.mapdb.StoreDirect.get(StoreDirect.kt:545)
	at org.mapdb.IndexTreeListJava.treeFold(IndexTreeListJava.java:594)
	at org.mapdb.IndexTreeLongLongMap.forEachValue(IndexTreeLongLongMap.kt:463)
	at org.mapdb.HTreeMap.forEachValue(HTreeMap.kt:1248)
	at com.derby.nuke.kafka.app.MapdbReader.main(MapdbReader.java:40)

```

**Comment by jankotek** [comment]
I am afraid I can not help you.  ` .checksumHeaderBypass()` says you had previous data corruption, maybe from incorrect shutdown. That could cause this problem
