### ISSUE TITLE
Find out if element is still in cache

### ISSUE THREAD

**Issue by piegamesde** [jankotek/mapdb#839]
I have a setup similar to the disk overflow example in the `HTreeMap` documentation. When I get the element from the map, and that element got flushed to disk, it blocks until the element got loaded and deserialized, which might take a while. Is there a way to find out if an item is still easily accessible in the memory cache?

**Comment by piegamesde** [comment]
It actually is quite simple:

    cache.containsKey(key);

does not return if an item was added, but if it was added and is still in the cache. If the item got evicted to disk, then that `HTreeMap` now contains the value and returns  `true` on that method.

This is not a totally intuitive behavior (I found it through trial and error) that can lead to unexpected situations in some cases. Some documentation wouldn't harm here.

**Comment by piegamesde** [comment]
So, this workaround *theoretically* works, but in practice, it has some interesting side effects. As far as I can read Kotlin, `containsKey`:

 - Actually retrieves the key with `getprotected` and tests if it is `!=null`
 - Getting an element requires the read lock, no problem. But if the `expireAfterGet()` setting is set, it does actually need the write lock (!).
 - But the write lock is already held by the eviction background thread which takes its time to serialize elements.

So in the end, my main Thread calls `containsKey` to check if an element is available without having to wait for deserialization and waits until the last (de)serialization in the background thread finished. Oh, that irony.

This is how it looks like in the Thread dump:

```
"pool-2-thread-3" #20 prio=5 os_prio=0 tid=0x0000000019a75000 nid=0x1e68 waiting on condition [0x000000001e71e000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000890e7058> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:943)
        at org.mapdb.HTreeMap.remove(HTreeMap.kt:1393)
        at togos.minecraft.maprend.gui.RenderedImage.setImage(RenderedImage.java:25)
		[...]

   Locked ownable synchronizers:
        - <0x00000000890b7608> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"pool-2-thread-2" #19 prio=5 os_prio=0 tid=0x0000000019a74000 nid=0x11e4 waiting on condition [0x000000001e61e000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000890e7058> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:943)
        at org.mapdb.HTreeMap.remove(HTreeMap.kt:1393)
        at togos.minecraft.maprend.gui.RenderedImage.setImage(RenderedImage.java:25)
		[...]

   Locked ownable synchronizers:
        - <0x00000000890b79f8> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"pool-2-thread-1" #18 prio=5 os_prio=0 tid=0x0000000019932000 nid=0x286c runnable [0x000000001e51d000]
   java.lang.Thread.State: RUNNABLE
        at java.util.zip.Deflater.deflateBytes(Native Method)
        at java.util.zip.Deflater.deflate(Deflater.java:444)
        - locked <0x00000000e2075d88> (a java.util.zip.ZStreamRef)
        at java.util.zip.Deflater.deflate(Deflater.java:366)
        at com.sun.imageio.plugins.png.IDATOutputStream.deflate(PNGImageWriter.java:221)
        at com.sun.imageio.plugins.png.IDATOutputStream.write(PNGImageWriter.java:215)
        at com.sun.imageio.plugins.png.PNGImageWriter.encodePass(PNGImageWriter.java:908)
        at com.sun.imageio.plugins.png.PNGImageWriter.write_IDAT(PNGImageWriter.java:942)
        at com.sun.imageio.plugins.png.PNGImageWriter.write(PNGImageWriter.java:1158)
        at javax.imageio.ImageWriter.write(ImageWriter.java:615)
        at javax.imageio.ImageIO.doWrite(ImageIO.java:1612)
        at javax.imageio.ImageIO.write(ImageIO.java:1578)
        at togos.minecraft.maprend.gui.RenderedMap$1.serialize(RenderedMap.java:34)
        at togos.minecraft.maprend.gui.RenderedMap$1.serialize(RenderedMap.java:1)
        at org.mapdb.StoreDirectAbstract.serialize(StoreDirectAbstract.kt:243)
        at org.mapdb.StoreDirect.put(StoreDirect.kt:589)
        at org.mapdb.HTreeMap.valueWrap(HTreeMap.kt:1210)
        at org.mapdb.HTreeMap.putprotected(HTreeMap.kt:344)
        at org.mapdb.HTreeMap.put(HTreeMap.kt:324)
        at org.mapdb.DB$HashMapMaker$verify$listener$1.modify(DB.kt:742)
        at org.mapdb.HTreeMap.listenerNotify(HTreeMap.kt:1191)
        at org.mapdb.HTreeMap.removeprotected(HTreeMap.kt:513)
        at org.mapdb.HTreeMap.expireEvictEntry(HTreeMap.kt:914)
        at org.mapdb.HTreeMap$expireEvictSegment$1.take(HTreeMap.kt:881)
        at org.mapdb.QueueLong.takeUntil(QueueLong.kt:153)
        at org.mapdb.HTreeMap.expireEvictSegment(HTreeMap.kt:859)
        at org.mapdb.HTreeMap$1.run(HTreeMap.kt:146)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - <0x00000000890b7ca8> (a java.util.concurrent.ThreadPoolExecutor$Worker)
        - <0x00000000890e7058> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00000000890f2150> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)

"JavaFX Application Thread" #13 prio=5 os_prio=0 tid=0x00000000190fe800 nid=0x2950 waiting on condition [0x000000001a41c000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000890e7058> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:943)
        at org.mapdb.HTreeMap.containsKey(HTreeMap.kt:1408)
        at togos.minecraft.maprend.gui.RenderedImage.getImage(RenderedImage.java:45)
        at togos.minecraft.maprend.gui.RenderedRegion.draw(RenderedRegion.java:146)
		[...]

   Locked ownable synchronizers:
        - None
```

Two of the worker threads from the thread pool want to set an image and wait for the lock. The third one is the eviction background thread that holds the lock while serializing images to disk. No problem.

The JavaFX Application Thread wants to know if an image is loaded in RAM with `containsKey` and now waits for the write lock to release. And that really shouldn't happen at all.

For reference, my `RenderedImage` class:

```
package togos.minecraft.maprend.gui;

import java.util.Objects;
import org.joml.Vector3ic;
import org.mapdb.HTreeMap;
import javafx.scene.image.WritableImage;

public class RenderedImage {

	// private WritableImage image;
	private final Vector3ic								key;
	private final HTreeMap<Vector3ic, WritableImage>	cache;
	private volatile boolean							hasValue	= false;

	public RenderedImage(HTreeMap<Vector3ic, WritableImage> cache, Vector3ic key) {
		this.cache = Objects.requireNonNull(cache);
		this.key = Objects.requireNonNull(key);
		// System.out.println(cache + " " + key);
	}

	public void setImage(WritableImage image) {
		// this.image = image;
		// System.out.println(cache + " " + key + " " + image);
		if (image == null)
			cache.remove(key);
		else
			cache.put(key, image);
		hasValue = image != null;
	}

	/** Returns if the last {@link #setImage(WritableImage)} call was with a non-null value. */
	public boolean isImageSet() {
		return hasValue;
	}

	/**
	 * Returns true if the image is loaded in RAM, causing {@link #getImage(boolean)} to return immediately. Returns false if the image got written to disk to
	 * save memory.
	 */
	public boolean isImageLoaded() {
		return cache.containsKey(key);
	}

	public WritableImage getImage(boolean force) {
		return (force || cache.containsKey(key)) ? cache.get(key) : null;
	}
}
```

**Comment by piegamesde** [comment]
Here's my workaround for the issue:

```

    protected Set<Vector3ic> unloaded = ConcurrentHashMap.newKeySet();
    public final Serializer<Vector3ic> VECTOR_SERIALIZER = new Serializer<Vector3ic>() {
        @SuppressWarnings("unchecked")
        @Override
        public void serialize(DataOutput2 out, Vector3ic value) throws IOException {
            unloaded.add(value);
            Serializer.JAVA.serialize(out, value);
        }

        @Override
        public Vector3ic deserialize(DataInput2 input, int available) throws IOException {
            Vector3ic value = (Vector3ic) Serializer.JAVA.deserialize(input, available);
            unloaded.remove(value);
            return value;
        }
    };
```

`unloaded` contains the keys for all elements that are not directly accessible and is updated with each (de)serialization. Ugly, but works.

**Comment by jankotek** [comment]
Hi guys, I think this is solved in 4.0 branch. External values are not loaded for `keySet().contains()`. I am not going to port this bug to 3.0, too many changes. 

Will keep this  issue open to make sure this is fixed and documented in new release.
