### ISSUE TITLE
File too large Exception

### ISSUE THREAD

**Issue by fleaLi** [jankotek/mapdb#840]
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.3.1611 (Core)
Release:	7.3.1611
Codename:	Core

Caused by: java.io.IOException: File too large
        at sun.nio.ch.FileDispatcherImpl.truncate0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.truncate(FileDispatcherImpl.java:80)
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:906)
        at org.mapdb.volume.MappedFileVol.ensureAvailable(MappedFileVol.java:147)
        ... 28 more
2017-08-09 00:07:50 [nioEventLoopGroup-3-487] ERROR ExceptionHandler:24 -
org.mapdb.DBException$VolumeIOError
        at org.mapdb.volume.MappedFileVol.ensureAvailable(MappedFileVol.java:155)
        at org.mapdb.StoreDirect.allocateNewPage(StoreDirect.kt:153)
        at org.mapdb.StoreDirectAbstract.allocateData(StoreDirectAbstract.kt:310)
        at org.mapdb.StoreDirect.linkedRecordPut(StoreDirect.kt:243)
        at org.mapdb.StoreDirect.put(StoreDirect.kt:604)
        at org.mapdb.HTreeMap.valueWrap(HTreeMap.kt:1210)
        at org.mapdb.HTreeMap.putprotected(HTreeMap.kt:344)
        at org.mapdb.HTreeMap.put(HTreeMap.kt:324)
        at com.antzb.app.controller.TaskTemplateController.convergeItemsOfQBZ(TaskTemplateController.java:183)
        at sun.reflect.GeneratedMethodAccessor437.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

The code ：

 private static final DB db= DBMaker.fileDB(ConstProperties.get("mapdbfile")).fileMmapEnable()
            .fileMmapEnableIfSupported().fileMmapPreclearDisable()
            .cleanerHackEnable()
            .checksumHeaderBypass()
            .fileChannelEnable()
            .make();
   private static final HTreeMap<String,List<JSONObject>> cache=db.hashMap("aggregation",Serializer.STRING,Serializer.ELSA).
            expireExecutor(Executors.newScheduledThreadPool(1)).
            expireAfterCreate(Long.valueOf(ConstProperties.get("mapdbtime")), TimeUnit.MINUTES)
                .expireAfterUpdate(Long.valueOf(ConstProperties.get("mapdbtime")),TimeUnit.MINUTES)
                .expireAfterGet(Long.valueOf(ConstProperties.get("mapdbtime")),TimeUnit.MINUTES).createOrOpen();
    public final  static DB getDb(){
        db.getStore().fileLoad();
        DB d=db;
        return d;
    }

**Comment by jankotek** [comment]
What mapdb version is it?

**Comment by fleaLi** [comment]
3.0.5
