### ISSUE TITLE
assertion failure when creating SortedTableMap

### ISSUE THREAD

**Issue by jakubzytka** [jankotek/mapdb#852]
Hello,

MapDB 3.0.5

I stumbled upon assertion failure at 
```
org.mapdb.SortedTableMap$Companion$createFromSink$1.flushPage(SortedTableMap.kt:213)
	at org.mapdb.SortedTableMap$Companion$createFromSink$1.create(SortedTableMap.kt:146)
	at org.mapdb.SortedTableMap$Companion$createFromSink$1.create(SortedTableMap.kt:117)
	at Test.main(Test.java:24)
```

reproduction test case is below;
do I do anything wrong?

```
import org.mapdb.Serializer;
import org.mapdb.SortedTableMap;
import org.mapdb.volume.RandomAccessFileVol;
import org.mapdb.volume.Volume;


public class Test {
    public static void main( String[] args ) {
	Volume volume = RandomAccessFileVol.FACTORY.makeVolume("test.mapdb", false);
	
	SortedTableMap.Sink<Long, byte[]> sink = SortedTableMap.create(
        	volume,
	        Serializer.LONG,
        	Serializer.BYTE_ARRAY)
		.pageSize(1 << 19)
		.createFromSink();

	for (long i = 0; i < 15; i++) {
		byte[] bytes = new byte[i < 14 ? 50 : 550000];
		sink.put(i, bytes);
	}
	sink.create();
	volume.close();

        System.exit( 0 );
    }
}
```

**Comment by Loeing** [comment]
I've run into the same issue, but SortedTableMap doesn't seem to be in master anymore. Is there somewhere I can look if I want to try fixing the bug?
