### ISSUE TITLE
Exception when iterating over keys in HashTreeMap

### ISSUE THREAD

**Issue by andrm** [jankotek/mapdb#858]
This is with 3.0.5. (excluded guava from the mapdb dependency for newer guava)

Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.mapdb.DataInput2$ByteBuffer.unpackInt(DataInput2.java:389)
	at org.mapdb.DataInput2.readUTF(DataInput2.java:491)
	at org.mapdb.serializer.SerializerString.deserialize(SerializerString.java:20)
	at org.mapdb.serializer.SerializerString.deserialize(SerializerString.java:11)
	at org.mapdb.HTreeMap$leafValueExternalSerializer$1.deserialize(HTreeMap.kt:228)
	at org.mapdb.HTreeMap$leafValueExternalSerializer$1.deserialize(HTreeMap.kt:214)
	at org.mapdb.StoreDirectAbstract.deserialize(StoreDirectAbstract.kt:229)
	at org.mapdb.StoreDirect.get(StoreDirect.kt:546)
	at org.mapdb.HTreeMap.leafGet(HTreeMap.kt:1374)
	at org.mapdb.HTreeMap$htreeIterator$1.moveToNextLeaf(HTreeMap.kt:1057)
	at org.mapdb.HTreeMap$htreeIterator$1.next(HTreeMap.kt:1082)
	at com.google.common.collect.Iterators$ConcatenatedIterator.next(Iterators.java:1425)
	at pcon.cleanup(ProductionDb.java:257)

Code:
hMap = this.dataBase.hashMap(ACTION_MAP)
                    .keySerializer(STRING)
                    .valueSerializer(BYTE_ARRAY)
                    .layout(16,128,4)
                    .createOrOpen();
Set<String> keys = hMap.getKeys();
        for (String key : keys)  {
....

**Comment by zkmake520** [comment]
Also met this problem  during iterating or put a new value

**Comment by Loeing** [comment]
It looks like this ticket has a fix: 
https://github.com/jankotek/mapdb/issues/881

**Comment by andrm** [comment]
Yupp.
