### ISSUE TITLE
MapDB fails if map file reopened with different allocation settings

### ISSUE THREAD

**Issue by allanwax** [jankotek/mapdb#860]
I created a mapdb.db file on an SSD disk using mmap and an allocation and increment size of 1G, and inserted 1.3 billion (USA) hashset values.  This worked fine (but it took some time).

I then properly closed the mapdb file and reopened using mmap and the default allocation values (they were not specified).  This failed with the following:

```
 FATAL -- org.mapdb.DBException$VolumeIOError
org.mapdb.DBException$VolumeIOError
        at org.mapdb.volume.MappedFileVol.<init>(MappedFileVol.java:113)
        at org.mapdb.volume.MappedFileVol$MappedFileFactory.factory(MappedFileVol.java:64)
        at org.mapdb.volume.MappedFileVol$MappedFileFactory.makeVolume(MappedFileVol.java:38)
        at org.mapdb.StoreDirect$volume$1.invoke(StoreDirect.kt:77)
        at org.mapdb.StoreDirect$volume$1.invoke(StoreDirect.kt:16)
        at org.mapdb.StoreDirect.<init>(StoreDirect.kt:76)
        at org.mapdb.StoreDirect$Companion.make(StoreDirect.kt:57)
        at org.mapdb.StoreDirect$Companion.make$default(StoreDirect.kt:56)
        at org.mapdb.DBMaker$Maker.make(DBMaker.kt:450)
        at com.findology.mapdb.MapDBOps.init(MapDBOps.java:99)
        at com.findology.mapdb.MapDBServer.main(MapDBServer.java:293)
Caused by: java.io.IOException: Map failed
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:940)
        at org.mapdb.volume.MappedFileVol.<init>(MappedFileVol.java:104)
        ... 10 more
Caused by: java.lang.OutOfMemoryError: Map failed
        at sun.nio.ch.FileChannelImpl.map0(Native Method)
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:937)
        ... 11 more

```

If I put back the allocation values, it opens fine.

I think it is a bug if you have to use the same allocation values to open the DB in the future.  DB files can be moved around to machines with different configuration.

**Comment by andrm** [comment]
Did you adjust the layout values? See https://jankotek.gitbooks.io/mapdb/content/htreemap/ , scroll down to "Layout". Default values for a htreemap only make space for 500k entries.

**Comment by allanwax** [comment]
@andrm  Layout is the default values in both cases.  Do you suggest changes? How would this affect avoiding the issue when changing allocation problems?

**Comment by andrm** [comment]
This gives you 16 billion entries to a map:

```
HTreeMap myhashMap = dataBase.hashMap("examplemap")
                    .keySerializer(STRING)
                    .valueSerializer(BYTE_ARRAY)
                    .layout(16, 64, 5)
                    .createOrOpen();
```

**Comment by allanwax** [comment]
@andrm Thanks!

I ran a stupid little program to generate possible max values and came up with `32, 32, 6` to produce `~3.4E10` .  I will try this number as MapDB documents indicate that only a 32-bit hash is used which produces only a little over 4B unique values.

Does changing the layout in anyway affect the issue of failure when opening a mapdb file create with large mmap allocation and then reopening with default?

**Comment by andrm** [comment]
I'm not sure if I understand your question correctly.
For the layout, you need to re-open with the same layout parameters in 3.0.5.
I don't think initial size of the allocation is relevant for re-opening an existing mapdb. The increment allocation is used though.
I think your original problem was that the instance couldn't handle that many entries.

**Comment by allanwax** [comment]
@andrm For this situation the same layout was used for both.  The only thing that changed was the allocation.  Created with a 1G allocation and read with the default allocation for the failure condition.

If the issue is  

> the instance couldn't handle that many entries

 then perhaps the db parameters should be scanned ahead of time and MapDB should adapt.  I think MapDB should be more robust than it currently is.

Also, I would probably be a good idea to have a utility to examine a DB and print out all the configuration information so that if you're opening a DB copied from another machine that you could tell what configuration you need to make it run.  Just an idea.

**Comment by andrm** [comment]
@allanwax I agree with you that the MapDB should be more robust in that regard. I think @jankotek  is very aware of it and things will improve in 4.0.
