### ISSUE TITLE
Periodic NullPointerException.

### ISSUE THREAD

**Issue by unnuferdev** [jankotek/mapdb#869]
Hello. Sometimes I have NPE with following  stack-trace.

java.lang.NullPointerException: null
	at org.mapdb.volume.ByteBufferVolSingle.getLong(ByteBufferVolSingle.java:110)
	at org.mapdb.StoreDirect.getIndexVal(StoreDirect.kt:128)
	at org.mapdb.StoreDirect.get(StoreDirect.kt:523)
	at org.mapdb.BTreeMap.getNode(BTreeMap.kt:800)
	at org.mapdb.BTreeMap.access$getNode(BTreeMap.kt:72)
	at org.mapdb.BTreeMap$BTreeBoundIterator.advanceFromLo(BTreeMap.kt:1109)
	at org.mapdb.BTreeMap$BTreeBoundIterator.<init>(BTreeMap.kt:1072)
	at org.mapdb.BTreeMap$entryIterator$2.<init>(BTreeMap.kt:1187)
	at org.mapdb.BTreeMap.entryIterator(BTreeMap.kt:1187)

Could you point possible reasons? Or it is bug in code?

**Comment by jankotek** [comment]
I think you are trying to access store after it was closed.
