### ISSUE TITLE
NullpointerException under high load

### ISSUE THREAD

**Issue by rjtokenring** [jankotek/mapdb#892]
Hi, under multithreaded high load, I got this exception:

java.lang.NullPointerException
        at org.mapdb.volume.ByteBufferVol.getSlice(ByteBufferVol.java:43)
        at org.mapdb.volume.ByteBufferVol.getLong(ByteBufferVol.java:122)
        at org.mapdb.StoreDirect.getIndexVal(StoreDirect.kt:128)
        at org.mapdb.StoreDirect.getBinaryLong(StoreDirect.kt:556)
        at org.mapdb.IndexTreeListJava.treeGetBinary(IndexTreeListJava.java:238)
        at org.mapdb.IndexTreeListJava.treeGet(IndexTreeListJava.java:193)
        at org.mapdb.IndexTreeLongLongMap.get(IndexTreeLongLongMap.kt:77)
        at org.mapdb.HTreeMap.getprotected(HTreeMap.kt:629)
        at org.mapdb.HTreeMap.get(HTreeMap.kt:603)
...

Code as attachment.

Version 3.0.5

[MapDbHandler.txt](https://github.com/jankotek/mapdb/files/1970420/MapDbHandler.txt)

**Comment by passyt** [comment]
Any update on this, I got the same error on version 3.0.7?
