### ISSUE TITLE
IndexOutOfBoundsException and Multiple WAL File

### ISSUE THREAD

**Issue by davutcavdar** [jankotek/mapdb#897]
We are using 3.07create DB like that: 

```
db = DBMaker
		.fileDB(dbName)
		.fileMmapEnableIfSupported()
		.transactionEnable()
		.closeOnJvmShutdown()
		.make();

map = db.treeMap(MAP_NAME).keySerializer(Serializer.STRING).valueSerializer(Serializer.STRING).counterEnable().createOrOpen();
```
Then have realized that, IndexOutOfBoundsException exceptions are thrown and multiple WAL files are created, such as db.wal.0, db.wal.2 ...... db.wal.100 etc.

Example error log: 

Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at java.util.Collections$SynchronizedList.get(Collections.java:2417)
	at org.mapdb.WriteAheadLog.walGetRecord(WriteAheadLog.java:863)
	at org.mapdb.StoreWAL.get(StoreWAL.kt:522)
	at org.mapdb.BTreeMap.getNode(BTreeMap.kt:800)
	at org.mapdb.BTreeMap.getNonBinary(BTreeMap.kt:271)
	at org.mapdb.BTreeMap.get(BTreeMap.kt:235)
	at io.antmedia.datastore.db.MapDBStore.get(MapDBStore.java:152)

Any suggestions to resolve these issues?

**Comment by MouamleH** [comment]
Is there a way to recover the DB data after this?
