### ISSUE TITLE
java.lang.IndexOutOfBoundsException while doing Commit for StoreWAL

### ISSUE THREAD

**Issue by abhishekmaheshwari86** [jankotek/mapdb#906]
Hi All,

i am facing below issue with MapDB. Below is stacktrace.

Exception in thread "AggregationThread-2" java.lang.IndexOutOfBoundsException
        at java.nio.Buffer.checkIndex(Buffer.java:540)
        at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
        at org.mapdb.volume.ByteBufferVol.getPackedLong(ByteBufferVol.java:289)
        at org.mapdb.WriteAheadLog.walGetRecord(WriteAheadLog.java:869)
        at org.mapdb.StoreWAL$commit$4.value(StoreWAL.kt:623)
        at org.eclipse.collections.impl.map.mutable.primitive.LongLongHashMap.forEachKeyValue(LongLongHashMap.java:998)
        at org.mapdb.StoreWAL.commit(StoreWAL.kt:622)
        at org.mapdb.DB.commit(DB.kt:435)
        at org.colombia.aggbus.api.store.MapDBStore.commit(MapDBStore.java:71)
        at com.colombia.metrics.MetricsService$AdLogProcessor.onCommit(MetricsService.java:382)
        at org.colombia.aggbus.api.Aggregator.commit(Aggregator.java:196)
        at org.colombia.aggbus.api.AggregationBus$AggregationThread.run(AggregationBus.java:526)

Maven Config:
<dependency>
    <groupId>org.mapdb</groupId>
    <artifactId>mapdb</artifactId>
    <version>3.0.7</version>
</dependency>

Code to create DB:
  db = DBMaker
                .fileDB(dir + name)
                .concurrencyDisable()
                .fileMmapEnableIfSupported() 
                .fileMmapPreclearDisable()
                .allocateStartSize(512 * 1024*1024)
                .allocateIncrement(256 * 1024*1024)
                .transactionEnable()
                .closeOnJvmShutdown()
                .make();

        store = db
                .hashMap(name, keySerializer, valueSerializer)
                .counterEnable()
                .expireAfterCreate(unit.toMillis(ttl))
                .expireExecutor(Executors.newScheduledThreadPool(1))
                .createOrOpen();

**Comment by icreator** [comment]
.closeOnJvmShutdown()

maybe you terminate JVM by Ctrl^C and use .close() in code

try remove .closeOnJvmShutdown()
