### ISSUE TITLE
org.mapdb.DBException$FileLocked: File is already opened and is locked:

### ISSUE THREAD

**Issue by jigees4u** [jankotek/mapdb#916]
**Code Snippet:**
DB db = DBMaker
          .fileDB("<FilePath>")
          .closeOnJvmShutdown()
          .allocateStartSize(1024)
          .allocateIncrement(1024)
          .transactionEnable().make();

**Error:**
org.mapdb.DBException$FileLocked: File is already opened and is locked: <FilePath>
	at org.mapdb.volume.Volume.lockFile(Volume.java:495)
	at org.mapdb.volume.RandomAccessFileVol.<init>(RandomAccessFileVol.java:52)
	at org.mapdb.volume.RandomAccessFileVol$1.makeVolume(RandomAccessFileVol.java:26)
	at org.mapdb.StoreWAL$realVolume$1.invoke(StoreWAL.kt:75)
	at org.mapdb.StoreWAL$realVolume$1.invoke(StoreWAL.kt:18)
	at org.mapdb.StoreWAL.<init>(StoreWAL.kt:74)
	at org.mapdb.StoreWAL$Companion.make(StoreWAL.kt:56)
	at org.mapdb.StoreWAL$Companion.make$default(StoreWAL.kt:55)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:464)
	.
	.
	.
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at org.mapdb.volume.Volume.lockFile(Volume.java:490)
	... 12 more

**Comment by vJ101010** [comment]
+1

we are also facing similar issue, where we are getting 
Caused by: org.mapdb.DBException$FileLocked: File is already opened and is locked: db\subscribers_2.ser
	at org.mapdb.volume.Volume.lockFile(Volume.java:495)
 	at org.mapdb.volume.RandomAccessFileVol.<init>(RandomAccessFileVol.java:52)
 	at org.mapdb.volume.RandomAccessFileVol$1.makeVolume(RandomAccessFileVol.java:26)
	at org.mapdb.StoreDirect$volume$1.invoke(StoreDirect.kt:77)
	at org.mapdb.StoreDirect$volume$1.invoke(StoreDirect.kt:16)
 	at org.mapdb.StoreDirect.<init>(StoreDirect.kt:76)
	at org.mapdb.StoreDirect$Companion.make(StoreDirect.kt:57)
	at org.mapdb.StoreDirect$Companion.make$default(StoreDirect.kt:56)
 	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:450)
 	at com.nimsoft.events.common.mapdb.MapDb.openDB(MapDb.java:115)
	at com.nimsoft.events.common.mapdb.MapDb.open(MapDb.java:60)
	... 9 more
Caused by: java.nio.channels.OverlappingFileLockException
at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at org.mapdb.volume.Volume.lockFile(Volume.java:490)


**Manually deleting db folder and restarting Java application is solving us this issue**

**Comment by madhavabk** [comment]
+1
i am adding some entries and then just reading it and i face same issue.
org.mapdb.DBException$FileLocked: File is already opened and is locked: D:\membersList.db
	at org.mapdb.volume.Volume.lockFile(Volume.java:495)
	at org.mapdb.volume.RandomAccessFileVol.<init>(RandomAccessFileVol.java:52)
	at org.mapdb.volume.RandomAccessFileVol$1.makeVolume(RandomAccessFileVol.java:26)
	at org.mapdb.StoreDirect$volume$1.invoke(StoreDirect.kt:77)
	at org.mapdb.StoreDirect$volume$1.invoke(StoreDirect.kt:16)
	at org.mapdb.StoreDirect.<init>(StoreDirect.kt:76)
	at org.mapdb.StoreDirect$Companion.make(StoreDirect.kt:57)
	at org.mapdb.StoreDirect$Companion.make$default(StoreDirect.kt:56)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:450)

Any solution for this problem?

**Comment by bthomee** [comment]
I experienced this too on Mac OS Mojave 10.14.6 while writing to an exFat formatted drive. Writing the data to a Mac OS Extended (Journaled) RAID drive instead was successful.

I call the code as follows:
return DBMaker
	.fileDB(path)
	.fileMmapEnable()
	.fileMmapPreclearDisable()
	.allocateStartSize(1024*1024*128) // 128MB
	.allocateIncrement(1024*1024*128) // 128MB
	.closeOnJvmShutdown()
	.make();

**Comment by euggorw** [comment]
+1

**Comment by boundaries-io** [comment]
+1, will this ever be worked on ? it has been a year.....

**Comment by brett-matson** [comment]
I'm having this problem on MacOS Big Sur. Did anyone find a work around? (other than deleting the databases)

**Comment by bestDvlpr** [comment]
Does anyone have any solution or workaround to solve the issue?

**Comment by boerzi** [comment]
DBMaker.fileDB(file).fileLockDisable().make()

use fileLockDisable() method
