### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by leonchen83** [jankotek/mapdb#928]
mapdb version : 3.0.7
os version : windows 7 64bit
memory : 8g
jdk : 1.8.0_151
cpu : core i3-4710
reproduce code:

```
public static void main(String[] args) {
	DB db = DBMaker.memoryDirectDB().make();
	ConcurrentMap<Long, byte[]> r = db.hashMap("foo").keySerializer(Serializer.LONG).valueSerializer(Serializer.BYTE_ARRAY).createOrOpen();
	for (int i = 0; i < 100000000; i++) {
		byte[] value = new byte[2048];
		r.put(1L, value);
		r.remove(1L);
	}
}
```

exception:
```
Exception in thread "main" org.mapdb.DBException$OutOfMemory: Out of Direct buffer memory. Increase it with JVM option '-XX:MaxDirectMemorySize=10G'
	at org.mapdb.volume.ByteBufferMemoryVol.ensureAvailable(ByteBufferMemoryVol.java:112)
	at org.mapdb.StoreDirect.allocateNewPage(StoreDirect.kt:153)
	at org.mapdb.StoreDirectAbstract.allocateData(StoreDirectAbstract.kt:310)
	at org.mapdb.StoreDirect.longStackNewChunk(StoreDirect.kt:368)
	at org.mapdb.StoreDirect.longStackPut(StoreDirect.kt:288)
	at org.mapdb.StoreDirectAbstract.releaseData(StoreDirectAbstract.kt:367)
	at org.mapdb.StoreDirect.updateProtected(StoreDirect.kt:663)
	at org.mapdb.StoreDirect.update(StoreDirect.kt:634)
	at org.mapdb.IndexTreeListJava.treeRemoveCollapsing(IndexTreeListJava.java:518)
	at org.mapdb.IndexTreeLongLongMap.remove(IndexTreeLongLongMap.kt:88)
	at org.mapdb.IndexTreeLongLongMap.removeKey(IndexTreeLongLongMap.kt:394)
	at org.mapdb.HTreeMap.removeprotected(HTreeMap.kt:501)
	at org.mapdb.HTreeMap.remove(HTreeMap.kt:464)
	at cn.nextop.gondor.core.common.domain.pipeline.engine.storage.MapdbEntityStorage.main(MapdbEntityStorage.java:92)
Caused by: java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:694)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at org.mapdb.volume.ByteBufferMemoryVol.ensureAvailable(ByteBufferMemoryVol.java:103)
	... 13 more

```

**Comment by leonchen83** [comment]
mapdb version 1.0.7 can run this example
```
	public static void main(String[] args) {
		DB db = DBMaker.newMemoryDirectDB().transactionDisable().cacheDisable().make();

		ConcurrentMap<Long, byte[]> r = db.createHashMap("foo").keySerializer(Serializer.LONG).valueSerializer(Serializer.BYTE_ARRAY).make();
		for (int i = 0; i < 100000000; i++) {
			byte[] value = new byte[2048];
			r.put(1L, value);
			r.remove(1L);
		}
	}
```

**Comment by jankotek** [comment]
Offheap (direct) memory is limited. There is some JVM setting to increase this limit.

**Comment by leonchen83** [comment]
but I put the key `1L` and then I remove this key `1L`, and loop 100000000 times, should not reach the off heap limit. above code can work normaly in version 1.0.7
