### ISSUE TITLE
Exception on DB db = DBMaker.fileDB("/tmp/myfile.db").make()

### ISSUE THREAD

**Issue by sergioszy** [jankotek/mapdb#932]
Hello, I got this exception when I try

DB db = DBMaker.fileDB("/tmp/myfile.db").make();

Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/ranges/RangesKt
	at org.mapdb.StoreDirectAbstract.calculateHeaderChecksum(StoreDirectAbstract.kt:405)
	at org.mapdb.StoreDirectAbstract.fileHeaderCheck(StoreDirectAbstract.kt:108)
	at org.mapdb.StoreDirect.<init>(StoreDirect.kt:114)
	at org.mapdb.StoreDirect$Companion.make(StoreDirect.kt:57)
	at org.mapdb.StoreDirect$Companion.make$default(StoreDirect.kt:56)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:450)
	at mapdb.Merda.<init>(Merda.java:21)
	at mapdb.Merda.main(Merda.java:55)
Caused by: java.lang.ClassNotFoundException: kotlin.ranges.RangesKt
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

Thanks in advance

**Comment by allanwax** [comment]
If you would post your build methodology and the sample program, it would help to diagnose this.

**Comment by allanwax** [comment]
Try not importing Kotlin.  Mapdb should do it for you.  I do my builds outside of IntelliJ so should should be able to try 'mvn clean install <more flags as needed> -U'

**Comment by allanwax** [comment]
I also recommend adding closeOnJvmShutdown() so that resources will be released at program exit.  However this has nothing to do with there error, just good practice.

**Comment by jankotek** [comment]
MapDB already depends on kotlin-stdlib, so it will import specific version.
