### ISSUE TITLE
rollback throws org.mapdb.DBException$GetVoid

### ISSUE THREAD

**Issue by teenriot** [jankotek/mapdb#934]
Exception is thrown at last command

`Exception in thread "main" org.mapdb.DBException$GetVoid: Record does not exist, recid=11
	at org.mapdb.StoreWAL.getIndexVal(StoreWAL.kt:169)
	at org.mapdb.StoreWAL.get(StoreWAL.kt:499)
	at org.mapdb.BTreeMap.sizeLong(BTreeMap.kt:902)
	at org.mapdb.BTreeMap.getSize(BTreeMap.kt:898)
	at org.mapdb.BTreeMap.size(BTreeMap.kt:72)`

for the SSCCE:

`import org.mapdb.BTreeMap;
import org.mapdb.DB;
import org.mapdb.DBMaker;
import org.mapdb.Serializer;

public class Test
{
	public static void main(String[] args)
	{
		try (DB db = DBMaker.fileDB("testdata/test.db")
							.transactionEnable()
							.make()) {
        	BTreeMap<Integer, Integer> data = db.treeMap("test", Serializer.INTEGER, Serializer.INTEGER)
                    							.counterEnable()
                    							.createOrOpen();
    		data.put(1, 1);
    		db.rollback();
    		System.out.println(data.size());
		}		
	}
}`

**Comment by jankotek** [comment]
What version is it?

**Comment by teenriot** [comment]
Sry for lack of information.
I used Version 3.0.7.

**Comment by novoj** [comment]
Same problem here.

**Comment by totalslacker** [comment]
Is there any update here? I'm trying 3.0.8 and am seeing the same behavior. Even containsKey throws the same exception, which is making a workaround difficult.

**Comment by khliu1238** [comment]
Any update? I have same issue as well. Version 3.0.7.

**Comment by Montaro2017** [comment]
updated? Same issue, i'm using 3.0.10

**Comment by MikeyCarter** [comment]
Anyone got an idea how to recover?   I'm getting the same error so thought to run <obj>.clear()

But the error comes up on clear as well.   No way to clear out the record in question.

```org.mapdb.DBException$GetVoid: Record does not exist, recid=900
	at org.mapdb.StoreWAL.get(StoreWAL.kt:505)
	at org.mapdb.HTreeMap.leafGet(HTreeMap.kt:1372)
	at org.mapdb.HTreeMap$clear$$inlined$lockWrite$lambda$1.value(HTreeMap.kt:553)
	at org.mapdb.IndexTreeLongLongMap$forEachKeyValue$1.visit(IndexTreeLongLongMap.kt:453)
	at org.mapdb.IndexTreeLongLongMap$forEachKeyValue$1.visit(IndexTreeLongLongMap.kt:49)
	at org.mapdb.IndexTreeListJava.treeFold(IndexTreeListJava.java:606)
	at org.mapdb.IndexTreeListJava.treeFold(IndexTreeListJava.java:604)
	at org.mapdb.IndexTreeLongLongMap.forEachKeyValue(IndexTreeLongLongMap.kt:452)
	at org.mapdb.HTreeMap.clear(HTreeMap.kt:552)
	at org.mapdb.HTreeMap.clear(HTreeMap.kt:523)
```
