### ISSUE TITLE
org.mapdb.DBException$PointerChecksumBroken: Broken bit parity

### ISSUE THREAD

**Issue by sunyaf** [jankotek/mapdb#944]
org.mapdb.DBException$PointerChecksumBroken: Broken bit parity
        at org.mapdb.DataIO.parity4Get(DataIO.java:476)
分支
            <groupId>org.mapdb</groupId>
            <artifactId>mapdb</artifactId>
            <version>3.0.7</version>

**Comment by sunyaf** [comment]
<dependency>
            <groupId>org.mapdb</groupId>
            <artifactId>mapdb</artifactId>
            <version>3.0.7</version>
            <exclusions>
                <exclusion>
                    <groupId>org.eclipse.collections</groupId>
                    <artifactId>eclipse-collections-forkjoin</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.collections</groupId>
                    <artifactId>eclipse-collections</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.collections</groupId>
                    <artifactId>eclipse-collections-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.google.guavas</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by hamadodene** [comment]
I found the same problem in production with the same version of MapDB.
```
org.mapdb.DBException$PointerChecksumBroken: Broken bit parity
at org.mapdb.DataIO.parity4Get(DataIO.java:476)
at org.mapdb.StoreWAL.longStackLoadChunk(StoreWAL.kt:732)
at org.mapdb.StoreWAL.longStackPut(StoreWAL.kt:712)
at org.mapdb.StoreDirectAbstract.releaseData(StoreDirectAbstract.kt:367)
at org.mapdb.StoreWAL.longStackTake(StoreWAL.kt:890)
at org.mapdb.StoreDirectAbstract.allocateRecid(StoreDirectAbstract.kt:255)
at org.mapdb.StoreWAL.put(StoreWAL.kt:383)
at org.mapdb.HTreeMap.putprotected(HTreeMap.kt:350)
```

Do you have some ideas to fix this problem?

**Comment by nicoloboschi** [comment]
Same as @hamadodene  

@jankotek  any idea? do you need other information/logs?

**Comment by Azmechatech** [comment]
Same here:
org.mapdb.DBException$PointerChecksumBroken: Broken bit parity
        at org.mapdb.DataIO.parity1Get(DataIO.java:448)
        at org.mapdb.BTreeMapJava$NodeSerializer.deserialize(BTreeMapJava.java:176)
        at org.mapdb.BTreeMapJava$NodeSerializer.deserialize(BTreeMapJava.java:136)
        at org.mapdb.StoreDirectAbstract.deserialize(StoreDirectAbstract.kt:229)
        at org.mapdb.StoreWAL.get(StoreWAL.kt:527)
        at org.mapdb.BTreeMap.getNode(BTreeMap.kt:800)
        at org.mapdb.BTreeMap.access$getNode(BTreeMap.kt:72)
        at org.mapdb.BTreeMap$BTreeIterator.advanceFrom(BTreeMap.kt:1031)
        at org.mapdb.BTreeMap$BTreeIterator.advance(BTreeMap.kt:1050)
        at org.mapdb.BTreeMap$keyIterator$1.next(BTreeMap.kt:1205)
        at org.mapdb.BTreeMap.sizeLong(BTreeMap.kt:908)
        at org.mapdb.BTreeMap.getSize(BTreeMap.kt:898)
        at org.mapdb.BTreeMap.size(BTreeMap.kt:72)
        at org.mapdb.BTreeMap$entries$1.getSize(BTreeMap.kt:971)
        at org.mapdb.BTreeMap$entries$1.size(BTreeMap.kt:936)
        at java.base/java.util.Spliterators$IteratorSpliterator.estimateSize(Spliterators.java:1822)
        at java.base/java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:408)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:558)
        at java.base/java.util.stream.ReferencePipeline.max(ReferencePipeline.java:594)

**Comment by sunyaf** [comment]
I've really given it up. Maybe you can try the latest version

**Comment by sunyaf** [comment]
> @jankotek
> Same here:
> org.mapdb.DBException$PointerChecksumBroken: Broken bit parity
> at org.mapdb.DataIO.parity1Get(DataIO.java:448)
> at org.mapdb.BTreeMapJava$NodeSerializer.deserialize(BTreeMapJava.java:176)
> at org.mapdb.BTreeMapJava$NodeSerializer.deserialize(BTreeMapJava.java:136)
> at org.mapdb.StoreDirectAbstract.deserialize(StoreDirectAbstract.kt:229)
> at org.mapdb.StoreWAL.get(StoreWAL.kt:527)
> at org.mapdb.BTreeMap.getNode(BTreeMap.kt:800)
> at org.mapdb.BTreeMap.access$getNode(BTreeMap.kt:72)
> at org.mapdb.BTreeMap$BTreeIterator.advanceFrom(BTreeMap.kt:1031)
> at org.mapdb.BTreeMap$BTreeIterator.advance(BTreeMap.kt:1050)
> at org.mapdb.BTreeMap$keyIterator$1.next(BTreeMap.kt:1205)
> at org.mapdb.BTreeMap.sizeLong(BTreeMap.kt:908)
> at org.mapdb.BTreeMap.getSize(BTreeMap.kt:898)
> at org.mapdb.BTreeMap.size(BTreeMap.kt:72)
> at org.mapdb.BTreeMap$entries$1.getSize(BTreeMap.kt:971)
> at org.mapdb.BTreeMap$entries$1.size(BTreeMap.kt:936)
> at java.base/java.util.Spliterators$IteratorSpliterator.estimateSize(Spliterators.java:1822)
> at java.base/java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:408)
> at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
> at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
> at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
> at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:558)
> at java.base/java.util.stream.ReferencePipeline.max(ReferencePipeline.java:594)

I've really given it up. Maybe you can try the latest version
