### ISSUE TITLE
org.mapdb.DB.checkNotClosed(DB.kt:153)

### ISSUE THREAD

**Issue by afshanz** [jankotek/mapdb#949]
Hi,
- I create a DBMaker.memoryDB() and overflow goes to DBMaker.fileDB()
- then I create HTreeMap with a given key later i clear and close HTreeMap instance
- and I have not closed my  both DB (memory and file) the I try to create again a  HTreeMap with the same key then i get the following exception 
 java.lang.IllegalAccessError: DB was closed
	at org.mapdb.DB.checkNotClosed(DB.kt:153)
	at org.mapdb.DB$Maker.make2(DB.kt:1373)
	at org.mapdb.DB$Maker.createOrOpen(DB.kt:1363)
	at org.mapdb.DB$HashMapMaker.createOrOpen(DB.kt:961)

**Comment by afshanz** [comment]
i am using mapdb 3.0.7 version
